---
title: 'bulk RNA-seq analysis' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
editor_options: 
  chunk_output_type: inline
params:
  cell_line: "HCC"
  data_out_dir: "./temp_data/" 

---

```{r}
if (interactive()) {
  source("./pipe.R")
  input = get_input(get_current_path())
  output = get_output(get_current_path())
}
```


```{r}
suppressPackageStartupMessages(library(GSEABase))
source_from_github(repositoy = "DEG_functions",version = "0.2.54")
```

# Create data
```{r}
bulk_Mar25 = read.table(
  file = input$rna_counts,
  sep = "\t",
  header = TRUE
) %>% as.data.frame() %>% 
  dplyr::select(!c("gene_id","gene_chr", "gene_start", "gene_end", "gene_strand","gene_biotype", "gene_description", "tf_family"))
gene_length = bulk_Mar25 %>% dplyr::pull("gene_length") 
rownames(bulk_Mar25) = make.unique(bulk_Mar25[,"gene_name",drop=T])
bulk_Mar25  = bulk_Mar25 %>% dplyr::select(!c("gene_length","gene_name")) 

tpm <- function(counts, lengths) {
  rpk <- counts / lengths
  coef <- sum(rpk) / 1e6
  rpk/coef
}

omitgenes= startsWith(rownames(bulk_Mar25),"ERCC")
bulk_Mar25=bulk_Mar25[!omitgenes,]
bulk_Mar25_TPM=apply(bulk_Mar25, 2, function(x) tpm(x, gene_length[!omitgenes])) %>%  
  as.data.frame()


```

```{r}
#adjust sample names
#read xlsx file
library(readxl)
sample_description = readxl::read_xlsx(input$sample_description, sheet = 1) %>% 
  as.data.frame() 

 sample_description = sample_description %>%  mutate(new_name = paste(sample_description$`Group Name\r\n(Required)`,c(1:3),sep = "_")) 


bulk_Mar25_TPM = bulk_Mar25_TPM[,sample_description$`Sample Name`]
colnames(bulk_Mar25_TPM) = sample_description$new_name
colnames(bulk_Mar25_TPM)  = colnames(bulk_Mar25_TPM) %>%  
  gsub(pattern = "_Osi_",replacement = "_osi_short_") %>% 
  gsub(pattern = "_OsiRox_",replacement = "_osi_short_roxa_") %>% 
  gsub(pattern = "_Per_",replacement = "_osi_persistor_") %>% 
  gsub(pattern = "_PerRox_",replacement = "_osi_persist_roxa_") 


```

# Inter cell lines comparision
```{r}
# create metadata
cell.labels = names(bulk_Mar25_TPM)
condition = str_extract(cell.labels, "HCC|H1975")
metadata = data.frame(condition = condition, row.names = colnames(bulk_Mar25_TPM))
```

```{r}
suppressPackageStartupMessages(library(DESeq2))
dds <- DESeqDataSetFromMatrix(countData = round(bulk_Mar25_TPM),
                              colData = metadata,
                              design = ~condition)
```
## filtering
```{r}
nrow(dds)
dds1 <- dds[ rowSums(counts(dds)) >= 3, ] # filter low count genes
nrow(dds1)
```

## PCA
```{r}
vst = vst(dds1, blind=FALSE)
```

```{r}
library("ggfortify")
PCAdata <- prcomp(t(assay(vst)))
autoplot(PCAdata, data = metadata,colour = "condition",label = FALSE, main="PCA") # Show dots
```

## Distance plot
```{r}
library(pheatmap)
vsd <- vst(dds, blind=FALSE)
sampleDists <- dist(t(assay(vsd)), method = "euclidean")
library("RColorBrewer")
sampleDistMatrix <- as.matrix(sampleDists)
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
pheatmap(sampleDistMatrix,
         clustering_distance_rows=sampleDists,
         clustering_distance_cols=sampleDists,
         col=colors, main = "Sample euclidean distance Matrix")
```

# Analysis
```{r}
# get cell line
cell_line_bulk = bulk_Mar25_TPM[,startsWith(colnames(bulk_Mar25_TPM),params$cell_line)]
```

```{r}
# create metadata
cell.labels = names(cell_line_bulk)
condition = str_extract(cell.labels, "Veh|osi_short_[1-9]|Rox|osi_short_roxa|osi_persistor|osi_persist_roxa") %>% gsub(pattern = "_[1-9]",replacement = "")
peristor = str_extract(cell.labels, "short|persist")
metadata = data.frame(condition = condition, row.names = colnames(cell_line_bulk))
```

```{r}
library(DESeq2)
dds <- DESeqDataSetFromMatrix(countData = round(cell_line_bulk),
                              colData = metadata,
                              design = ~condition)
```
## PCA
```{r}
nrow(dds)
dds1 <- dds[ rowSums(counts(dds)) >= 3, ] # filter low count genes
nrow(dds1)
```

```{r}
vst = vst(dds1, blind=FALSE)
```

```{r}
library("ggfortify")
PCAdata <- prcomp(t(assay(vst)))
autoplot(PCAdata, data = metadata,colour = "condition",label = FALSE, main=paste(params$cell_line,"PCA")) + 
  scale_color_manual(values = rainbow(6)) 


```
## DEG FC {.tabset}
```{r}
genesets = getGmt(input$genesets) %>% geneIds()


dds <- DESeq(dds)
cpVSop <- results(dds,contrast = c("condition","osi_persist_roxa","osi_persistor"))  %>% as.data.frame()
cpVSop$padj = p.adjust(cpVSop$pvalue, method = "fdr")
roxaVSctrl <- results(dds,contrast = c("condition","Rox","Veh"))  %>% as.data.frame()
diff_genes = data.frame(row.names = rownames(cpVSop), 
                        cpVSop_FC = cpVSop$log2FoldChange,
                        roxaVSctrl_FC = roxaVSctrl$log2FoldChange, 
                        cpVSop_padj = cpVSop$padj)
```
```{r}
# create 6 breaks between plot limits in log scale and then exponent, otherwise breaks not good
breaks_fun = function(limits){ 
  breaks = exp(-seq(-log(limits[1]), -log(limits[2]), length.out = 6))
  breaks[1] = breaks[1] * 0.95 #adjust extreme ticks to prevent truncation
  breaks[7] = breaks[7] * 1.05
  return(signif(breaks, digits = 2))
}

```



```{r fig.height=6, fig.width=13, results='asis'}
ranked_vec = cpVSop[,"log2FoldChange"]%>% setNames(rownames(cpVSop)) %>% na.omit() %>%  #order by FC
  sort(decreasing = T) # sort

hyp_obj <- hypeR_fgsea(ranked_vec, genesets, up_only = F)
plt = hyp_dots(hyp_obj,merge = F)
plt1 = plt$up+ aes(size=nes)+ggtitle("up in comboPersistor")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
plt2 = plt$dn+ aes(size=abs(nes))+ggtitle("up in osiPersistors")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
print_tab(plt1+plt2,title = paste(params$cell_line,"cpVSop"))


ranked_vec = roxaVSctrl[,"log2FoldChange"]%>% setNames(rownames(roxaVSctrl)) %>% na.omit() %>% # make named vector
  sort(decreasing = T) # sort 

hyp_obj <- hypeR_fgsea(ranked_vec, genesets, up_only = F)
plt = hyp_dots(hyp_obj,merge = F)
plt1 = plt$up+ aes(size=nes)+ggtitle("up in roxa")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
plt2 = plt$dn+ aes(size=abs(nes))+ggtitle("up in ctrl")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
print_tab(plt1+plt2,title = paste(params$cell_line,"roxaVSctrl"))
```

# DEG in comboVSosi but not in roxaVSctrl 

```{r}
diff_genes = data.frame(row.names = rownames(cpVSop), 
                        cpVSop_FC = 2**cpVSop$log2FoldChange,
                        roxaVSctrl_FC = 2**roxaVSctrl$log2FoldChange,
                        cpVSop_padj = cpVSop$padj)
```

```{r}
up_genes_df =  diff_genes %>% filter(cpVSop_FC > 2 & roxaVSctrl_FC<1.2 & cpVSop_padj<0.05) 
down_genes_df = diff_genes %>% filter(cpVSop_FC < 0.5 & roxaVSctrl_FC>0.8 & cpVSop_padj<0.05)
up_genes = up_genes_df %>% rownames()
down_genes = down_genes_df %>% rownames()

print_tab(cbind(up_genes_df,gene_description = bulk_Mar25_raw[bulk_Mar25_raw$gene_name %in% up_genes,"gene_description"]),
          title = "up")
print_tab(cbind(down_genes_df,gene_description = bulk_Mar25_raw[bulk_Mar25_raw$gene_name %in% down_genes,"gene_description"]),
          title = "up")

```

```{r}
if(length(up_genes)>=3){
  hyp_obj <- hypeR(up_genes, genesets, test = "hypergeometric", fdr=1, plotting=F,
                 background = rownames(bulk_Mar25_TPM))
  plt1 = hyp_dots(hyp_obj,title = paste("up in comboVSosi but not in roxaVSctrl -",params$cell_line))
  print(plt1)
}

```
```{r}
if(length(down_genes)>=3){
  hyp_obj <- hypeR(down_genes, genesets, test = "hypergeometric", fdr=1, plotting=F,
                   background = rownames(bulk_Mar25_TPM))
  plt2 = hyp_dots(hyp_obj,title = paste("down in comboVSosi but not in roxaVSctrl - ",params$cell_line))
  print(plt2)
}
```

```{r}
# expression heamap of genes
library(ComplexHeatmap)
SASP_signature = c(c("CCL2", "CCL5", "CCL7", "IL1A", "IL1B", "IL32"),c("SCG2", "INHBA", "INHA", "WNT7A", "CSF2", "TNFRSF11B", "GREM1", "CMTM3"))

signautre_expression = bulk_Mar25_TPM[SASP_signature[SASP_signature %in% rownames(bulk_Mar25_TPM)],] %>%  
  colMeans() %>% as.data.frame() %>% setNames("SASP_signature")


all_signature_expression_zscore = t(scale(signautre_expression)) %>% as.data.frame()

p = Heatmap(all_signature_expression_zscore, cluster_rows = F, cluster_columns = F, name = "TPM Z-score",column_title = "signatures")
p

SASP_signature = c(c("CCL2", "CCL5", "CCL7", "IL1A", "IL1B", "IL32"),c("SCG2", "INHBA", "INHA", "WNT7A", "CSF2", "TNFRSF11B", "GREM1", "CMTM3"))

signautre_expression = bulk_Mar25_TPM[SASP_signature[SASP_signature %in% rownames(bulk_Mar25_TPM)],] 


p = Heatmap(signautre_expression, cluster_rows = F, cluster_columns = F, name = "TPM",column_title = "signatures")
p

```

