---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
suffix ="_2Kvargenes"
xeno = readRDS("./Data/10x_xeno_1000.Rds")
xeno = FindVariableFeatures(object = xeno,nfeatures = 2000)
var_features = VariableFeatures(xeno) %>% as.character()
```



```{r}
library(reticulate)

sc <- import('scanpy', convert = FALSE)
adata <- sc$AnnData(
  X   = t(as.matrix(GetAssayData(xeno,slot='counts'))), #cnmf expect 10x counts
  obs = xeno[[]],
  var = GetAssay(xeno)[[]]
)
rm(xeno) #delete to save ram
```

```{python}
adata = r.adata
```


```{python}
# %matplotlib inline
# %load_ext autoreload
# %autoreload 2

import scanpy as sc
import matplotlib.pyplot as plt
import harmonypy
from harmonypy import run_harmony
import sys
from cnmf import cNMF

import numpy as np
import pandas as pd
from sklearn.decomposition import NMF
import seaborn as sns
import yaml
## copied from harmonypy.py
def moe_correct_ridge(Z_orig, Z_cos, Z_corr, R, W, K, Phi_Rk, Phi_moe, lamb):
    Z_corr = Z_orig.copy()
    for i in range(K):
        Phi_Rk = np.multiply(Phi_moe, R[i,:])
        x = np.dot(Phi_Rk, Phi_moe.T) + lamb
        W = np.dot(np.dot(np.linalg.inv(x), Phi_Rk), Z_orig.T)
        W[0,:] = 0 # do not remove the intercept
        Z_corr -= np.dot(W.T, Phi_Rk)
    Z_cos = Z_corr / np.linalg.norm(Z_corr, ord=2, axis=0)
    return Z_cos, Z_corr, W, Phi_Rk

```

```{python}
var_features = r.var_features

var_features_df = pd.Series(data=np.full(len(adata.var_names), False), index = adata.var_names)


for i,gene_name in enumerate(var_features_df.index):
  if gene_name in var_features:
    var_features_df[i] = True
  else:
    var_features_df[i] = False


adata.var['highly_variable'] = var_features_df
sc.pp.normalize_per_cell(adata)
adata = adata[:,adata.var['highly_variable']].copy()
sc.pp.scale(adata, zero_center=False, max_value=50)
sc.tl.pca(adata, use_highly_variable=False)
```

```{python}
sc.pl.pca_variance_ratio(adata, log=True)
plt.savefig("./Data/PCA.png")
```

```{python}
harmony_res = run_harmony(adata.obsm['X_pca'], adata.obs, 'orig.ident')
```

```{python}
X = np.array(adata[:,adata.var['highly_variable']].X)
_, X_corr, _, _ = moe_correct_ridge(X.T, None, None, harmony_res.R, None, harmony_res.K, None, harmony_res.Phi_moe, harmony_res.lamb)
X_corr = X_corr.T
adata.obsm['X_pca_harmony'] = harmony_res.Z_corr.T
```

```{python}
sc.pl.umap(adata, color=['orig.ident'])
plt.savefig('./Data/orig_umap.png', dpi=199)
```

```{python}
sc.pp.neighbors(adata, n_pcs=20, use_rep='X_pca_harmony')
sc.tl.umap(adata) #error when running on server
plt.savefig('./Data/corrected_umap.png')

```


```{python}
adata_corr = adata[:,adata.var['highly_variable']].copy()
adata_corr.X = X_corr
```

```{python}
suffix = r.suffix
X_corr_nonneg = X_corr.copy()
X_corr_nonneg[X_corr_nonneg<0]= 0
adata_corr_nonneg = adata_corr.copy()
adata_corr_nonneg.X = X_corr_nonneg
sc.write('./Data/cnmf/xeno_Harmony_NoNeg' + suffix +'.h5ad', adata_corr_nonneg)
```

cNMF:

```{python}
name = 'cNMF_patients_Varnorm_Harmony' + suffix
outdir = './Data/cnmf'
K_range = np.arange(3,9)
cnmf_obj = cNMF(output_dir=outdir, name=name)
cnmf_obj.prepare(counts_fn='./Data/cnmf/xeno_Harmony_NoNeg'+ suffix +'.h5ad', components=K_range, n_iter=10, seed=14, densify=True)
```

```{python}
cnmf_obj.factorize(worker_i=0, total_workers=1)
```

```{python}
cnmf_obj.combine()
cnmf_obj.k_selection_plot()
```


```{python}
import pickle
f = open('./Data/cnmf/xeno' + suffix +'_cnmf_obj.pckl', 'wb')
pickle.dump(cnmf_obj, f)
f.close()
```