# Generated by MakefileR, do not edit by hand

.Phony: all

all: xeno_preprocess patients_preprocess xeno_clustering patients_clustering patients_deg patients_run_sipsic patients_sipsic_analysis xenografts_deg xenografts_run_sipsic xeno_sipsic_analysis xeno_cnmf_preprocess xeno_cnmf_run calculate_programs models_programs_analysis bivona_preprocess patients_bivona_programs_calc patients_programs_analysis bivona_programs_analysis bulk_cell_lines_OSI bulk_mar25_HCC bulk_mar25_H1975 march25_all_analysis

# ============
# xeno_preprocess
# ============

xeno_preprocess: ./Reports/xeno/00_preprocess/01_preprocess.html ./Reports/xeno/00_preprocess/xeno.qs
	@echo  $@ is up to date

./Reports/xeno/00_preprocess/01_preprocess.html ./Reports/xeno/00_preprocess/xeno.qs: ./Notebooks/xeno/00_preprocess.Rmd
	Rscript render.R xeno_preprocess

# ============
# patients_preprocess
# ============

patients_preprocess: ./Reports/patients/00_preprocess/00_preprocess.html ./Reports/patients/00_preprocess/patients.qs
	@echo  $@ is up to date

./Reports/patients/00_preprocess/00_preprocess.html ./Reports/patients/00_preprocess/patients.qs: ./Notebooks/patients/00_preprocess.Rmd ./input_data/patients_raw/fc.txt.gz
	Rscript render.R patients_preprocess

# ============
# xeno_clustering
# ============

xeno_clustering: ./Reports/xeno/001_clustering/001_clustering.html
	@echo  $@ is up to date

./Reports/xeno/001_clustering/001_clustering.html: ./Notebooks/xeno/001_clustering.Rmd ./Reports/xeno/00_preprocess/xeno.qs
	Rscript render.R xeno_clustering

# ============
# patients_clustering
# ============

patients_clustering: ./Reports/patients/001_clustering/001_clustering.html
	@echo  $@ is up to date

./Reports/patients/001_clustering/001_clustering.html: ./Notebooks/patients/001_clustering.Rmd ./Reports/patients/00_preprocess/patients.qs
	Rscript render.R patients_clustering

# ============
# patients_deg
# ============

patients_deg: ./Reports/patients/01_DEG/01_DEG.html
	@echo  $@ is up to date

./Reports/patients/01_DEG/01_DEG.html: ./Notebooks/patients/01_DEG.Rmd ./Reports/patients/00_preprocess/patients.qs ./input_data/HIF_targets_Lombardi_PMC9869179.txt ./input_data/h.all.v2023.2.Hs.symbols.gmt
	Rscript render.R patients_deg

# ============
# patients_run_sipsic
# ============

patients_run_sipsic: ./Reports/patients/02_run_sipsic/02_run_sipsic.html ./Reports/patients/02_run_sipsic/patients_pathwayScoresMatrix.RDS
	@echo  $@ is up to date

./Reports/patients/02_run_sipsic/02_run_sipsic.html ./Reports/patients/02_run_sipsic/patients_pathwayScoresMatrix.RDS: ./Notebooks/patients/02_run_sipsic.Rmd ./Reports/patients/00_preprocess/patients.qs ./input_data/HIF_targets_Lombardi_PMC9869179.txt ./input_data/h.all.v2023.2.Hs.symbols.gmt
	Rscript render.R patients_run_sipsic

# ============
# patients_sipsic_analysis
# ============

patients_sipsic_analysis: ./Reports/patients/03_sipsic_analysis/03_sipsic_analysis.html
	@echo  $@ is up to date

./Reports/patients/03_sipsic_analysis/03_sipsic_analysis.html: ./Notebooks/patients/03_sipsic_analysis.Rmd ./Reports/patients/00_preprocess/patients.qs ./Reports/patients/02_run_sipsic/patients_pathwayScoresMatrix.RDS
	Rscript render.R patients_sipsic_analysis

# ============
# xenografts_deg
# ============

xenografts_deg: ./Reports/xeno/01_DEG/01_DEG.html
	@echo  $@ is up to date

./Reports/xeno/01_DEG/01_DEG.html: ./Notebooks/xeno/01_DEG.Rmd ./Reports/xeno/00_preprocess/xeno.qs ./input_data/HIF_targets_Lombardi_PMC9869179.txt ./input_data/h.all.v2023.2.Hs.symbols.gmt
	Rscript render.R xenografts_deg

# ============
# xenografts_run_sipsic
# ============

xenografts_run_sipsic: ./Reports/xeno/02_run_SiPSiC/02_run_SiPSiC.html ./Reports/xeno/02_run_SiPSiC/xeno_pathwayScoresMatrix.RDS
	@echo  $@ is up to date

./Reports/xeno/02_run_SiPSiC/02_run_SiPSiC.html ./Reports/xeno/02_run_SiPSiC/xeno_pathwayScoresMatrix.RDS: ./Notebooks/xeno/02_run_SiPSiC.Rmd ./Reports/xeno/00_preprocess/xeno.qs ./input_data/HIF_targets_Lombardi_PMC9869179.txt ./input_data/h.all.v2023.2.Hs.symbols.gmt
	Rscript render.R xenografts_run_sipsic

# ============
# xeno_sipsic_analysis
# ============

xeno_sipsic_analysis: ./Reports/xeno/03_SiPSiC/03_SiPSiC.html ./Reports/xeno/03_SiPSiC/xeno_sipsic_hallmarks_logFC.tsv ./Reports/xeno/03_SiPSiC/xeno_sipsic_hallmarks_fdr_df.tsv
	@echo  $@ is up to date

./Reports/xeno/03_SiPSiC/03_SiPSiC.html ./Reports/xeno/03_SiPSiC/xeno_sipsic_hallmarks_logFC.tsv ./Reports/xeno/03_SiPSiC/xeno_sipsic_hallmarks_fdr_df.tsv: ./Notebooks/xeno/03_SiPSiC.Rmd ./Reports/xeno/00_preprocess/xeno.qs ./Reports/xeno/02_run_SiPSiC/xeno_pathwayScoresMatrix.RDS
	Rscript render.R xeno_sipsic_analysis

# ============
# xeno_cnmf_preprocess
# ============

xeno_cnmf_preprocess: ./Reports/xeno/04_cnmf/01_create_data_for_cnmf/01_create_data_for_cnmf.html ./Reports/xeno/04_cnmf/01_create_data_for_cnmf/xeno_counts_filtered.h5ad
	@echo  $@ is up to date

./Reports/xeno/04_cnmf/01_create_data_for_cnmf/01_create_data_for_cnmf.html ./Reports/xeno/04_cnmf/01_create_data_for_cnmf/xeno_counts_filtered.h5ad: ./Notebooks/xeno/04_cnmf/01_create_data_for_cnmf.Rmd ./Reports/xeno/00_preprocess/xeno.qs
	Rscript render.R xeno_cnmf_preprocess

# ============
# xeno_cnmf_run
# ============

xeno_cnmf_run: Reports/xeno/04_cnmf/02_run_cnmf_1.7/models_2Kvargenes_corrected_noTPM_cnmf_obj.pckl
	@echo  $@ is up to date

Reports/xeno/04_cnmf/02_run_cnmf_1.7/models_2Kvargenes_corrected_noTPM_cnmf_obj.pckl: ./Notebooks/xeno/04_cnmf/02_run_cnmf/sbatch_cnmf_script.sh
	./Notebooks/xeno/04_cnmf/02_run_cnmf/sbatch_cnmf_script.sh

# ============
# calculate_programs
# ============

calculate_programs: ./Reports/xeno/04_cnmf/04_calculate_programs/04_calculate_programs.html ./Reports/xeno/04_cnmf/04_calculate_programs/cell_usage_by_TPM.RDS ./Reports/xeno/04_cnmf/04_calculate_programs/gep_scores.RDS
	@echo  $@ is up to date

./Reports/xeno/04_cnmf/04_calculate_programs/04_calculate_programs.html ./Reports/xeno/04_cnmf/04_calculate_programs/cell_usage_by_TPM.RDS ./Reports/xeno/04_cnmf/04_calculate_programs/gep_scores.RDS: Notebooks/xeno/04_cnmf/04_calculate_programs.Rmd ./Reports/xeno/00_preprocess/xeno.qs Reports/xeno/04_cnmf/02_run_cnmf_1.7/models_2Kvargenes_corrected_noTPM_cnmf_obj.pckl ./input_data/h.all.v2023.2.Hs.symbols.gmt
	Rscript render.R calculate_programs

# ============
# models_programs_analysis
# ============

models_programs_analysis: ./Reports/xeno/04_cnmf/05_models_cnmf_analysis_k5/05_models_cnmf_analysis_k5.html
	@echo  $@ is up to date

./Reports/xeno/04_cnmf/05_models_cnmf_analysis_k5/05_models_cnmf_analysis_k5.html: ./Notebooks/xeno/04_cnmf/05_models_cnmf_analysis_k5.Rmd ./Reports/xeno/00_preprocess/xeno.qs ./Reports/xeno/04_cnmf/04_calculate_programs/cell_usage_by_TPM.RDS ./Reports/xeno/04_cnmf/04_calculate_programs/gep_scores.RDS ./input_data/HIF_targets_Lombardi_PMC9869179.txt ./input_data/h.all.v2023.2.Hs.symbols.gmt
	Rscript render.R models_programs_analysis

# ============
# bivona_preprocess
# ============

bivona_preprocess: ./Reports/Bivona/01_preprocess/01_preprocess.html ./Reports/Bivona/01_preprocess/bivona.qs
	@echo  $@ is up to date

./Reports/Bivona/01_preprocess/01_preprocess.html ./Reports/Bivona/01_preprocess/bivona.qs: ./Notebooks/Bivona/01_preprocess.Rmd ./input_data/Bivona_scRNAseq/NI04_tumor_seurat_object.RData
	Rscript render.R bivona_preprocess

# ============
# patients_bivona_programs_calc
# ============

patients_bivona_programs_calc: ./Reports/patients/04_patients_cnmf_k5_from_xeno_calc/04_patients_cnmf_k5_from_xeno_calc.html ./Reports/patients/04_patients_cnmf_k5_from_xeno_calc/patients_cell_usage.RDS ./Reports/patients/04_patients_cnmf_k5_from_xeno_calc/bivona_cell_usage.RDS
	@echo  $@ is up to date

./Reports/patients/04_patients_cnmf_k5_from_xeno_calc/04_patients_cnmf_k5_from_xeno_calc.html ./Reports/patients/04_patients_cnmf_k5_from_xeno_calc/patients_cell_usage.RDS ./Reports/patients/04_patients_cnmf_k5_from_xeno_calc/bivona_cell_usage.RDS: ./Notebooks/patients/04_patients_cnmf_k5_from_xeno_calc.Rmd ./Reports/patients/00_preprocess/patients.qs ./Reports/Bivona/01_preprocess/bivona.qs ./Reports/xeno/04_cnmf/04_calculate_programs/gep_scores.RDS Reports/xeno/04_cnmf/02_run_cnmf_1.7/models_2Kvargenes_corrected_noTPM_cnmf_obj.pckl
	Rscript render.R patients_bivona_programs_calc

# ============
# patients_programs_analysis
# ============

patients_programs_analysis: ./Reports/patients/05_patients_cnmf_k5_from_xeno/05_patients_cnmf_k5_from_xeno.html
	@echo  $@ is up to date

./Reports/patients/05_patients_cnmf_k5_from_xeno/05_patients_cnmf_k5_from_xeno.html: ./Notebooks/patients/05_patients_cnmf_k5_from_xeno.Rmd ./Reports/patients/00_preprocess/patients.qs ./Reports/patients/04_patients_cnmf_k5_from_xeno_calc/patients_cell_usage.RDS ./input_data/h.all.v2023.2.Hs.symbols.gmt ./input_data/HIF_targets_Lombardi_PMC9869179.txt
	Rscript render.R patients_programs_analysis

# ============
# bivona_programs_analysis
# ============

bivona_programs_analysis: ./Reports/Bivona/02_bivona_cnmf_analysis/02_bivona_cnmf_analysis.html
	@echo  $@ is up to date

./Reports/Bivona/02_bivona_cnmf_analysis/02_bivona_cnmf_analysis.html: ./Notebooks/Bivona/02_bivona_cnmf_analysis.Rmd ./Reports/Bivona/01_preprocess/bivona.qs ./Reports/patients/04_patients_cnmf_k5_from_xeno_calc/bivona_cell_usage.RDS ./input_data/h.all.v2023.2.Hs.symbols.gmt ./input_data/HIF_targets_Lombardi_PMC9869179.txt
	Rscript render.R bivona_programs_analysis

# ============
# bulk_cell_lines_OSI
# ============

bulk_cell_lines_OSI: ./Reports/Bulk/01_cell_lines_OSI/01_cell_lines_OSI.html
	@echo  $@ is up to date

./Reports/Bulk/01_cell_lines_OSI/01_cell_lines_OSI.html: ./Notebooks/Bulk/01_cell_lines_OSI.Rmd ./input_data/cell_lines/OSI_bulk/OSI_bulk_cell_lines_noMTGLKI_tpm.txt ./input_data/HIF_targets_Lombardi_PMC9869179.txt
	Rscript render.R bulk_cell_lines_OSI

# ============
# bulk_mar25_HCC
# ============

bulk_mar25_HCC: ./Reports/Bulk/03_bulk_cell_lines_march25/mar25_analysis_HCC/mar25_analysis_HCC.html ./Reports/Bulk/03_bulk_cell_lines_march25/mar25_analysis_HCC/HCC_comboVSosi_not_roxaVSctrl.txt
	@echo  $@ is up to date

./Reports/Bulk/03_bulk_cell_lines_march25/mar25_analysis_HCC/mar25_analysis_HCC.html ./Reports/Bulk/03_bulk_cell_lines_march25/mar25_analysis_HCC/HCC_comboVSosi_not_roxaVSctrl.txt: ./Notebooks/Bulk/03_bulk_cell_lines_march25/HCC_mar25_analysis.Rmd ./input_data/cell_lines/OSI_roxa_march25/Mar25_noMTGLKI_tpm.txt ./input_data/HIF_targets_Lombardi_PMC9869179.txt ./input_data/cell_lines/OSI_roxa_march25/RK_BIFSAMPLE.xlsx ./input_data/h.all.v2023.2.Hs.symbols.gmt ./input_data/pathways_from_papers/FRIDMAN_SENESCENCE_UP.v2024.1.Hs.gmt
	Rscript render.R bulk_mar25_HCC

# ============
# bulk_mar25_H1975
# ============

bulk_mar25_H1975: ./Reports/Bulk/03_bulk_cell_lines_march25/mar25_analysis_H1975/mar25_analysis_H1975.html ./Reports/Bulk/03_bulk_cell_lines_march25/mar25_analysis_H1975/H1975_comboVSosi_not_roxaVSctrl.txt
	@echo  $@ is up to date

./Reports/Bulk/03_bulk_cell_lines_march25/mar25_analysis_H1975/mar25_analysis_H1975.html ./Reports/Bulk/03_bulk_cell_lines_march25/mar25_analysis_H1975/H1975_comboVSosi_not_roxaVSctrl.txt: ./Notebooks/Bulk/03_bulk_cell_lines_march25/H1975_mar25_analysis.Rmd ./input_data/cell_lines/OSI_roxa_march25/Mar25_noMTGLKI_tpm.txt ./input_data/HIF_targets_Lombardi_PMC9869179.txt ./input_data/cell_lines/OSI_roxa_march25/RK_BIFSAMPLE.xlsx ./input_data/h.all.v2023.2.Hs.symbols.gmt ./input_data/pathways_from_papers/FRIDMAN_SENESCENCE_UP.v2024.1.Hs.gmt
	Rscript render.R bulk_mar25_H1975

# ============
# march25_all_analysis
# ============

march25_all_analysis: ./Reports/Bulk/03_bulk_cell_lines_march25/all_cell_lines_analysis/all_cell_lines_analysis.html
	@echo  $@ is up to date

./Reports/Bulk/03_bulk_cell_lines_march25/all_cell_lines_analysis/all_cell_lines_analysis.html: ./Notebooks/Bulk/03_bulk_cell_lines_march25/all_cell_lines_analysis.Rmd ./input_data/cell_lines/OSI_roxa_march25/Mar25_noMTGLKI_tpm.txt ./input_data/HIF_targets_Lombardi_PMC9869179.txt ./input_data/cell_lines/OSI_roxa_march25/RK_BIFSAMPLE.xlsx ./input_data/h.all.v2023.2.Hs.symbols.gmt ./Reports/Bulk/03_bulk_cell_lines_march25/mar25_analysis_HCC/HCC_comboVSosi_not_roxaVSctrl.txt ./Reports/Bulk/03_bulk_cell_lines_march25/mar25_analysis_H1975/H1975_comboVSosi_not_roxaVSctrl.txt ./input_data/pathways_from_papers/FRIDMAN_SENESCENCE_UP.v2024.1.Hs.gmt
	Rscript render.R march25_all_analysis
