---
title: "R Notebook"
output: 
  html_notebook: 
    code_folding: hide
---

## Data
```{r}
lung = readRDS("./Data/lung_cancercells_withTP_onlyPatients.rds")
```

```{r}
suffix ="2Kvargenes_normalized_2-7theta"
```

```{python}
suffix = r.suffix
import pickle
f = open('./Data/cnmf/cnmf_objects/patients_' + suffix + '_cnmf_obj.pckl', 'rb')
cnmf_obj = pickle.load(f)
f.close()
```
## Functionres

```{r}
library(stringi)
source_from_github(repositoy = "DEG_functions",version = "0.2.1")
source_from_github(repositoy = "cNMF_functions",version = "0.3.21",script_name = "cnmf_function_Harmony.R")
```

```{r}
selected_k = 5
suffix = paste(suffix,paste0(selected_k,"nmfK"),sep="_")
print(suffix)
```

```{python}
selected_k = int(r.selected_k)
density_threshold = 0.1
cnmf_obj.consensus(k=selected_k, density_threshold=density_threshold,show_clustering=True)
usage_norm, gep_scores, gep_tpm, topgenes = cnmf_obj.load_results(K=selected_k, density_threshold=density_threshold)
```

## gep scores by expression
```{r}
gep_scores= py$gep_scores %>% t() %>%  as.matrix()
expression = lung@assays$RNA@data %>% as.matrix()
expression = expression[rownames(expression) %in% colnames(gep_scores),]

my_usage = gep_scores%*%expression
all_metagenes = my_usage %>% t() %>% as.data.frame()
   
 # for (col_num in 1:ncol(all_metagenes)){
 #      program_sum = sum(all_metagenes[,col_num])
 #      norm_program = all_metagenes[,col_num]/program_sum 
 #      all_metagenes[,col_num] = norm_program
 #    }
```

```{r}
#Add to seurat metadata:

library(reticulate)
all_metagenes= py$usage_norm
```

```{r fig.height=10, fig.width=10}

#Make metagene names
for (i in 1:ncol(all_metagenes)) {
  colnames(all_metagenes)[i] = "metagene." %>% paste0(i)
}

#add each metagene to metadata
for (i in 1:ncol(all_metagenes)) {
  metage_metadata = all_metagenes %>% select(i)
  lung = AddMetaData(object = lung,metadata = metage_metadata)
}
```



```{r fig.height=10, fig.width=10}
FeaturePlot(object = lung,features = colnames(all_metagenes))
```

## Enrichment analysis by top 200 genes of each program
```{r fig.height=8, fig.width=8, results='hide'}
gep_scores = py$gep_scores
plt_list = list()
for (i in 1:ncol(gep_scores)) {
  top_genes = gep_scores  %>%  arrange(desc(gep_scores[i])) #sort by score a
  top = head(rownames(top_genes),200) #take top top_genes_num
  res = genes_vec_enrichment(genes = top,background = rownames(gep_scores),homer = T,title = 
                    i,silent = T,return_all = T)
   
  plt_list[[i]] = res$plt
}
gridExtra::grid.arrange(grobs = plt_list)
```

## Enrichment analysis by selecting genes using "max" method
```{r fig.height=7, fig.width=7, results='hide'}
gep_scores = py$gep_scores
plt_list = list()

library(NMF)
top_features = extractFeatures(object = gep_scores %>% data.matrix(),method ="max")
for (i in 1:length(top_features)) {
  top_features[[i]]= rownames(gep_scores)[top_features[[i]]]
}

for (i in 1:ncol(gep_scores)) {
top = top_features[i] %>% unlist()
  try({ 
 res = genes_vec_enrichment(genes = top,background = rownames(gep_scores),homer = T,title = 
                    i,silent = T,return_all = T)
      plt_list[[i]] = res$plt
    }, silent=TRUE)
}
plt_list = Filter(Negate(is.null), plt_list) #remove null plots


gridExtra::grid.arrange(grobs = plt_list)

```
## Enriched in patient
```{r fig.height=5, fig.width=7}
lung = SetIdent(object = lung,value = "patient.ident")
VlnPlot(object = lung,features = colnames(all_metagenes))
```
## Enriched in time point
```{r}
lung = program_assignment(dataset = lung,larger_by = 2,program_names = colnames(all_metagenes))
```   

```{r}
data =FetchData(object = lung,vars = c("program.assignment","time.point"))
data = data %>% dplyr::count(program.assignment, time.point) %>%  dplyr::add_count(time.point, wt = n, name = "overall")%>% 
mutate(proportion = n / overall)   

plt_list = list()
for (program_name in unique(data$program.assignment)) {
  program_data = data[data$program.assignment == program_name,]
  p = ggplot(data=program_data, aes(x=time.point, y=proportion)) +geom_bar(stat="identity")+ylab("precentage") +ggtitle("program" %>% paste(program_data$program.assignment %>% unique() %>% as.character())) +
    scale_y_continuous(limits = c(0,1))  
    plt_list[[program_name]] = p
}
gridExtra::grid.arrange(grobs = plt_list)

```

```{r}
DimPlot(lung,group.by = "program.assignment")

# DimPlot(lung,group.by = "program.assignment",cols = c("red","darkgreen","blue","grey"))
```



