---
title: "Title"
author: "Avishai Wizel"
date: '`r Sys.Date()`'
output: 
  html_notebook: 
    code_folding: hide
---
Generate EGFR patients counts and normalize it according to:
https://docs.scvi-tools.org/en/stable/tutorials/notebooks/tabula_muris.html#Normalize-Smartseq2-matrix-by-gene-length
```{r}


tpm <- function(counts, lengths) {
  
  rpk <- counts / lengths
  coef <- sum(rpk) / 1e6
  rpk/coef
}

lung.data_raw <- read.delim("./Data/fc.txt",skip=0,header=T,sep="\t",stringsAsFactors=F)
rownames(lung.data_raw)<- make.unique(lung.data_raw$gene_name)
lengths <- lung.data_raw[,6] 
lengths_df <- lung.data_raw[,6,drop=F] 
omitgenes <- startsWith(rownames(lung.data_raw),"MT-")|startsWith(rownames(lung.data_raw),"ERCC-")
lung.data <- lung.data_raw[,8:ncol(lung.data_raw)]

# changing the cell labels
cell.labels <- gsub(".gene_counts.tsv","",colnames(lung.data))
cell.labels <- gsub(".sort.bam","",cell.labels)
cell.labels <- gsub("_",".",cell.labels)
cell.labels <- gsub(".S[0-9]*","",cell.labels)
t <- regexpr("[A-H][0-9]+$", cell.labels)
cell.labels[t<0] <- paste0(regmatches(cell.labels[t<0], regexpr("[^ACGT]*", cell.labels[t<0])),regmatches(colnames(lung.data)[t<0], regexpr("_S[0-9]+", colnames(lung.data)[t<0])))
well <- regmatches(cell.labels, regexpr("[A-H,S][0-9]+$", cell.labels))
plate <- substr(cell.labels,1,nchar(cell.labels)-nchar(well)-1)

colnames(lung.data) <- paste(plate,well,sep="_")
lung.tpm <- apply(lung.data[!omitgenes,1:dim(lung.data)[2]], 2, function(x) tpm(x, lengths[!omitgenes]) )
colnames(lung.tpm) <- paste(plate,well,sep="_")

```

```{r}
#make sure lung.tpm is like known lung:
log2(lung.tpm["DDX11L1","MGH1066.1.P6_A10"]+1) # tpm > log2(tpm+1)
lung["DDX11L1","MGH1066.1.P6_A10"]@assays$RNA@counts %>% as.numeric() #already in log2(tpm)
```
```{r}
#save lung.data
library(SeuratData)
library(SeuratDisk)
lung_data <- CreateSeuratObject(counts = lung.data, project = "lung", min.cells = 3, min.features = 200)
lung_data= lung_data [rownames(lung_data )%in% rownames(lung),colnames(lung_data )%in% colnames(lung) ]
SaveH5Seurat(lung_data, filename = "./Data/lung_data.h5Seurat")
Convert("./Data/lung_data.h5Seurat", dest = "h5ad")
```

```{r}
library(reticulate)
rownames(lengths_df) = rownames(lengths_df) %>% gsub(pattern = "_",replacement = "-") #replace underscores with dash like seurat
lengths_df = lengths_df[rownames(lengths_df) %in% rownames(lung_data),,drop=F]
```

```{python}
import scanpy as sc
import numpy as np
import pandas as pd
gene_len = r.lengths_df
lung_data = sc.read("./Data/lung_data.h5ad")
```

```{python}
gene_len = gene_len.reindex(lung_data.var.index).dropna()
assert (lung_data.var.index == gene_len.index).sum() == lung_data.shape[1]
lung_data.X = lung_data.X / gene_len['Length'].values * np.median(gene_len['Length'].values)
# round to integer
lung_data.X = np.rint(lung_data.X)

norm_counts_patients = pd.DataFrame(data=norm_counts_patients.T,    # values
index=lung_data.var.index,    # 1st column as index
columns=lung_data.obs_names)  # 1st row as the column names
```

```{r}
norm_counts_patients = py$norm_counts_patients %>% t()
saveRDS(object = norm_counts_patients,file = "./Data/norm_counts_patients.rds")
```

