---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.Date()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
---

## Parameters

```{r warning=FALSE}
suffix = ""
data_to_read = ""
```


## functions

```{r warning=FALSE}
library(stringi)
source_from_github(repositoy = "DEG_functions",version = "0.2.54")
  ```

## Data

```{r}
xeno = readRDS("./Data/10x_xeno_1000.Rds")
lung = readRDS("./Data/lung_cancercells_withTP_onlyPatients.rds")
lung_patients = lung$patient.ident %>% unique() %>% as.character()
lung_patients_filtered = lung_patients[!(lung_patients %in% c("X1055new","X1099"))] #remove patients with less then 100 cells
lung = subset(x = lung,subset = patient.ident %in% lung_patients_filtered)
```

## Patients DEG
```{r}
patients_list = lung$patient.ident %>% unique()
lung = SetIdent(object = lung,value = "time.point")

first_up = list() #all first group up genes
second_up = list() #all second group up genes
for (patient in patients_list) {
  patient_data = subset(x = lung,subset = patient.ident == patient)
  features = filter_features(object = patient_data,ident.1 = "pre-treatment",ident.2 = "on-treatment",min.pct = 0.1)
  deg_df = FindMarkers(object = patient_data,ident.1 = "pre-treatment",ident.2 = "on-treatment",densify = T,features = features)
  
  #add first up genes vector and background:
  deg_vector = deg_df %>% mutate(fdr = p.adjust(p_val,method = "fdr"))%>% #add fdr
    filter(avg_log2FC>1.5 & fdr<0.05) %>% #filter significant
    rownames() #get genes
  bg = features
  first_up[[patient]] =  list(deg = deg_vector, bg = bg)
  
  #add second up genes vector and background:
  deg_vector = deg_df %>% mutate(fdr = p.adjust(p_val,method = "fdr"))%>% #add fdr
    filter(avg_log2FC<(-1.5) & fdr<0.05) %>% #filter significant
    rownames() #get genes
  bg = features
  second_up[[patient]] =  list(deg = deg_vector, bg = bg)


}
```

```{r fig.height=4, fig.width=10}
require(gridExtra)

for (patient in patients_list) {
  downreg  = genes_vec_enrichment(genes = first_up[[patient]]$deg,background = first_up[[patient]]$bg,homer = T,title = paste(patient,"downregulated during treatment"),bar_color = "indianred2",return_all = T,silent = T)
    upreg = genes_vec_enrichment(genes = second_up[[patient]]$deg,background = second_up[[patient]]$bg,homer = T,title = paste(patient,"upregulated during treatment"),return_all = T,silent = T)
  grid.arrange(downreg$plt, upreg$plt, ncol=2)

}
```



## Xeno DEG

```{r}
patients_list = xeno$orig.ident %>% unique()
xeno = SetIdent(object = xeno,value = "treatment")

for (patient in patients_list) {
  patient_data = subset(x = xeno,subset = orig.ident == patient)
  deg_df = FindMarkers(object = patient_data,ident.1 = "NT",ident.2 = "OSI",densify = T,mean.fxn = function(x) {
    return(log(x = rowMeans(x = x) + 1, base = 2))
  })
  volcano_plot(deg_df,top_genes_text = 5,ident1 = "NT",ident2 = "OSI")
  
  
  #add first up genes vector and background:
  deg_vector = deg_df %>% mutate(fdr = p.adjust(p_val,method = "fdr"))%>% #add fdr
    filter(avg_log2FC>1.5 & fdr<0.05) %>% #filter significant
    rownames() #get genes
  bg = features
  first_up[[patient]] =  list(deg = deg_vector, bg = bg)
  
  #add second up genes vector and background:
  deg_vector = deg_df %>% mutate(fdr = p.adjust(p_val,method = "fdr"))%>% #add fdr
    filter(avg_log2FC<(-1.5) & fdr<0.05) %>% #filter significant
    rownames() #get genes
  bg = features
  second_up[[patient]] =  list(deg = deg_vector, bg = bg)


}
```
```{r fig.height=4, fig.width=10}
require(gridExtra)

for (patient in patients_list) {
  downreg  = genes_vec_enrichment(genes = first_up[[patient]]$deg,background = first_up[[patient]]$bg,homer = T,title = paste(patient,"downregulated during treatment"),bar_color = "indianred2",return_all = T,silent = T)
    upreg = genes_vec_enrichment(genes = second_up[[patient]]$deg,background = second_up[[patient]]$bg,homer = T,title = paste(patient,"upregulated during treatment"),return_all = T,silent = T)
  grid.arrange(downreg$plt, upreg$plt, ncol=2)

}
```






