---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
---



# Functions

```{r warning=FALSE}
# modify dotplot to be without exponent of the expression
newDef <- deparse(DotPlot)
newDef[57] =  "            return(mean(x =  x))"
newDef[136] =  "            yes = \"Identity\", no = \"Split Identity\")) + cowplot::theme_cowplot()" #add package name
newDef[95] = "                data.use <- data.use" # remove log
newDef[146] = "        plot <- plot + scale_color_distiller(palette = cols,  direction = 1)"
DotPlot.2 <- eval(parse(text=newDef))
```

# Data

```{r}

```


```{r}
library("readxl")
GSE17708 <- read_excel("./Data/EMT_pathways/GSE17708_Keshamouni_TGFB1_logs.xls",sheet = 1,progress = T,cell_cols("BC")) %>% dplyr::slice(3:n())
GSE17708_genes <- read_excel("./Data/EMT_pathways/GSE17708_Keshamouni_TGFB1_logs.xls",sheet = 1,progress = T,cell_cols("B"))
GSE17708 = cbind(GSE17708,GSE17708_genes) 
GSE17708_72H_UP_df = GSE17708 %>% set_names(c("deg","gene")) %>% filter(deg > 1) %>% dplyr::select(gene) #take up genes
GSE17708_72H_UP = GSE17708_72H_UP_df %>% filter(!gene == "---") %>% pull(gene) # remove na gene symbols
GSE17708_72H_UP = GSE17708_72H_UP %>% strsplit(split = " /// ") %>% unlist() %>% unique() # split ambiguous genes
```

```{r}
bayers_EMT = c("ZEB1	LIX1L	VIM	AXL	MMPT	ANTXR2	C3orf21	FN1	NRP1	TGFBI	GALNT5	PPARG	FN1	HNMT	CARD6	RBPMS	TNFRSF21	TMEM45B	MPP7	SSH3	MTAC2D1	MUC1	EPPK1	SHROOM3	EPN3	PRSS22	AP1M2	SH3YL1	KLC3	SERINC2	EVPL	FXYD3	CLDN4	CRB3	LRRC54	MAPK13	EPPK1	GALNT3	STAP2	AP1M2	DSP	ELMO3	KRTCAP3	MAL2	F11R	GPR110	GPT56	KRT19	GRHL1	BSPRY	C1orf116	S100A14	SPINT2	ANKRD22	ST14	GRHL2	PRR5	BSPRY	TJP3	TACSTD2	CDH3	C1orf172	CDS1	PRR5	MPZL2	INADL	EPN3	RBM35A	TMC4	ITGB6	TMEM125	EPHA1	CDS1	ENPP5	ST14	EPB41L5	ERBB3	RAB25	PRSS8	TMEM30B	CLDN7	RBM35A	TACSTD1	CDS1	SCNN1A	CDH1") %>% strsplit(split = "\t") %>% unlist() %>% unique()
bayers_mes = bayers_EMT[1:16]
bayers_epi = bayers_EMT[17:length(bayers_EMT)]

```

```{r}
hEMT = c("PDPN, ITGA5, ITGA6, TGFBI, LAMC2, MMP10, LAMA3, CDH13, SERPINE1, P4HA2, TNC, MMP1")%>% strsplit(split = ", ") %>% unlist() %>% unique()
epi_genes = c("CDH1, DSP, OCLN, CRB3")%>% strsplit(split = ", ") %>% unlist() %>% unique()
mes_genes = c("VIM, CDH2, FOXC2, SNAI1, SNAI2, TWIST1, FN1, ITGB6, MMP2, MMP3, MMP9, SOX10, GSC, ZEB1, ZEB2, TWIST2")%>% strsplit(split = ", ") %>% unlist() %>% unique()
```

```{r}
hallmark_emt = genesets$HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION
```


# calculate score- scaled data
```{r }
gene_list = list(hallmark_emt = hallmark_emt, GSE17708_72H_UP = GSE17708_72H_UP,bayers_mes = bayers_mes,bayers_epi = bayers_epi,Tagli_hEMT = hEMT,Tagli_epi = epi_genes,Tagli_mes = mes_genes)

idx=1
for (dataset in list(xeno,lung)) {
  dataset = ScaleData(object = dataset,features = unlist(gene_list))
  for (i in seq_along(gene_list)) {
    genes = gene_list[[i]]
    genes = genes[genes %in% rownames(dataset)]
    name = names(gene_list)[i]
    scores = dataset@assays$RNA@scale.data[genes,] %>% colMeans()
    dataset %<>% AddMetaData(metadata = scores,col.name = name)
  }
  dataset$Tagli_emt = dataset$Tagli_mes - dataset$Tagli_epi
  dataset$bayers_EMT = dataset$bayers_mes - dataset$bayers_epi
  if (idx == 1 ) {
    xeno = dataset
  } 
  if (idx==2) {
    lung = dataset
  }
  idx = idx+1
}

x_names <-emt_pathways <- c("hallmark_emt","GSE17708_72H_UP","bayers_EMT","Tagli_emt","Tagli_hEMT")
x_names[1] = "Hallmark \n EMT"
x_names[2] = "GSE17708\n72H_UP"


```


```{r}
openxlsx::write.xlsx(gene_list, "./Data/EMT_pathways/pathway_genes.xlsx")
  
```

```{r fig.height=5, fig.width=14}
p1 = DotPlot.2(object = xeno, features =  emt_pathways,group.by  = 'treatment',scale = T,scale.by = "size")+
  guides(size = guide_legend(title = "Cells expressing (%)"),color = guide_colorbar(title = "Average Score")) +
  theme(axis.text.x = element_text( size = 10))+ scale_x_discrete(labels= x_names)+ggtitle("Models")+ scale_size_binned()


p2 = DotPlot.2(object = lung, features =  emt_pathways,group.by  = 'time.point',scale = T,scale.by = "size")+
  guides(size = guide_legend(title = "Cells expressing (%)"),color = guide_colorbar(title = "Average Score")) +
  theme(axis.text.x = element_text( size = 10))+ scale_x_discrete(labels= x_names)+ggtitle("Patients")+ scale_size_binned()
p1 + p2
```











```{r}
DotPlot.2(object = xeno, features =  emt_pathways,group.by  = 'orig.ident',split.by = "treatment", scale = T,scale.by = "size",cols = "Blues")+
  guides(size = guide_legend(title = "Cells expressing (%)"),color = guide_colorbar(title = "Average Score")) +
  theme(axis.text.x = element_text( size = 10))+ scale_x_discrete(labels= x_names)+ggtitle("Models")+ scale_size_binned()
```


```{r }

data = FetchData(object = lung,vars = c("time.point",emt_pathways))
df = reshape2::melt(data,value.name = "logTPM") %>% dplyr::rename(gene = variable)


stat.test <- df %>%
    group_by(gene) %>%
  wilcox_test(logTPM ~ time.point,comparisons =  list(c("pre-treatment","on-treatment"))) %>%
  mutate(y.position = 5)

stat.test

stat.test <- stat.test %>% 
  add_xy_position(x = "gene", dodge = 0.8)

ggboxplot(
  df,
  x = "gene",
  y = "logTPM",
  color = "time.point",
  palette = "jco",
  add = "jitter"
)+ stat_pvalue_manual(stat.test,y.position = 4, label = "{p.adj.signif}",remove.bracket =F)+ geom_violin(aes(fill = time.point), trim = FALSE)


```

```{r fig.height=6, fig.width=15}
library(rstatix)
data = FetchData(object = lung,vars = c("time.point",emt_pathways,"patient.ident"))
df = reshape2::melt(data,value.name = "logTPM") %>% dplyr::rename(pathway = variable)

stat.test <- df %>%
    group_by(pathway) %>%
  wilcox_test(logTPM ~ time.point,comparisons =  list(c("pre-treatment","on-treatment"))) %>% 
  add_xy_position(x = "pathway") 


stat.test



p = ggplot(df,aes( x = patient.ident, y = logTPM))+ 
    geom_violin(trim = F,aes(fill = time.point)) +
  geom_boxplot(aes(fill = time.point), width=.2, outlier.shape=NA,
    position = position_dodge(0.9))   +theme_minimal() + stat_pvalue_manual(stat.test,y.position = 3, label = "{p.adj.signif}",remove.bracket = F)

p+facet_wrap(vars(pathway))

```






# calculate score- z score (log tpm)


```{r }
#calculate score
gene_list = list(hallmark_emt = hallmark_emt, GSE17708_72H_UP = GSE17708_72H_UP,bayers_mes = bayers_mes,bayers_epi = bayers_epi,Tagli_hEMT = hEMT,Tagli_epi = epi_genes,Tagli_mes = mes_genes)

idx=1
for (dataset in list(xeno,lung)) {
  # dataset = ScaleData(object = dataset,features = unlist(gene_list))
  for (i in seq_along(gene_list)) {
    genes = gene_list[[i]]
    genes = genes[genes %in% rownames(dataset)]
    name = names(gene_list)[i]
    scores = dataset@assays$RNA@data[genes,] %>% colMeans()
    if (!name  %in% c("Tagli_mes","Tagli_epi","bayers_mes","bayers_epi")) {
      scores = scale(scores)
    }
    dataset %<>% AddMetaData(metadata = scores,col.name = name)
  }
  dataset$Tagli_emt = scale(dataset$Tagli_mes - dataset$Tagli_epi)
  dataset$bayers_EMT = scale(dataset$bayers_mes - dataset$bayers_epi)
  if (idx == 1 ) {
    xeno = dataset
  } 
  if (idx==2) {
    lung = dataset
  }
  idx = idx+1
}

x_names <-emt_pathways <- c("hallmark_emt","GSE17708_72H_UP","bayers_EMT","Tagli_emt","Tagli_hEMT")
# x_names[1] = "Hallmark \n EMT"
# x_names[2] = "GSE17708\n72H_UP"


```

```{r fig.height=5, fig.width=10}
p1 = DotPlot.2(object = xeno, features =  emt_pathways,group.by  = 'treatment',scale = F,scale.by = "size")+
  guides(size = guide_legend(title = "Cells expressing (%)",title.theme =element_text(size = 10)),color = guide_colorbar(title = "Average Score")) +
  theme(axis.text.x = element_text( size = 10,angle = 45,hjust = 1))+ scale_x_discrete(labels= x_names)+ggtitle("Models")


p2 = DotPlot.2(object = lung, features =  emt_pathways,group.by  = 'time.point',scale = F,scale.by = "size")+
  guides(size = guide_legend(title = "Cells expressing (%)",title.theme =element_text(size = 10)),color = guide_colorbar(title = "Average Score")) +
  theme(axis.text.x = element_text( size = 10,angle = 45,hjust = 1))+ scale_x_discrete(labels= x_names)+ggtitle("Patients")
p1 + p2
```

```{r}
p1 + guides(fill = guide_legend(theme = theme(
  legend.title = element_text(size = 15)
)))
```

```{r}
metagenes_mean_compare.2 <- function(dataset,time.point_var,prefix = "",patient.ident_var,pre_on = c("OSI","NT","res"), axis.text.x = 11,test = "t.test", programs = c("Hypoxia","TNFa","Cell_cycle"), with_split = T, without_split = T){
  
  for (metegene in programs) {
    #create data:
    genes_by_tp = FetchData(object = dataset,vars = metegene) %>% rowSums() %>% as.data.frame() #mean expression
    names(genes_by_tp)[1] = "Metagene_mean"
    genes_by_tp = cbind(genes_by_tp,FetchData(object = dataset,vars = c(patient.ident_var,time.point_var))) # add id and time points
    
    
    genes_by_tp_forPlot =  genes_by_tp %>% mutate(!!ensym(patient.ident_var) := paste(prefix,genes_by_tp[,patient.ident_var])) #add "model" before  each model/patient
    fm <- as.formula(paste("Metagene_mean", "~", time.point_var)) #make formula to plot
    
    #plot and split by patient:   
    stat.test = compare_means(formula = fm ,data = genes_by_tp_forPlot,method = test,group.by = patient.ident_var,p.adjust.method = "fdr")%>% # Add pairwise comparisons p-value
      dplyr::filter((group1 == pre_on[1] & group2 == pre_on[2]) | (group1 == pre_on[1] & group2 == pre_on[3])) %>%   #filter for pre vs on treatment only 
mutate(y.position = if_else(condition = group2 == pre_on[2],true = max(genes_by_tp_forPlot$Metagene_mean),false = max(genes_by_tp_forPlot$Metagene_mean)*1.2))      
    

    
    plt = ggboxplot(genes_by_tp_forPlot, x = time.point_var, y = "Metagene_mean", color = time.point_var) + #plot
      stat_pvalue_manual(stat.test, label = "p = {signif(p, digits=3)}")+
      grids()+  
      ylab(paste(metegene,"mean"))+
      theme(axis.text.x = element_text(size = axis.text.x))+
      ylim(0, max(genes_by_tp_forPlot$Metagene_mean)*1.3)+ # extend y axis to show p value
    scale_x_discrete(labels= c("pre","on","res"))
    plt = facet(plt, facet.by = patient.ident_var) #split by patients
    print_tab(plt = plt,title = c(metegene,"per patient")) 
    
    
  }
  
  
}

```



# calculate score- log tpm scale per patient


```{r }
#calculate score
gene_list = list(hallmark_emt = hallmark_emt, GSE17708_72H_UP = GSE17708_72H_UP,bayers_mes = bayers_mes,bayers_epi = bayers_epi,Tagli_hEMT = hEMT,Tagli_epi = epi_genes,Tagli_mes = mes_genes)

idx=1
for (dataset in list(xeno,lung)) {
  if (idx == 1 ) {
    patient_var = "orig.ident"
  } 
  if (idx==2) {
    patient_var = "patient.ident"
  }  
  dataset = ScaleData(object = dataset,features = unlist(gene_list))
  for (i in seq_along(gene_list)) {
    genes = gene_list[[i]]
    genes = genes[genes %in% rownames(dataset)]
    name = names(gene_list)[i]
    scores = FetchData(object = dataset,vars = c(genes,patient_var))
    scores = scores %>% mutate(r = rowMeans(dplyr::select_at(scores,vars(-contains(patient_var))))) %>% 
      group_by_at(patient_var) %>% summarise(r = scale(r)) %>% pull(r) %>% as.data.frame()
    dataset %<>% AddMetaData(metadata = scores,col.name = name)

  }
  dataset$Tagli_emt = (dataset$Tagli_mes - dataset$Tagli_epi)
  dataset$bayers_EMT = (dataset$bayers_mes - dataset$bayers_epi)
  if (idx == 1 ) {
    xeno = dataset
  } 
  if (idx==2) {
    lung = dataset
  }
  idx = idx+1
}

x_names <-emt_pathways <- c("hallmark_emt","GSE17708_72H_UP","bayers_EMT","Tagli_emt","Tagli_hEMT")
x_names[1] = "Hallmark \n EMT"
x_names[2] = "GSE17708\n72H_UP"


```





```{r fig.height=5, fig.width=11}

p1 = DotPlot.2(object = lung, features =  emt_pathways[1:2],group.by  = 'patient.ident',split.by = "time.point", scale = F,scale.by = "size",cols = "Blues")+
  guides(size = guide_legend(title = "Cells expressing (%)",title.theme =element_text(size = 10)),color = guide_colorbar(title = "Average Score")) +
  theme(axis.text.x = element_text( size = 10))+ scale_x_discrete(labels= x_names)+ggtitle("Patients")+ scale_size_binned()
  
p2 = DotPlot.2(object = xeno, features =  emt_pathways[1:2],group.by  = 'orig.ident',split.by = "treatment", scale = F,scale.by = "size",cols = "Blues")+
  guides(size = guide_legend(title = "Cells expressing (%)",title.theme =element_text(size = 10)),color = guide_colorbar(title = "Average Score")) +
  theme(axis.text.x = element_text( size = 10))+ scale_x_discrete(labels= x_names)+ggtitle("Models")+ scale_size_binned()

p1 +  geom_tile(aes(
  y =p1$data$id,
  x = length(unique(p1$data$features.plot)) + 1,
  fill = p1$data$id %>% gsub(pattern = ".*_", replacement = ""),width=0.2
))+ guides(fill=guide_legend(title="treatment"))+ # creates a bar on the rights side of your data, coloured by your x-variable
  p2 +  geom_tile(aes(
    y =p2$data$id,
    x = length(unique(p2$data$features.plot)) + 1,
  fill = p2$data$id %>% gsub(pattern = ".*_", replacement = ""),width=0.2
  ))+ guides(fill=guide_legend(title="treatment")) # creates a bar on the rights side of your data, coloured by your x-variable

```




# calculate score- log tpm


```{r }
#calculate score
gene_list = list(hallmark_emt = hallmark_emt, GSE17708_72H_UP = GSE17708_72H_UP,bayers_mes = bayers_mes,bayers_epi = bayers_epi,Tagli_hEMT = hEMT,Tagli_epi = epi_genes,Tagli_mes = mes_genes)

idx=1
for (dataset in list(xeno,lung)) {
  # dataset = ScaleData(object = dataset,features = unlist(gene_list))
  for (i in seq_along(gene_list)) {
    genes = gene_list[[i]]
    genes = genes[genes %in% rownames(dataset)]
    name = names(gene_list)[i]
    scores = dataset@assays$RNA@data[genes,] %>% colMeans()
    dataset %<>% AddMetaData(metadata = scores,col.name = name)
  }
  dataset$Tagli_emt = dataset$Tagli_mes - dataset$Tagli_epi
  dataset$bayers_EMT = dataset$bayers_mes - dataset$bayers_epi
  if (idx == 1 ) {
    xeno = dataset
  } 
  if (idx==2) {
    lung = dataset
  }
  idx = idx+1
}

x_names <-emt_pathways <- c("hallmark_emt","GSE17708_72H_UP","bayers_EMT","Tagli_emt","Tagli_hEMT")
x_names[1] = "Hallmark \n EMT"
x_names[2] = "GSE17708\n72H_UP"


```



```{r}
metagenes_mean_compare.2(dataset = lung,time.point_var = "time.point",prefix = "patient",patient.ident_var = "patient.ident",pre_on = c("pre-treatment","on-treatment","resistant"),test = "wilcox.test",programs = emt_pathways[1:2],without_split = T)

metagenes_mean_compare.2(dataset = xeno,time.point_var = "treatment",prefix = "model",patient.ident_var = "orig.ident",pre_on = c("NT","OSI","res"),test = "wilcox.test",programs = emt_pathways[1:2],without_split = T)


```



```{r}
FetchData(object = lung,vars = c("time.point","patient.ident","hallmark_emt")) %>% filter(patient.ident == "MGH1066" & time.point == "pre-treatment") %>% pull ("hallmark_emt") %>% mean()

FetchData(object = lung,vars = c("time.point","patient.ident","hallmark_emt")) %>% filter(patient.ident == "MGH1066" & time.point == "on-treatment") %>% pull ("hallmark_emt") %>% mean()
```

```{r fig.height=5, fig.width=14}
p1 = DotPlot.2(object = xeno, features =  emt_pathways,group.by  = 'treatment',scale = T,scale.by = "size")+
  guides(size = guide_legend(title = "Cells expressing (%)"),color = guide_colorbar(title = "Average Score")) +
  theme(axis.text.x = element_text( size = 10))+ scale_x_discrete(labels= x_names)+ggtitle("Models")+ scale_size_binned()


p2 = DotPlot.2(object = lung, features =  emt_pathways,group.by  = 'time.point',scale = T,scale.by = "size")+
  guides(size = guide_legend(title = "Cells expressing (%)"),color = guide_colorbar(title = "Average Score")) +
  theme(axis.text.x = element_text( size = 10))+ scale_x_discrete(labels= x_names)+ggtitle("Patients")+ scale_size_binned()
p1 + p2
```

```{r}
all_pathways = list()
for (pathway in emt_pathways) {
  data = FetchData(object = lung,vars = c(pathway, "time.point", "patient.ident"))
  all_patients = list()
  for (patient in unique(lung$patient.ident)) {
    mean1 = data %>% filter(patient.ident == patient, time.point == "pre-treatment") %>% pull(1) %>% mean()
    mean2 = data %>% filter(patient.ident == patient, time.point == "on-treatment") %>% pull(1) %>% mean()
    fc = mean1 / mean2
    all_patients[[patient]] = fc
  }
  all_pathways[[pathway]] = all_patients
}


mat = as.data.frame(lapply(all_pathways, unlist))
mat = log2(t(mat) %>% as.data.frame())
breaks <- c(seq(-1,1,by=0.1))
colors_for_plot <- colorRampPalette(colors = c("royalblue1", "white", "red"))(n = length(breaks))

pheatmap::pheatmap(mat,color = colors_for_plot,breaks = breaks,display_numbers = T,main = "log2(FC) pre/on")
```


```{r}
data = FetchData(object = lung,vars = bayers_EMT) 
data = cor(data)

print(ComplexHeatmap::Heatmap(data,show_column_names = F,show_row_names = T,cluster_rows = T,name = "correlation",use_raster = T,cluster_columns = T, row_names_gp = grid::gpar(fontsize = 5)))
```


<script src="https://hypothes.is/embed.js" async></script>

