---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
---



# Figure 1


```{r}
xeno_umap_patients = readRDS("./Figures/xeno_patient_umap.rds")
xeno_umap_treatment = readRDS("./Figures/xeno_treatment_umap.rds")
xeno_deg = readRDS("./Figures/xeno_DEG.rds")
xeno_sipsic_heatmap = readRDS("./Figures/xeno_sipsic_heatmap.rds")

```


```{r fig.height=15, fig.width=15}
p1 = cowplot::plot_grid(xeno_umap_treatment,xeno_umap_patients,xeno_deg,ncol = 1,nrow = 3,labels = c("B","C","E"))
p2 = cowplot::plot_grid(NULL,xeno_sipsic_heatmap,ncol = 1,nrow = 2,labels = c("A","D"))
p3 = cowplot::plot_grid(p2,p1,nrow = 1,ncol = 2)
p3
```


```{r}
pdf("./final_figures/fig1.pdf",width = 15,height = 15)
p3
dev.off()
```

# Figure 2


```{r}
xeno_nmf_heatmap = readRDS("./Figures/xeno_NMF_programs_heatmap.rds")
xeno_nmf_usage_UMAP = readRDS("./Figures/xeno_NMF_usage_UMAP.rds")

```


```{r fig.height=17, fig.width=12}
p = cowplot::plot_grid(xeno_nmf_usage_UMAP,xeno_nmf_heatmap,ncol = 1,labels = "AUTO")
p
```
```{r}
pdf("./final_figures/fig2.pdf",width = 12,height = 17)
p
dev.off()
```
# Figure 3

```{r}
xeno_nmf_GSEA = readRDS("./Figures/xeno_nmf_GSEA.rds")
xeno_NMF_programs_dotplot = readRDS("./Figures/xeno_NMF_programs_dotplot.rds")
xeno_NMF_hypoxia_split_violin = readRDS("./Figures/xeno_NMF_hypoxia_split_violin.rds")
```

```{r fig.height=12, fig.width=21}
p1 = cowplot::plot_grid(xeno_NMF_programs_dotplot,xeno_NMF_hypoxia_split_violin, ncol = 1,labels = c("B","C"))
p = cowplot::plot_grid(xeno_nmf_GSEA,p1, ncol = 2,labels = c("A",NULL,NULL), rel_widths = c(1.5, 1))
p
```

```{r}
pdf("./final_figures/fig3.pdf",width = 22,height = 12)
p
dev.off()
```

# Figure 4

```{r}
patients_nmf_usage_umap = readRDS("./Figures/patients_nmf_usage_umap.rds")
bivona_nmf_usage_umap =  readRDS("./Figures/bivona_nmf_usage_umap.rds")

bivona_nmf_dotplot = readRDS("./Figures/bivona_nmf_dotplot.rds")
bivona_nmf_violin = readRDS("./Figures/bivona_nmf_violin.rds")

patients_nmf_usage_dotplot =  readRDS("./Figures/patients_nmf_usage_dotplot.rds")
patients_nmf_hypoxia_violin = readRDS("./Figures/patients_nmf_hypoxia_violin.rds")
```

```{r fig.height=17, fig.width=17}
p1 = cowplot::plot_grid(bivona_nmf_usage_umap,patients_nmf_usage_umap, bivona_nmf_dotplot,patients_nmf_usage_dotplot,bivona_nmf_violin,patients_nmf_hypoxia_violin,nrow = 3, ncol = 2,labels = "AUTO",rel_heights = c(1.5,1,1))

p1
```

```{r}
pdf("./final_figures/fig4.pdf",width = 19,height = 17)
p1
dev.off()
```

# Fig 4 sup
```{r}

bivona_known_genes_violin = readRDS("./Figures/bivona_hif_targets_violin.rds")
bivona_known_genes_dotplot = readRDS("./Figures/bivona_known_genes_dotplot.rds")

patients_hif_targets_violin = readRDS("./Figures/patients_hif_targets_violin.rds")
patients_signtures_dotplot =  readRDS("./Figures/patients_signtures_dotplot.rds")

xeno_signtures_dotplot = readRDS("./Figures/xeno_signtures_dotplot.rds")
xeno_hif_targets_violin = readRDS("./Figures/xeno_hif_targets_violin.rds")
```


```{r fig.height=8, fig.width=24}
p1 = cowplot::plot_grid(xeno_signtures_dotplot,patients_signtures_dotplot,bivona_known_genes_dotplot,xeno_hif_targets_violin,patients_hif_targets_violin,bivona_known_genes_violin,labels = "AUTO")

p1
```


```{r}
pdf("./final_figures/fig4_sup.pdf",width = 24,height = 8)
p1
dev.off()
```