---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
---

<style type="text/css">
.main-container {
  max-width: 85% !important;
  margin: auto;
}
</style>


# Functions

```{r}
library(stringi)
library(reticulate)
source_from_github(repositoy = "DEG_functions",version = "0.2.47")
source_from_github(repositoy = "cNMF_functions",version = "0.4.04",script_name = "cnmf_functions_V3.R")
source_from_github(repositoy = "sc_general_functions",version = "0.1.34",script_name = "functions.R")


sipsic_per_patient <- function(x, dataset_splited, patients_names,to_TPM) {
  i <<- i + 1
  message(paste("pathway "), i)
  all_patients = c()
  
  for (patient in patients_names) {
    patient_data = dataset_splited[[patient]]
    if (to_TPM) {
      res = getPathwayScores((2 ^ patient_data@assays$RNA@data) - 1, unlist(x))[["pathwayScores"]]
    } else{
      res = getPathwayScores(patient_data@assays$RNA@data, unlist(x))[["pathwayScores"]]
    }
    all_patients = c(all_patients, res)
  }
  scoresAndIndices = append(scoresAndIndices, all_patients)
  
}

```

# Data

```{r}
lung = readRDS("./Data/lung_cancercells_withTP_onlyPatients.rds")
lung_patients = lung$patient.ident %>% unique() %>% as.character()
lung_patients_filtered = lung_patients[!(lung_patients %in% c("X1055new","X1099"))] # remove patients with less than 100 malignant cells
lung = subset(x = lung,subset = patient.ident %in% lung_patients_filtered)


genesets <- msigdb_download("Homo sapiens",category="H") 
hif_targets = c("LDHA", "PPFIA4", "PFKFB4", "AK4", "ERO1A", "BNIP3L", "BNIP3",  #https://pubmed.ncbi.nlm.nih.gov/36384128/
"PFKL", "ENO1", "MIR210HG", "TPI1", "HILPDA", "PGK1", "INSIG2", 
"AK4P1", "AC114803.1", "ENO2", "FUT11", "EGLN3", "NDRG1", "BNIP3P1", 
"WDR54", "OVOL1-AS1", "STC2", "DDX41", "C4orf47", "GYS1", "ANKRD37", 
"BICDL2", "P4HA1", "PDK1", "OSMR", "PKM", "LDHAP5", "AL158201.1", 
"PFKP", "MIR210", "NLRP3P1", "GSX1", "AL109946.1", "PGAM1", "SLC16A3", 
"ISM2", "TCAF2", "ARID3A", "KDM3A", "JMJD6", "C4orf3")
genesets[["HIF_targets"]] = hif_targets
```

# Patients log2(TPM)

```{r}
lung_splited = list()
for (patient in unique(lung$patient.ident)) {
  patient_data = subset(lung, subset = patient.ident == patient)
  lung_splited[[patient]] = patient_data
}


```

```{r}
scoresAndIndices = list()
i = 0
scoresAndIndices = lapply(genesets,dataset_splited=lung_splited, FUN = sipsic_per_patient,patients_names = unique(lung$patient.ident),to_TPM=F) 
scoresAndIndices_patients_logtpm = scoresAndIndices

```

```{r}
for (pathway_name in names(scoresAndIndices_patients_logtpm)) {
  metadata = scoresAndIndices[[pathway_name]] %>% as.data.frame() %>%  t() %>% as.data.frame(row.names = names(scoresAndIndices[[pathway_name]])) 
  lung %<>% AddMetaData(metadata = metadata,col.name = pathway_name)

}
```


```{r}
```



```{r}
signf_plot_pre_vs_on<- function(dataset,programs,patient.ident_var,prefix,pre_on,test,time.point_var) {
    final_df = data.frame()
    for (metegene in programs) {
      genes_by_tp = FetchData(object = dataset,vars = metegene) %>% rowSums() %>% as.data.frame() #mean expression
      names(genes_by_tp)[1] = metegene
      genes_by_tp = cbind(genes_by_tp,FetchData(object = dataset,vars = c(patient.ident_var,time.point_var))) # add id and time points
      
      
      # genes_by_tp_forPlot =  genes_by_tp %>% mutate(!!ensym(patient.ident_var) := paste(prefix,genes_by_tp[,patient.ident_var])) #add "model" before  each model/patient
      fm <- as.formula(paste(metegene, "~", time.point_var)) #make formula to plot
      
      #plot and split by patient:   
      stat.test = compare_means(formula = fm ,data = genes_by_tp,method = test,group.by = patient.ident_var,p.adjust.method = "fdr")%>% 
              dplyr::filter(group1 == pre_on[1] & group2 == pre_on[2])  #filter for pre vs on treatment only
      final_df = rbind(final_df,stat.test)
    }
    return(final_df)
}

final_df = signf_plot_pre_vs_on(dataset = lung,time.point_var = "time.point",prefix = "patient",patient.ident_var = "patient.ident",pre_on = c("pre-treatment","on-treatment"),test = "wilcox.test",programs = names(scoresAndIndices) )
final_df = reshape2::dcast(final_df, patient.ident  ~.y.,value.var = "p.adj") %>% column_to_rownames("patient.ident")

```

```{r fig.height=10, fig.width=8}
sig_heatmap(all_patients_result = t(final_df) %>% as.data.frame(),title = "ad")

```


```{r}
all_pathways = list()
for (hallmark in names(scoresAndIndices_patients_logtpm)) {
  data = FetchData(object = lung,vars = c(hallmark, "time.point", "patient.ident"))
  all_patients = list()
  for (patient in unique(lung$patient.ident)) {
    mean1 = data %>% filter(patient.ident == patient, time.point == "pre-treatment") %>% pull(1) %>% mean()
    mean2 = data %>% filter(patient.ident == patient, time.point == "on-treatment") %>% pull(1) %>% mean()
    fc = mean1 / mean2
    all_patients[[patient]] = fc
  }
  all_pathways[[hallmark]] = all_patients
}

```

```{r fig.height=9}
a = as.data.frame(lapply(all_pathways, unlist))
a = log2(t(a) %>% as.data.frame())
breaks <- c(seq(-1,1,by=0.1))
colors_for_plot <- colorRampPalette(colors = c("blue", "white", "red"))(n = length(breaks))

pheatmap(a,color = colors_for_plot,breaks = breaks,display_numbers = T,main = "log2(FC) pre/on")

```


```{r}
res= getPathwayScores((2^xeno_splited$PC9@assays$RNA@data)-1, unlist(genesets$HALLMARK_HYPOXIA))[["pathwayScores"]]
names(res) = colnames(xeno_splited$PC9)
xeno_splited$PC9  %<>% AddMetaData(metadata = res,col.name = "HALLMARK_HYPOXIA")
data = FetchData(object = xeno_splited$PC9,vars = c("HALLMARK_HYPOXIA", "treatment", "orig.ident"))
mean1 = data %>% filter( treatment == "NT") %>% pull(1) %>% mean()
mean2 = data %>% filter( treatment == "OSI") %>% pull(1) %>% mean()
fc = mean1 / mean2
log2(fc)
```

```{r}
metagenes_mean_compare(dataset = lung,time.point_var = "time.point",prefix = "patient",patient.ident_var = "patient.ident",pre_on = c("pre-treatment","on-treatment"),test = "wilcox.test",programs = "HALLMARK_HYPOXIA",without_split = F)
```

# Patients TPM
```{r}

scoresAndIndices = list()
i = 0
scoresAndIndices = lapply(genesets,dataset_splited=lung_splited, FUN = sipsic_per_patient,patients_names = unique(lung$patient.ident),to_TPM=T) 
scoresAndIndices_patients_tpm = scoresAndIndices


```

```{r}
for (pathway_name in names(scoresAndIndices_patients_tpm)) {
  lung %<>% AddMetaData(metadata = unlist(scoresAndIndices_patients_tpm[[pathway_name]]),col.name = pathway_name)

}
```

```{r}
all_pathways = list()
for (hallmark in names(scoresAndIndices_patients_tpm)) {
  data = FetchData(object = lung,vars = c(hallmark, "time.point", "patient.ident"))
  all_patients = list()
  for (patient in unique(lung$patient.ident)) {
    mean1 = data %>% filter(patient.ident == patient, time.point == "pre-treatment") %>% pull(1) %>% mean()
    mean2 = data %>% filter(patient.ident == patient, time.point == "on-treatment") %>% pull(1) %>% mean()
    fc = mean1 / mean2
    all_patients[[patient]] = fc
  }
  all_pathways[[hallmark]] = all_patients
}

```

```{r fig.height=9}
a = as.data.frame(lapply(all_pathways, unlist))
a = log2(t(a) %>% as.data.frame())
breaks <- c(seq(-1,1,by=0.1))
colors_for_plot <- colorRampPalette(colors = c("blue", "white", "red"))(n = length(breaks))

pheatmap(a,color = colors_for_plot,breaks = breaks,display_numbers = T,main = "log2(FC) pre/on")

```

```{r}

final_df = signf_plot_pre_vs_on(dataset = lung,time.point_var = "time.point",prefix = "",patient.ident_var = "patient.ident",pre_on = c("pre-treatment","on-treatment"),test = "wilcox.test",programs = names(scoresAndIndices) )
final_df = reshape2::dcast(final_df, patient.ident  ~.y.,value.var = "p.adj") %>% column_to_rownames("patient.ident")
a_sign = sign(a)
```

```{r fig.height=10, fig.width=8}
breaks <- c(seq(-15,15,by=0.1))
colors_for_plot <- colorRampPalette(colors = c("blue", "white", "red"))(n = length(breaks))
sig_heatmap(all_patients_result  = t(final_df) %>% as.data.frame(),title = "Blue: log10(pval) up pathways during treatment in patients\n Red:-log10(pval) down pathways during treatment in patients",sign_matrix = a_sign,breaks = breaks, color = colors_for_plot)
```


# Xeno TPM
```{r}
xeno_splited = list()
for (patient in unique(xeno$orig.ident)) {
  patient_data = subset(xeno, subset = orig.ident == patient)
  patient_data = DietSeurat(object = patient_data)
  xeno_splited[[patient]] = patient_data
}

```

```{r}
scoresAndIndices = list()
i = 0
scoresAndIndices = lapply(genesets,dataset_splited=xeno_splited, FUN = sipsic_per_patient,patients_names = unique(xeno$orig.ident),to_TPM=T) 
scoresAndIndices_xeno_TPM = scoresAndIndices
this="5.12 16:56"
gc()
save.image()

```

```{r}
for (pathway_name in names(scoresAndIndices_xeno_TPM)) {
  metadata = scoresAndIndices_xeno_TPM[[pathway_name]] %>% as.data.frame() %>%  t() %>% as.data.frame(row.names = names(scoresAndIndices_xeno_TPM[[pathway_name]])) 
  xeno %<>% AddMetaData(metadata = metadata,col.name = pathway_name)

}
```



# Xeno log2(TPM)
```{r}

scoresAndIndices = list()
i=0
fun <- function(x,dataset) {
    i<<-i+1
    message(paste("pathway "),i)
    all_patients = c()
    for (patient in unique(dataset$orig.ident)) {
        patient_data = subset(dataset,subset = orig.ident == patient)
        res = getPathwayScores((2^patient_data@assays$RNA@data)-1, unlist(x))[["pathwayScores"]]
        all_patients = c(all_patients,res)
    }
    scoresAndIndices = append(scoresAndIndices,all_patients)


}


scoresAndIndices = lapply(genesets[1:2],dataset=xeno, FUN = fun) 


```


```{r}
for (pathway_name in names(scoresAndIndices)) {
  xeno %<>% AddMetaData(metadata = unlist(scoresAndIndices[[pathway_name]]),col.name = pathway_name)
}
```



```{r}
all_pathways = list()
for (hallmark in names(scoresAndIndices_xeno_TPM)) {
  data = FetchData(object = xeno,vars = c(hallmark, "treatment", "orig.ident"))
  all_patients = list()
  for (patient in unique(xeno$orig.ident)) {
    mean1 = data %>% filter(orig.ident == patient, treatment == "NT") %>% pull(1) %>% mean()
    mean2 = data %>% filter(orig.ident == patient, treatment == "OSI") %>% pull(1) %>% mean()
    fc = mean1 / mean2
    all_patients[[patient]] = fc
  }
  all_pathways[[hallmark]] = all_patients
}

```

```{r fig.height=9}
a = as.data.frame(lapply(all_pathways, unlist))
a = log2(t(a) %>% as.data.frame())
breaks <- c(seq(-1,1,by=0.1))
colors_for_plot <- colorRampPalette(colors = c("blue", "white", "red"))(n = length(breaks))

pheatmap(a,color = colors_for_plot,breaks = breaks,display_numbers = T)

```
```{r}

final_df = signf_plot_pre_vs_on(dataset = xeno,time.point_var = "treatment",prefix = "",patient.ident_var = "orig.ident",pre_on = c("NT","OSI"),test = "wilcox.test",programs = names(scoresAndIndices) )
final_df = reshape2::dcast(final_df, orig.ident  ~.y.,value.var = "p.adj") %>% column_to_rownames("orig.ident")
a_sign = sign(a)
final_df[final_df == 0 ] = 1e-300
```

```{r fig.height=10, fig.width=8}
breaks <- c(seq(-300,-2,by=1))
colors_for_plot1 <- colorRampPalette(colors = c("blue","aliceblue"))(n = length(breaks))
breaks <- c(seq(2,300,by=1))
colors_for_plot2 <- colorRampPalette(colors = c("seashell","red"))(n = length(breaks))
breaks <- c(seq(-1,1,by=1))
colors_for_plot3 <- colorRampPalette(colors = c("white"))(n = length(breaks))

breaks <- c(seq(-300,300,by=1))
undebug(sig_heatmap)
colors_for_plot = c(colors_for_plot1,colors_for_plot3,colors_for_plot2)
sig_heatmap(all_patients_result  = t(final_df) %>% as.data.frame(),title = "Blue: log10(pval) up pathways during treatment in Xeno\n Red:-log10(pval) down pathways during treatment in Xeno",sign_matrix = a_sign,breaks = breaks, color = colors_for_plot)
```
# DE pathways

```{r}
calculatePathwayScores <- function(pathwayToScore, countsMatrix)
{
  pathwayName <- pathwayToScore@setName
  print(pathwayName)
  pathwayGenes <- pathwayToScore@geneIds
  pathwayScoresObject <- getPathwayScores(countsMatrix, pathwayGenes) 
  suppressWarnings(
    if(is.na(pathwayScoresObject)){return (NA)}
  )
  return(pathwayScoresObject$pathwayScores)
}
```

```{r}
genesets <- getGmt("./Data/msigdb_pathways/h.all.v7.0.symbols.pluscc.gmt")
genesets_cp <- getGmt("./Data/msigdb_pathways/c2.cp.v2023.2.Hs.symbols.gmt")
genesets_h_cp = GeneSetCollection(c(genesets,genesets_cp))
```

```{r}
# xeno = readRDS("./Data/10x_xeno_1000.Rds")

pathwayScoreLists <- lapply(X = genesets_h_cp@.Data, calculatePathwayScores, xeno@assays$RNA@data%>% expm1())
pathwayScoreLists <- pathwayScoreLists[!is.na(pathwayScoreLists)] #remove NA pathways
pathwayScoresMatrix <- as.data.frame(do.call("rbind", pathwayScoreLists))
```


<script src="https://hypothes.is/embed.js" async></script>

