---
title: "All cell TPM heatmap"
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
editor_options: 
  chunk_output_type: inline
params:
  data_out_dir: "./temp_data/" 
---


```{r}
source("./pipe.R")
input = pipeline$Bulk_TPM_heatmap$input
output = pipeline$Bulk_TPM_heatmap$output
```

```{r}
library(dplyr)
library(tibble)
library(ComplexHeatmap)
library(circlize)
library(writexl)
suppressPackageStartupMessages(library(GSEABase))
```

```{r}
bulk_Mar25_TPM_list = readRDS(input$bulk_Mar25_TPM_list)
metadata_list = readRDS(input$metadata_list)
```

```{r}
all_msigdb = readRDS(input$msigdb) %>% geneIds() 
```

```{r}
genesets_annot= data.frame()

# Add Hallmarkd
genesets = getGmt(input$msigDB_hallmarks) %>% geneIds() 
genesets_annot = rbind(genesets_annot,
                        data.frame(
                          pathway = names(genesets),
                          name = "Hallmarks"
                        ))
# rename ROS  annotation pathway
genesets_annot[genesets_annot$pathway == "HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY","name"] = "ROS"

#senescence  pathways
pathways_to_check = c("FRIDMAN_SENESCENCE_UP","REACTOME_OXIDATIVE_STRESS_INDUCED_SENESCENCE","GOBP_ONCOGENE_INDUCED_CELL_SENESCENCE", "GOBP_POSITIVE_REGULATION_OF_CELLULAR_SENESCENCE", "KAMMINGA_SENESCENCE", "WP_KYNURENINE_PATHWAY_AND_LINKS_TO_CELL_SENESCENCE")
senescence_pathways = all_msigdb[pathways_to_check]
genesets = c(genesets, senescence_pathways)
genesets_annot = rbind(genesets_annot,
                        data.frame(
                          pathway = names(senescence_pathways),
                          name = "Senescence"
                        ))

# ROS pathways
pathways_to_check = c("GOBP_PROGRAMMED_CELL_DEATH_IN_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES" ,"GOBP_POSITIVE_REGULATION_OF_REACTIVE_OXYGEN_SPECIES_METABOLIC_PROCESS", 
                      "GOBP_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES")
ros_pathways = all_msigdb[pathways_to_check]
genesets = c(genesets, ros_pathways)
genesets_annot = rbind(genesets_annot,
                        data.frame(
                          pathway = names(ros_pathways),
                          name = "ROS"
                        ))


hif_targets =  scan(input$hif_targets, character(), quote = "")
genesets[["HIF_targets"]] = hif_targets

genesets_annot = rbind(genesets_annot,
                        data.frame(
                          pathway = "HIF_targets",
                          name = "Hallmarks"
                        ))



sasp =  scan(input$SASP_genes, character(), quote = "")
genesets[["SASP"]] = sasp

genesets_annot = rbind(genesets_annot,
                        data.frame(
                          pathway = c("SASP"),
                          name = "Senescence"
                        ))

sabrina_senescence = readxl::read_xlsx("input_data/Pathways/pathways_from_papers/Sabrina_PMC12780064_sup_data_3.xlsx", sheet = "EIS gene list",skip = 0) %>% pull(2)

sabrina_sasp = readxl::read_xlsx("input_data/Pathways/pathways_from_papers/Sabrina_PMC12780064_sup_data_3.xlsx", sheet = "Shared SASP genes",skip = 0) %>% pull(2)
```


```{r}
genesets[["Sabrina_Senescence"]] = sabrina_senescence
genesets[["Sabrina_SASP"]] = sabrina_sasp
```



```{r}
all_cell_lines_TPM = list()

for (cell_line in names(bulk_Mar25_TPM_list)) {
  cell_line_data = bulk_Mar25_TPM_list[[cell_line]]
  metadata = metadata_list[[cell_line]]
  all_genesets_tpm = list()

  for (pathway in names(genesets)) {
    pathway_genes = genesets[[pathway]]
    pathway_genes = pathway_genes[pathway_genes %in% rownames(cell_line_data)]
    scores_df = cell_line_data[pathway_genes,] %>% colMeans() %>% data.frame(row.names = names(.), score =.)
    scores_df = merge(x = scores_df,y = metadata,by = 0) %>% column_to_rownames("Row.names")
    scores_df$condition = factor(scores_df$condition,levels = 
                                   c("Veh","Rox","osi_short","osi_short_roxa","osi_persistor","osi_persist_roxa"))
    summary_df <- scores_df %>%
    group_by(condition) %>%
    dplyr::summarise(
      Mean_Score = mean(score),
      SD_Score = sd(score),
      N = n(),
      SE_Score = SD_Score / sqrt(N)
    )
    means = summary_df$Mean_Score  %>% scale() %>% as.vector() %>% setNames(summary_df$condition)
    all_genesets_tpm[[pathway]] = means
  }
  
  all_genesets_tpm_df = all_genesets_tpm %>% as.data.frame() %>% t() %>% as.data.frame()
  all_cell_lines_TPM[[cell_line]] = all_genesets_tpm_df
}


```

```{r fig.height=11, fig.width=10}

summary_df = do.call(cbind,all_cell_lines_TPM)

ordered_pathways = genesets_annot %>% filter(pathway %in% rownames(summary_df)) %>%
  mutate(pathway = factor(pathway,levels = rownames(summary_df))) %>% arrange(pathway) %>% pull(name)


ht <- Heatmap(summary_df, show_heatmap_legend = FALSE,
              column_split = str_extract(colnames(summary_df),"H1975|HCC"),   
              column_title_gp = gpar(fill = c("green", "orange")),
              column_order  = colnames(summary_df),row_split = ordered_pathways)
col_fun = colorRamp2(c(min(summary_df), max(summary_df)), c("blue", "red"))

lgd <- Legend(
  title = "Mean scaled score",col_fun = col_fun)

draw(ht, padding = unit(c(2, 2, 2, 75), "mm"))
pushViewport(viewport(x=0.8, y=0.7, width=unit(4, "cm"), height=unit(6, "cm"), just=c("left","center")))
draw(lgd,x = unit(2, "cm"), y = unit(9, "cm"))
popViewport()
```



```{r fig.height=8, fig.width=7}


plot_genes_heatmap <- function(pathway_genes, return_df = F, plot = T, pathway = "", scale= T,filter = T) {
  pathway_genes = pathway_genes[pathway_genes %in% rownames(bulk_Mar25_TPM_list[[1]]) & pathway_genes %in% rownames(bulk_Mar25_TPM_list[[2]])]
  if (filter) {
    # expressed in at least one sample
    pathway_genes = pathway_genes[rowSums(bulk_Mar25_TPM_list[[1]][pathway_genes, ]) >
                                    0 & rowSums(bulk_Mar25_TPM_list[[2]][pathway_genes, ]) > 0]
  }

  summary_df_list = list()
  
  for (cell_line in names(bulk_Mar25_TPM_list)) {
    cell_line_data = bulk_Mar25_TPM_list[[cell_line]]
    metadata = metadata_list[[cell_line]]
    scores_df = cell_line_data[pathway_genes,] %>% t() %>% as.data.frame() %>% merge(y = metadata,by = 0) %>% column_to_rownames("Row.names")
    
    
    summary_df <- scores_df %>%
    group_by(condition) %>%
    dplyr::summarise(
      across(all_of(pathway_genes), mean, .names = "{.col}")
    ) %>% column_to_rownames("condition")
    if (scale){
      summary_df = summary_df  %>% scale()
    }

    summary_df = summary_df  %>%  t() %>% as.data.frame()%>% na.omit()
    summary_df_list[[cell_line]] = summary_df
  }
  
  #cbind dfs in list
  summary_df = do.call(cbind,summary_df_list)
  
  
  ht <- Heatmap(summary_df, show_heatmap_legend = FALSE, column_title= pathway,
                column_order  = colnames(summary_df),
                column_split = str_extract(colnames(summary_df),"H1975|HCC"))
  col_fun = colorRamp2(c(min(summary_df),0, max(summary_df)), c("blue","white", "red"))
  
  lgd <- Legend(
    title = "TPM mean \nZ score",col_fun = col_fun)
  if (plot){
    draw(ht, padding = unit(c(2, 2, 2, 75), "mm"))
    pushViewport(viewport(x=0.8, y=0.7, width=unit(4, "cm"), height=unit(6, "cm"), just=c("left","center")))
    draw(lgd,x = unit(0.2, "cm"), y = unit(1, "cm"))
    popViewport()
  }
  
  
  if (return_df) {
    row_order_indices = row_order(ht) %>% unlist() %>% unname()
    clustered_mat = summary_df[row_order_indices, ]
    return(clustered_mat)
  }
}

  
```


```{r fig.height=6, fig.width=7}

clustered_mat = plot_genes_heatmap(genesets[["SASP"]],return_df = T,plot = T,pathway = "SASP")
write_xlsx(rownames_to_column(clustered_mat,var = "Gene"), path = paste0(params$data_out_dir,"SASP_genes_TPM_heatmap.xlsx"))

clustered_mat = plot_genes_heatmap(genesets[["HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY"]],return_df = T,plot = T)
write_xlsx(rownames_to_column(clustered_mat,var = "Gene"), path = paste0(params$data_out_dir,"ROS_genes_TPM_heatmap.xlsx"))

clustered_mat = plot_genes_heatmap(genesets[["HIF_targets"]],return_df = T,plot = T)
write_xlsx(rownames_to_column(clustered_mat,var = "Gene"), path = paste0(params$data_out_dir,"HIF_genes_TPM_heatmap.xlsx"))


```
# Scatter plot

```{r}

x_signature = "Sabrina_SASP"
y_signature = "HIF_targets"

all_cell_lines_TPM = list()

for (cell_line in names(bulk_Mar25_TPM_list)) {
  cell_line_data = bulk_Mar25_TPM_list[[cell_line]]
  metadata = metadata_list[[cell_line]]
  all_genesets_tpm = list()

  for (pathway in c(x_signature,y_signature)) {
    pathway_genes = genesets[[pathway]]
    pathway_genes = pathway_genes[pathway_genes %in% rownames(cell_line_data)]
    scores_df = cell_line_data[pathway_genes,] %>% colMeans() %>% data.frame(row.names = names(.), score =.)
    scores_df = merge(x = scores_df,y = metadata,by = 0) %>% column_to_rownames("Row.names")
    scores_df$condition = factor(scores_df$condition,levels = 
                                   c("Veh","Rox","osi_short","osi_short_roxa","osi_persistor","osi_persist_roxa"))
    summary_df <- scores_df %>%
    group_by(condition) %>%
    dplyr::summarise(
      Mean_Score = mean(score),
      SD_Score = sd(score),
      N = n(),
      SE_Score = SD_Score / sqrt(N)
    )
    means = summary_df$Mean_Score  %>% scale() %>% as.vector() %>% setNames(summary_df$condition)
    all_genesets_tpm[[pathway]] = means
  }
  
  all_genesets_tpm_df = all_genesets_tpm %>% as.data.frame() %>% t() %>% as.data.frame()
  all_cell_lines_TPM[[cell_line]] = all_genesets_tpm_df
}


```


```{r}
data = all_cell_lines_TPM$H1975 %>% t() 
#scatter plot
library(ggplot2)
library(ggrepel)


p1 = ggplot(data, aes(x = .data[[x_signature]], y =  .data[[y_signature]], label = rownames(data))) +
  geom_point() +
  geom_text_repel() +
  xlab(paste(x_signature,"mean TPM (scaled)")) +
  ylab(paste(y_signature,"mean TPM (scaled)")) +
  ggtitle(paste("H1975:",x_signature,"vs",y_signature)) +
  theme_minimal()

p1
data = all_cell_lines_TPM$HCC827 %>% t()
#scatter plot


p2 = ggplot(data, aes(x = .data[[x_signature]], y =  .data[[y_signature]], label = rownames(data))) +
  geom_point() +
  geom_text_repel() +
  xlab(paste(x_signature,"mean TPM (scaled)")) +
  ylab(paste(y_signature,"mean TPM (scaled)")) +
  ggtitle(paste("HCC827:",x_signature,"vs",y_signature)) +
  theme_minimal()

p2
```


```{r}
pdf(file = paste0(params$data_out_dir,paste0(x_signature,"-",y_signature,"_scatterplot_H1975.pdf")))
print(p1)
dev.off()
pdf(file = paste0(params$data_out_dir,paste0(x_signature,"-",y_signature,"_scatterplot_HCC827.pdf")))
print(p2)
dev.off()
```

```{r}
#write data- hif
clustered_mat = plot_genes_heatmap(genesets[["HIF_targets"]],return_df = T,plot = F)
clustered_mat = clustered_mat[,c("HCC827.Veh", 
                                 "HCC827.osi_persistor", "HCC827.osi_persist_roxa",
                                 "H1975.Veh", "H1975.osi_persistor",
                                 "H1975.osi_persist_roxa")]

write_xlsx(rownames_to_column(clustered_mat,var = "Gene"), path = paste0(params$data_out_dir,"HIF_genes_zscores.xlsx"))

#write data- fridman senescence
clustered_mat = plot_genes_heatmap(genesets[["FRIDMAN_SENESCENCE_UP"]],return_df = T,plot = F)
clustered_mat = clustered_mat[,c("HCC827.Veh", 
                                 "HCC827.osi_persistor", "HCC827.osi_persist_roxa",
                                 "H1975.Veh", "H1975.osi_persistor",
                                 "H1975.osi_persist_roxa")]
write_xlsx(rownames_to_column(clustered_mat,var = "Gene"), path = paste0(params$data_out_dir,"fridman_genes_zscore.xlsx"))

#write rk senescence
RK_senescence = c("ALDH1A3","AOPEP","CCN2","CDKN1A","CDKN1C","CDKN2A","CDKN2B","CDKN2D","CITED2","CLTB","COL1A2","CREG1","CRYAB","CXCL14","CYP1B1","EIF2S2","ESM1","F3","FILIP1L","FN1","GSN","GUK1","HBS1L","HPS5","HSPA2","HTATIP2","IFI16","IFNG","IGFBP1","IGFBP2","IGFBP3","IGFBP4","IGFBP5","IGFBP6","IGFBP7","IGSF3","ING1","IRF5","IRF7","ISG15","MAP1LC3B","MAP2K3","MMP1","NDN","NME2","NRG1","OPTN","PEA15","RAB13","RAB31","RAB5B","RABGGTA","TNFA","RBL2","YPEL3","SERPINB2","SERPINE1","SMPD1","SMURF2","SOD1","SPARC","TES","TFAP2A","TGFB1I1","THBS1","TNFAIP2","TNFAIP3","TP53","TSPYL5","ABI3","ARG2","B2M","EEF1E1","HLA-G","KIR2DL4","PAWR","SIRT1")
clustered_mat = plot_genes_heatmap(RK_senescence,return_df = T,plot = F)
clustered_mat = clustered_mat[,c("HCC827.Veh", 
                                 "HCC827.osi_persistor", "HCC827.osi_persist_roxa",
                                 "H1975.Veh", "H1975.osi_persistor",
                                 "H1975.osi_persist_roxa")]
write_xlsx(rownames_to_column(clustered_mat,var = "Gene"), path = paste0(params$data_out_dir,"RK_senescence_genes_zscore.xlsx"))

```


```{r fig.width=10}
library(ggVennDiagram)

#senescence venn
venn_data = list(
  SASP = genesets[["SASP"]],
  Fridman_senescence = genesets[["FRIDMAN_SENESCENCE_UP"]],
  GO_SENESCENCE = genesets[["GOBP_POSITIVE_REGULATION_OF_CELLULAR_SENESCENCE"]]
)
p = ggVennDiagram(venn_data, label_alpha = 0, label = "count") +
  scale_fill_gradient(low = "lightblue", high = "blue") +
  theme(legend.position = "none")+ 
  scale_x_continuous(expand = expansion(mult = 0.6))
p


#ros venn
venn_data = list(
  GOBP_RESPONSE_TO_ROS =  genesets[["GOBP_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES"]],
  GOBP_PROGRAMMED_CELL_DEATH_WHEN_ROS = genesets[["GOBP_PROGRAMMED_CELL_DEATH_IN_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES"]],
  Hallmark_ROS = genesets[["HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY"]]
)
p = ggVennDiagram(venn_data, label_alpha = 0, label = "count") +
  scale_fill_gradient(low = "lightblue", high = "blue") +
  theme(legend.position = "none")+ 
  scale_x_continuous(expand = expansion(mult = 0.8))
p
```
#FN1 and PI3

```{r}
summary_df_list = list()
pathway_genes = c("FN1","PI3")
for (cell_line in names(bulk_Mar25_TPM_list)) {
  cell_line_data = bulk_Mar25_TPM_list[[cell_line]]
  metadata = metadata_list[[cell_line]]
  scores_df = cell_line_data[pathway_genes,] %>% t() %>% as.data.frame() %>% merge(y = metadata,by = 0) %>% column_to_rownames("Row.names")
  
  
  summary_df <- scores_df %>%
  group_by(condition) %>%
  dplyr::summarise(
    across(all_of(pathway_genes), mean, .names = "{.col}")
  ) %>% column_to_rownames("condition") %>% scale()  %>%  t() %>% as.data.frame()%>% na.omit()
  summary_df_list[[cell_line]] = summary_df
}
```

```{r}
data = summary_df_list$H1975 %>% t() 
#scatter plot
library(ggplot2)
library(ggrepel)

x_signature = "FN1"
y_signature = "PI3"
p1 = ggplot(data, aes(x = .data[[x_signature]], y =  .data[[y_signature]], label = rownames(data))) +
  geom_point() +
  geom_text_repel() +
  xlab(paste(x_signature,"mean TPM (scaled)")) +
  ylab(paste(y_signature,"mean TPM (scaled)")) +
  ggtitle(paste("H1975:",x_signature,"vs",y_signature)) +
  theme_minimal()

p1
data = summary_df_list$HCC827 %>% t()
#scatter plot


p2 = ggplot(data, aes(x = .data[[x_signature]], y =  .data[[y_signature]], label = rownames(data))) +
  geom_point() +
  geom_text_repel() +
  xlab(paste(x_signature,"mean TPM (scaled)")) +
  ylab(paste(y_signature,"mean TPM (scaled)")) +
  ggtitle(paste("HCC827:",x_signature,"vs",y_signature)) +
  theme_minimal()

p2

plot_genes_heatmap(pathway_genes,return_df = F,plot = T)
```
# Signatures correlations

```{r}
groups_list = list()
for (cell_line in c("HCC827","H1975")){
  data = plot_genes_heatmap(genesets[["SASP"]],return_df = T,plot = F,pathway = "SASP",scale=F) %>%  
    dplyr::select(starts_with(cell_line)) %>% t() %>% cor()
  dist_matrix <- dist(data) 
  hc <- hclust(dist_matrix,method = "complete")
  groups <- cutree(hc, k = 2)
  groups_list[[cell_line]] = groups
  col_annotations = data.frame(group = factor(groups))
  connectivity <- rowMeans(data)
  top_5_genes <- names(sort(connectivity, decreasing = TRUE)[1:8])
  print(top_5_genes)
  
  # heatmap of correlation
  ht <- Heatmap(data, show_heatmap_legend = F, column_title= paste(cell_line,"SASP genes correlation"),
                cluster_rows = T, cluster_columns = T,top_annotation = HeatmapAnnotation(group = col_annotations$group))
  col_fun = colorRamp2(c(-1,0, 1), c("blue","white", "red"))
  title = "Pearson"
  lgd <- Legend(
    title = title,col_fun = col_fun)
  draw(ht, padding = unit(c(2, 2, 2, 75), "mm"))
  pushViewport(viewport(x=0.65, y=0.7, width=unit(4, "cm"), height=unit(6, "cm"), just=c("left","center")))
  draw(lgd,x = unit(0.2, "cm"), y = unit(1, "cm"))
  popViewport()
    
}

```
```{r}
group_1 = names(groups_list[[1]])[groups_list[[1]] == 1]
group_2 = names(groups_list[[2]])[groups_list[[2]] == 1]

intersect(group_1, group_2)
```

```{r}
genesets[["sasp_cor"]] = intersect(group_1, group_2)
```


# scatter 2 cell lines together, filtered list

```{r}

x_signature = "SASP" #oprions: "sasp_cor", "SASP"
y_signature = "HIF_targets"

all_cell_lines_TPM = list()

for (cell_line in names(bulk_Mar25_TPM_list)) {
  cell_line_data = bulk_Mar25_TPM_list[[cell_line]]
  metadata = metadata_list[[cell_line]]
  all_genesets_tpm = list()

  for (pathway in c(x_signature,y_signature)) {
    pathway_genes = genesets[[pathway]]
    pathway_genes = pathway_genes[pathway_genes %in% rownames(cell_line_data)]
    scores_df = cell_line_data[pathway_genes,] %>% colMeans() %>% data.frame(row.names = names(.), score =.)
    scores_df = merge(x = scores_df,y = metadata,by = 0) %>% column_to_rownames("Row.names")
    scores_df$condition = factor(scores_df$condition,levels = 
                                   c("Veh","Rox","osi_short","osi_short_roxa","osi_persistor","osi_persist_roxa"))
    summary_df <- scores_df %>%
    group_by(condition) %>%
    dplyr::summarise(
      Mean_Score = mean(score),
      SD_Score = sd(score),
      N = n(),
      SE_Score = SD_Score / sqrt(N)
    )
    means = summary_df$Mean_Score  %>% scale() %>% as.vector() %>% setNames(summary_df$condition)
    all_genesets_tpm[[pathway]] = means
  }
  
  all_genesets_tpm_df = all_genesets_tpm %>% as.data.frame() %>% t() %>% as.data.frame()
  all_cell_lines_TPM[[cell_line]] = all_genesets_tpm_df
}


```


```{r}

data_1975 = all_cell_lines_TPM$H1975 %>% t() 
data_827 = all_cell_lines_TPM$HCC827 %>% t()
all_data = rbind(data_1975,data_827) %>% as.data.frame()

all_data$cell_line = c(rep("H1975",nrow(data_1975)),rep("HCC827",nrow(data_827)))
#drop rows with "osi_short"
all_data = all_data  %>% filter(!grepl("osi_short", rownames(all_data)))
#scatter plot
library(ggplot2)
library(ggrepel)


p1 = ggplot(all_data, aes(x = .data[[x_signature]], y =  .data[[y_signature]], label = rownames(all_data), color= cell_line)) +
  geom_point() +
  geom_text_repel() +
  # set colors
  scale_colour_manual(values = c("H1975" = "red", "HCC827" = "blue")) +
  xlab(paste(x_signature,"mean TPM (scaled)")) +
  ylab(paste(y_signature,"mean TPM (scaled)")) +
  ggtitle(paste("H1975:",x_signature,"vs",y_signature)) +
  theme_minimal()

p1

```


# Kurpa genes

```{r fig.height=7, fig.width=6}
kurpa_sasp <- c(
  "IL-1b"     = "IL1B",
  "IP-10"     = "CXCL10",
  "MCP-1"     = "CCL2",
  "IL-12p40"  = "IL12B",
  "IL-12P70"  = "IL12A",
  "IL-6"      = "IL6",
  "IL-13"     = "IL13",
  "IFNg"      = "IFNG",
  "G-CSF"     = "CSF3",
  "IL-4"      = "IL4",
  "EGF"       = "EGF",
  "IL-10"     = "IL10",
  "IL-7"      = "IL7",
  "IL-1RA"    = "IL1RN",
  "IFNa2"     = "IFNA2",
  "RANTES"    = "CCL5",
  "Eotaxin"   = "CCL11",
  "IL-15"     = "IL15",
  "IL-8"      = "CXCL8",
  "TNFa"      = "TNF",
  "TNFb"      = "LTA",
  "IL-2"      = "IL2",
  "IL-1a"     = "IL1A",
  "IL-17A"    = "IL17A",
  "IL-3"      = "IL3",
  "IL-5"      = "IL5",
  "MIP-1a"    = "CCL3",
  "MIP-1b"    = "CCL4",
  "VEGF"      = "VEGFA",
  "GM-CSF"    = "CSF2"
)

sasp_genes_flat <- unname(kurpa_sasp)

data = plot_genes_heatmap(sasp_genes_flat ,return_df = T,plot = F,pathway = "SASP",scale=F,filter=F)

data = data+1 #psudocount
log2_fc = data.frame(row.names  = rownames(data), 
                     HCC827_fc = log2(data$HCC827.osi_persistor/data$HCC827.Veh),
                     H1975_fc = log2(data$H1975.osi_persistor/data$H1975.Veh))
#rename rownames to kurpa names
match_indices <- match(rownames(log2_fc), kurpa_sasp) 
rownames(log2_fc) = names(kurpa_sasp)[match_indices]
#order log2_fc by kurpa_sasp names
log2_fc = log2_fc[names(kurpa_sasp), ] %>% na.omit()

#heatmap of log2_fc
ht <- Heatmap(as.matrix(log2_fc[,c("HCC827_fc","H1975_fc")]), show_heatmap_legend = F, 
              column_title= paste("SASP genes log2 FC osi_persistor vs Veh"),
              cluster_rows = F, cluster_columns = F, show_row_names = T)
col_fun = colorRamp2(c(min(log2_fc[,c("HCC827_fc","H1975_fc")]),0, max(log2_fc[,c("HCC827_fc","H1975_fc")])), c("blue","white", "red"))
title = "log2 FC"
lgd <- Legend(
  title = title,col_fun = col_fun)
draw(ht, padding = unit(c(4, 10, 10, 75), "mm"))
pushViewport(viewport(x=0.8, y=0.7, width=unit(4, "cm"), height=unit(6, "cm"), just=c("left","center")))
draw(lgd,x = unit(0.2, "cm"), y = unit(1, "cm"))
popViewport()
```

