---
title: "All cell GSVA analysis"
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
editor_options: 
  chunk_output_type: inline
params:
  data_out_dir: "./temp_data/" 
---


```{r}
source("./pipe.R")
input = pipeline$Bulk_GSVA$input
output = pipeline$Bulk_GSVA$output
```

```{r}
library(GSVA)
library(dplyr)
library(tibble)
library(ComplexHeatmap)
library(circlize)
library(writexl)
library(GSEABase)
```

```{r}
bulk_Mar25_TPM_list = readRDS(input$bulk_Mar25_TPM_list)
metadata_list = readRDS(input$metadata_list)
```

```{r}
all_msigdb = readRDS(input$msigdb) %>% geneIds() 
```

```{r}
genesets_annot= data.frame()

# Add Hallmarkd
genesets = getGmt(input$msigDB_hallmarks) %>% geneIds() 
genesets_annot = rbind(genesets_annot,
                        data.frame(
                          pathway = names(genesets),
                          name = "Hallmarks"
                        ))
# rename ROS  annotation pathway
genesets_annot[genesets_annot$pathway == "HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY","name"] = "ROS"

#senescence  pathways
pathways_to_check = c("FRIDMAN_SENESCENCE_UP","REACTOME_OXIDATIVE_STRESS_INDUCED_SENESCENCE","GOBP_ONCOGENE_INDUCED_CELL_SENESCENCE", "GOBP_POSITIVE_REGULATION_OF_CELLULAR_SENESCENCE", "KAMMINGA_SENESCENCE", "WP_KYNURENINE_PATHWAY_AND_LINKS_TO_CELL_SENESCENCE")
senescence_pathways = all_msigdb[pathways_to_check]
genesets = c(genesets, senescence_pathways)
genesets_annot = rbind(genesets_annot,
                        data.frame(
                          pathway = names(senescence_pathways),
                          name = "Senescence"
                        ))

# ROS pathways
pathways_to_check = c("GOBP_PROGRAMMED_CELL_DEATH_IN_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES" ,"GOBP_POSITIVE_REGULATION_OF_REACTIVE_OXYGEN_SPECIES_METABOLIC_PROCESS", 
                      "GOBP_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES")
ros_pathways = all_msigdb[pathways_to_check]
genesets = c(genesets, ros_pathways)
genesets_annot = rbind(genesets_annot,
                        data.frame(
                          pathway = names(ros_pathways),
                          name = "ROS"
                        ))


hif_targets =  scan(input$hif_targets, character(), quote = "")
genesets[["HIF_targets"]] = hif_targets

genesets_annot = rbind(genesets_annot,
                        data.frame(
                          pathway = "HIF_targets",
                          name = "Hallmarks"
                        ))



sasp =  scan(input$SASP_genes, character(), quote = "")
genesets[["SASP"]] = hif_targets

genesets_annot = rbind(genesets_annot,
                        data.frame(
                          pathway = c("SASP"),
                          name = "Senescence"
                        ))

```



```{r}
# run GSVA
gsva_results_list = list()
for (cell_line in names(bulk_Mar25_TPM_list)) {
  cell_line_data = bulk_Mar25_TPM_list[[cell_line]] %>%
  mutate(across(where(is.numeric), ~ log2(.x + 1))) %>%  # log2 transform
  as.matrix()
  
    gsva_params <- gsvaParam(
    exprData = cell_line_data,
    geneSets = genesets,
    kcdf = "Gaussian", 
    minSize = 10,    
    maxSize = 500    
  )
  
  gsva_results <- gsva(gsva_params)
  gsva_results_list[[cell_line]] = gsva_results
}



```


```{r}
summary_df_list = list()
for (cell_line in names(gsva_results_list)) {
  gsva_results = gsva_results_list[[cell_line]]
  metadata = metadata_list[[cell_line]]

  scores_df = gsva_results %>% t() %>% as.data.frame() %>% merge(y = metadata, by = 0) %>% column_to_rownames("Row.names")
  summary_df <- scores_df %>%
    group_by(condition) %>%
    dplyr::summarise(across(where(is.numeric), mean, .names = "{.col}")) %>% column_to_rownames("condition") %>% scale()  %>% 
    t() %>% as.data.frame() %>% na.omit()
  summary_df_list[[cell_line]] = summary_df
}

#cbind dfs in list
summary_df = do.call(cbind,summary_df_list)

```

```{r fig.height=11, fig.width=10}

ordered_pathways = genesets_annot %>% filter(pathway %in% rownames(summary_df)) %>%
  mutate(pathway = factor(pathway,levels = rownames(summary_df))) %>% arrange(pathway) %>% pull(name)


ht <- Heatmap(summary_df, show_heatmap_legend = FALSE,
              column_split = str_extract(colnames(summary_df),"H1975|HCC"),   
              column_title_gp = gpar(fill = c("green", "orange")),
              column_order  = colnames(summary_df),row_split = ordered_pathways)
col_fun = colorRamp2(c(min(summary_df), max(summary_df)), c("blue", "red"))

lgd <- Legend(
  title = "Mean scaled score",col_fun = col_fun)

draw(ht, padding = unit(c(2, 2, 2, 75), "mm"))
pushViewport(viewport(x=0.8, y=0.7, width=unit(4, "cm"), height=unit(6, "cm"), just=c("left","center")))
draw(lgd,x = unit(2, "cm"), y = unit(9, "cm"))
popViewport()
```

```{r}
row_order_indices = row_order(ht) %>% unlist() %>% unname()
clustered_mat = summary_df[row_order_indices, ]
write_xlsx(rownames_to_column(clustered_mat,var = "Pathway"), path = paste0(params$data_out_dir,"GSVA_scores_heatmap.xlsx"))

```

```{r fig.height=8, fig.width=7}


plot_genes_heatmap <- function(pathway, return_df = F, plot = T) {
  pathway_genes = genesets[[pathway]]
  pathway_genes = pathway_genes[pathway_genes %in% rownames(bulk_Mar25_TPM_list[[1]]) & pathway_genes %in% rownames(bulk_Mar25_TPM_list[[2]])]
  # expressed in at least one sample
  pathway_genes = pathway_genes[rowSums(bulk_Mar25_TPM_list[[1]][pathway_genes,]) >0 & rowSums( bulk_Mar25_TPM_list[[2]][pathway_genes,])>0]
  summary_df_list = list()
  
  for (cell_line in names(bulk_Mar25_TPM_list)) {
    cell_line_data = bulk_Mar25_TPM_list[[cell_line]]
    metadata = metadata_list[[cell_line]]
    scores_df = cell_line_data[pathway_genes,] %>% t() %>% as.data.frame() %>% merge(y = metadata,by = 0) %>% column_to_rownames("Row.names")
    
    
    summary_df <- scores_df %>%
    group_by(condition) %>%
    dplyr::summarise(
      across(pathway_genes, mean, .names = "{.col}")
    ) %>% column_to_rownames("condition") %>% scale()  %>%  t() %>% as.data.frame()%>% na.omit()
    summary_df_list[[cell_line]] = summary_df
  }
  
  #cbind dfs in list
  summary_df = do.call(cbind,summary_df_list)
  
  
  ht <- Heatmap(summary_df, show_heatmap_legend = FALSE, column_title= pathway,
                column_order  = colnames(summary_df),
                column_split = str_extract(colnames(summary_df),"H1975|HCC"))
  col_fun = colorRamp2(c(min(summary_df), max(summary_df)), c("blue", "red"))
  
  lgd <- Legend(
    title = "TPM mean \nZ score",col_fun = col_fun)
  if (plot){
    draw(ht, padding = unit(c(2, 2, 2, 75), "mm"))
    pushViewport(viewport(x=0.8, y=0.7, width=unit(4, "cm"), height=unit(6, "cm"), just=c("left","center")))
    draw(lgd,x = unit(0.2, "cm"), y = unit(1, "cm"))
    popViewport()
  }
  
  
  if (return_df) {
    row_order_indices = row_order(ht) %>% unlist() %>% unname()
    clustered_mat = summary_df[row_order_indices, ]
    return(clustered_mat)
  }
}

  
```

