---
title: "All cell lines analysis"
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
editor_options: 
  chunk_output_type: inline
params:
  cell_line: "HCC"
  data_out_dir: "./temp_data/" 
---

```{r}
source("./pipe.R")
input = pipeline$march25_all_analysis$input
output = pipeline$march25_all_analysis$output
```


```{r}
suppressPackageStartupMessages(library(GSEABase))
source_from_github(repositoy = "DEG_functions",version = "0.2.54")
```

# Create data
```{r}
bulk_Mar25_raw = read.table(
  file = input$rna_counts,
  sep = "\t",
  header = TRUE
) %>% as.data.frame() 

bulk_Mar25_TPM = bulk_Mar25_raw %>%   dplyr::select(!c("Geneid","Chr", "Start", "End", "Strand","Length"))
rownames(bulk_Mar25_TPM) = make.unique(bulk_Mar25_TPM[,"gene_name",drop=T])
bulk_Mar25_TPM  = bulk_Mar25_TPM %>% dplyr::select(!c("gene_name"))
colnames(bulk_Mar25_TPM) = gsub(pattern = ".bam",replacement = "",x = colnames(bulk_Mar25_TPM))


```

```{r}
#adjust sample names
#read xlsx file
library(readxl)
sample_description = readxl::read_xlsx(input$sample_description, sheet = 1) %>% 
  as.data.frame() 

 sample_description = sample_description %>%  mutate(new_name = paste(sample_description$`Group Name\r\n(Required)`,c(1:3),sep = "_")) 


bulk_Mar25_TPM = bulk_Mar25_TPM[,sample_description$`Sample Name`]
colnames(bulk_Mar25_TPM) = sample_description$new_name
colnames(bulk_Mar25_TPM)  = colnames(bulk_Mar25_TPM) %>%  
  gsub(pattern = "_Osi_",replacement = "_osi_short_") %>% 
  gsub(pattern = "_OsiRox_",replacement = "_osi_short_roxa_") %>% 
  gsub(pattern = "_Per_",replacement = "_osi_persistor_") %>% 
  gsub(pattern = "_PerRox_",replacement = "_osi_persist_roxa_") 


```

# cell lines comparision
```{r}
# create metadata
cell.labels = names(bulk_Mar25_TPM)
condition = str_extract(cell.labels, "HCC|H1975")
metadata = data.frame(condition = condition, row.names = colnames(bulk_Mar25_TPM))
```

```{r}
suppressPackageStartupMessages(library(DESeq2))
dds <- DESeqDataSetFromMatrix(countData = round(bulk_Mar25_TPM),
                              colData = metadata,
                              design = ~condition)
```
## filtering
```{r}
nrow(dds)
dds1 <- dds[ rowSums(counts(dds)) >= 3, ] # filter low count genes
nrow(dds1)
```

## PCA
```{r}
vst = vst(dds1, blind=FALSE)
```

```{r}
library("ggfortify")
PCAdata <- prcomp(t(assay(vst)))
autoplot(PCAdata, data = metadata,colour = "condition",label = FALSE, main="PCA") # Show dots
```

## Distance plot
```{r}
library(pheatmap)
vsd <- vst(dds, blind=FALSE)
sampleDists <- dist(t(assay(vsd)), method = "euclidean")
library("RColorBrewer")
sampleDistMatrix <- as.matrix(sampleDists)
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
p = pheatmap::pheatmap(sampleDistMatrix,
         clustering_distance_rows=sampleDists,
         clustering_distance_cols=sampleDists,
         col=colors, main = "Sample euclidean distance Matrix")
p
```
```{r}
pdf(paste0(params$data_out_dir,"distance plot.pdf"),width = 8,height = 6)
p
dev.off()
```

# up in: osi persist+roxa vs osi persist, but not in: ctrl vs roxa

```{r fig.width=10}
up_in_persistors_HCC = read.table(file = input$up_in_persistors_HCC, sep = "\t", header = TRUE) %>% 
  as.data.frame()
up_in_persistors_H1975 = read.table(file = input$up_in_persistors_H1975, sep = "\t", header = TRUE) %>% 
  as.data.frame()
#find intersection
up_in_persistors_all_cell_lines = intersect(up_in_persistors_HCC[1], up_in_persistors_H1975[1])
down_in_persistors_all_cell_lines = intersect(up_in_persistors_HCC[2], up_in_persistors_H1975[2])


# heatmap of HCC up genes in H1975

library(ComplexHeatmap)
gene_vec = up_in_persistors_HCC %>% as.list() %>% unlist  %>% na.omit() # make named vector
names(gene_vec) = names(gene_vec) %>% gsub(pattern = "[0-9]",replacement = "") # remove numbers from names
ha1 = rowAnnotation(up_or_down = names(gene_vec),
                    col = list(cell_line = c(up_nes = "red",down_nes = "blue")))


ha2 = columnAnnotation(cell_line = names(bulk_Mar25_TPM) %>% str_extract(pattern  = "HCC|H1975"),
                       col = list(cell_line = c(HCC = "green",H1975 = "orange")))

signautre_expression = bulk_Mar25_TPM[gene_vec,] %>% t() %>% scale() %>% t() %>% as.data.frame() 

p1 = Heatmap(signautre_expression, cluster_rows = F, cluster_columns = F, name = "Z-score TPM",column_title = "up in HCC Genes",left_annotation = ha1,top_annotation = ha2,column_split = names(bulk_Mar25_TPM) %>% str_extract(pattern  = "HCC|H1975") ,column_gap = unit(4, "mm"))
p1


# heatmap of H1975 up genes in HCC
gene_vec = up_in_persistors_H1975 %>% as.list() %>% unlist  %>% na.omit() # make named vector
names(gene_vec) = names(gene_vec) %>% gsub(pattern = "[0-9]",replacement = "") # remove numbers from names
ha1 = rowAnnotation(up_or_down = names(gene_vec),
                    col = list(cell_line = c(up_nes = "red",down_nes = "blue")))


ha2 = columnAnnotation(cell_line = names(bulk_Mar25_TPM) %>% str_extract(pattern  = "HCC|H1975"),
                       col = list(cell_line = c(HCC = "green",H1975 = "orange")))

signautre_expression = bulk_Mar25_TPM[gene_vec,] %>% t() %>% scale() %>% t() %>% as.data.frame() 

p2 = Heatmap(signautre_expression, cluster_rows = F, cluster_columns = F, name = "Z-score TPM",column_title = "up in H1975 Genes",left_annotation = ha1,top_annotation = ha2,column_split = names(bulk_Mar25_TPM) %>% str_extract(pattern  = "HCC|H1975") ,column_gap = unit(4, "mm"))
p2
```
```{r}
pdf(paste0(params$data_out_dir,"up_in_HCC_persistors.pdf"),width = 10,height = 6)
p1
dev.off()

pdf(paste0(params$data_out_dir,"up_in_H1975_persistors.pdf"),width = 10,height = 6)
p2
dev.off()
```

# signatures
```{r fig.width=9}
# expression heatmap of signatures
SASP_signature = c("CCL2", "CCL5", "CCL7", "IL1A", "IL1B", "IL32","SCG2", "INHBA", "INHA", "WNT7A", "CSF2", "TNFRSF11B", "GREM1", "CMTM3")
FRIDMAN_SENESCENCE_UP  = getGmt(input$SENESCENCE) %>% geneIds() %>%  unlist() %>% base::unname()
hif_targets =  scan(input$hif_targets, character(), quote = "")


SASP_signautre_expression = bulk_Mar25_TPM[SASP_signature[SASP_signature %in% rownames(bulk_Mar25_TPM)],] %>%  
  colMeans() %>% as.data.frame() %>% setNames("SASP_signature")
SENESCENCE_signautre_expression = bulk_Mar25_TPM[FRIDMAN_SENESCENCE_UP[FRIDMAN_SENESCENCE_UP %in% rownames(bulk_Mar25_TPM)],] %>%
  colMeans() %>% as.data.frame() %>% setNames("FRIDMAN\nSENESCENCE_UP")

signatures = cbind(SASP_signautre_expression,SENESCENCE_signautre_expression)

signatures_H1975 = signatures[startsWith(rownames(signatures),prefix = "H1975"),,drop=F]
signatures_H1975_scaled = scale(signatures_H1975)

signatures_HCC = signatures[startsWith(rownames(signatures),prefix = "HCC"),,drop=F]
signatures_HCC_scaled = scale(signatures_HCC)


all_signature_expression_zscore = t(rbind(signatures_H1975_scaled, signatures_HCC_scaled)) %>% as.data.frame()

p1 = Heatmap(all_signature_expression_zscore, cluster_rows = F, cluster_columns = F, name = "Z-score TPM",column_title = "signatures")
p1

# expression heatmap of genes

signautre_expression = bulk_Mar25_TPM[SASP_signature[SASP_signature %in% rownames(bulk_Mar25_TPM)],]  %>% t() %>% as.data.frame()
signatures_H1975 = signautre_expression[startsWith(rownames(signautre_expression),prefix = "H1975"),,drop=F]
signatures_H1975_scaled = scale(signatures_H1975)

signatures_HCC = signautre_expression[startsWith(rownames(signautre_expression),prefix = "HCC"),,drop=F]
signatures_HCC_scaled = scale(signatures_HCC)

all_signature_expression_zscore = t(rbind(signatures_H1975_scaled, signatures_HCC_scaled)) %>% as.data.frame()



all_signature_expression_zscore = all_signature_expression_zscore[complete.cases(all_signature_expression_zscore), ] #Remove rows with all or some NAs

p2 = Heatmap(all_signature_expression_zscore, cluster_rows = T, cluster_columns = F, name = "Z-score TPM",column_title = "SASP genes")
p2

# signautre_expression = bulk_Mar25_TPM[FRIDMAN_SENESCENCE_UP[FRIDMAN_SENESCENCE_UP %in% rownames(bulk_Mar25_TPM)],]  %>% t() %>% scale() %>% t() %>% as.data.frame() 
# 
# 
# p3 = Heatmap(signautre_expression, cluster_rows = T, cluster_columns = F, name = "Z-score TPM",column_title = "FRIDMAN_SENESCENCE_UP genes",row_names_gp = gpar(fontsize = 8))

```
```{r fig.height=5, fig.width=12}
 library(dplyr)
# create metadata
cell.labels = names(bulk_Mar25_TPM)
condition = str_extract(cell.labels, "Veh|osi_short_[1-9]|Rox|osi_short_roxa|osi_persistor|osi_persist_roxa") %>% gsub(pattern = "_[1-9]",replacement = "") %>% factor(levels = c("Veh","Rox","osi_short","osi_short_roxa","osi_persistor","osi_persist_roxa"))
cell_type = str_extract(cell.labels, "HCC|H1975")

metadata = data.frame(condition = condition,cell_type =cell_type, row.names = colnames(bulk_Mar25_TPM))
#z score per cell line, mean over replicates

all_signatures = list("hif_targets" = hif_targets,"FRIDMAN_SENESCENCE_UP" = FRIDMAN_SENESCENCE_UP,"SASP_signature" = SASP_signature)
signautre_scores = list()
for (signautre_name in names(all_signatures)) {
  signature = all_signatures[[signautre_name]]
  scores_df = bulk_Mar25_TPM[signature,] %>% colMeans() %>% data.frame(row.names = names(.), score =.) 
  names(scores_df)[names(scores_df) == "score"] <- signautre_name
  
  signautre_scores[[signautre_name]] = scores_df
}
final_df <- do.call(cbind, signautre_scores)

final_df = merge(x = final_df,y = metadata,by = 0) %>% column_to_rownames("Row.names")

all_data = list()
for (cell_line in c("HCC","H1975")) {
  cell_line_data = final_df %>% filter(cell_type == cell_line)
  cell_line_data = cell_line_data %>%   group_by(condition) %>% 
    dplyr::summarise(hif_targets_mean = mean(hif_targets),
                     FRIDMAN_SENESCENCE_UP_mean = mean(FRIDMAN_SENESCENCE_UP),
                     SASP_signature_mean = mean(SASP_signature) )  %>% 
    mutate(
      scaled_hif_targets_mean = as.vector(scale(hif_targets_mean)),
      scaled_FRIDMAN_SENESCENCE_UP_mean = as.vector(scale(FRIDMAN_SENESCENCE_UP_mean)),
      scaled_SASP_signature_mean = as.vector(scale(SASP_signature_mean))
    ) %>% 
    mutate(cell_type = cell_line) %>% as.data.frame()
  all_data[[cell_line]] = cell_line_data
}
all_data_df = rbindlist(all_data) %>% as.data.frame()
rownames(all_data_df) = paste0(all_data_df$cell_type,"_",all_data_df$condition) 
all_data_df_to_plot = all_data_df %>%   select(-condition)%>% select(-cell_type) %>%  t() %>% as.data.frame()
all_data_df_to_plot = all_data_df_to_plot[startsWith(x = rownames(all_data_df_to_plot),prefix = "scaled"),] # take jst scaled rows

ha2 = columnAnnotation(cell_line = all_data_df$cell_type,
                       col = list(cell_line = c(HCC = "green",H1975 = "orange")))




p1 = Heatmap(all_data_df_to_plot, cluster_rows = F, cluster_columns = F, name = "Z-score TPM",
             top_annotation = ha2,column_split  = all_data_df$cell_type ,column_gap = unit(4, "mm"))


p1


```

```{r fig.height=12, fig.width=9}
# p3
```
```{r}
# calculate fold change in SASP HCC
cp_vs_op = SASP_signautre_expression[startsWith(rownames(SASP_signautre_expression),"HCC_osi_persist_roxa"),"SASP_signature",] %>% mean()/
  SASP_signautre_expression[startsWith(rownames(SASP_signautre_expression),"HCC_osi_persistor"),"SASP_signature",] %>% mean()

rox_vs_veh = SASP_signautre_expression[startsWith(rownames(SASP_signautre_expression),"HCC_Rox"),"SASP_signature",] %>% mean()/
  SASP_signautre_expression[startsWith(rownames(SASP_signautre_expression),"HCC_Veh"),"SASP_signature",] %>% mean()
print(paste("HCC cp_vs_op_SASP:",cp_vs_op))
print(paste("HCC rox_vs_veh_SASP:",rox_vs_veh))

# calculate fold change in SASP H1975
cp_vs_op_H1975 = SASP_signautre_expression[startsWith(rownames(SASP_signautre_expression),"H1975_osi_persist_roxa"),"SASP_signature",] %>% mean()/
  
  SASP_signautre_expression[startsWith(rownames(SASP_signautre_expression),"H1975_osi_persistor"),"SASP_signature",] %>% mean()

rox_vs_veh_H1975 = SASP_signautre_expression[startsWith(rownames(SASP_signautre_expression),"H1975_Rox"),"SASP_signature",] %>% mean()/
  SASP_signautre_expression[startsWith(rownames(SASP_signautre_expression),"H1975_Veh"),"SASP_signature",] %>% mean()
print(paste("H1975 cp_vs_op_SASP:",cp_vs_op_H1975))
print(paste("H1975 rox_vs_veh_SASP:",rox_vs_veh_H1975))

## calculate fold change in fridman senesence HCC
cp_vs_op_fridman = SENESCENCE_signautre_expression[startsWith(rownames(SENESCENCE_signautre_expression),"HCC_osi_persist_roxa"),"FRIDMAN\nSENESCENCE_UP",] %>% mean()/
  SENESCENCE_signautre_expression[startsWith(rownames(SENESCENCE_signautre_expression),"HCC_osi_persistor"),"FRIDMAN\nSENESCENCE_UP",] %>% mean()

rox_vs_veh_fridman = SENESCENCE_signautre_expression[startsWith(rownames(SENESCENCE_signautre_expression),"HCC_Rox"),"FRIDMAN\nSENESCENCE_UP",] %>% mean()/
  SENESCENCE_signautre_expression[startsWith(rownames(SENESCENCE_signautre_expression),"HCC_Veh"),"FRIDMAN\nSENESCENCE_UP",] %>% mean()
print(paste("HCC cp_vs_op_fridman:",cp_vs_op_fridman))
print(paste("HCC rox_vs_veh_fridman:",rox_vs_veh_fridman))


## calculate fold change in fridman senesence H1975
cp_vs_op_fridman_H1975 = SENESCENCE_signautre_expression[startsWith(rownames(SENESCENCE_signautre_expression),"H1975_osi_persist_roxa"),"FRIDMAN\nSENESCENCE_UP",] %>% mean()/
  SENESCENCE_signautre_expression[startsWith(rownames(SENESCENCE_signautre_expression),"H1975_osi_persistor"),"FRIDMAN\nSENESCENCE_UP",] %>% mean()

rox_vs_veh_fridman_H1975 = SENESCENCE_signautre_expression[startsWith(rownames(SENESCENCE_signautre_expression),"H1975_Rox"),"FRIDMAN\nSENESCENCE_UP",] %>% mean()/
  SENESCENCE_signautre_expression[startsWith(rownames(SENESCENCE_signautre_expression),"H1975_Veh"),"FRIDMAN\nSENESCENCE_UP",] %>% mean()
print(paste("H1975 cp_vs_op_fridman:",cp_vs_op_fridman_H1975))
print(paste("H1975 rox_vs_veh_fridman:",rox_vs_veh_fridman_H1975))

```

```{r}
pdf(paste0(params$data_out_dir,"signatures.pdf"),width = 10,height = 6)
p1
dev.off()

pdf(paste0(params$data_out_dir,"SASP_genes.pdf"),width = 10,height = 6)
p2
dev.off()

# pdf(paste0(params$data_out_dir,"SENESCENCE_genes.pdf"),width = 12,height = 9)
# p3
# dev.off()
```

#  all hallmarks
```{r fig.height=15, fig.width=12}

all_pathways = data.frame(row.names = names(bulk_Mar25_TPM))

i=1
for (pathway in names(genesets)) {
  genes_in_data = genesets[[pathway]][genesets[[pathway]] %in% rownames(bulk_Mar25_TPM)]
  mean_expression = bulk_Mar25_TPM[genes_in_data,] %>%  
  colMeans() %>% as.data.frame() %>% setNames(pathway)
  mean_expression = mean_expression[rownames(all_pathways),,drop=F] #order
  all_pathways = cbind(all_pathways,mean_expression)
  names(all_pathways)[i] = pathway
  i=i+1
}

all_pathways_scaled = scale(all_pathways)



p1 = Heatmap(t(all_pathways_scaled), cluster_rows = T, cluster_columns = F, name = "Z-score TPM",column_title = "signatures")
p1

```

```{r}
#TODO: read H1975_uniqe_deg_list and H1975_uniqe_deg_list
for (i in 1:length(H1975_uniqe_deg_list)) {
  common = intersect(H1975_uniqe_deg_list[[i]], HCC_uniqe_deg_list[[i]])
  # print(hif_targets[hif_targets %in% common])
  # print(common)
  print(diff_genes[common,])
  
  if(length(common)>=3){
  hyp_obj <- hypeR(common, genesets, test = "hypergeometric", fdr=1, plotting=F,
                   background = rownames(bulk_Mar25_TPM))
  plt2 = hyp_dots(hyp_obj,title = names(H1975_uniqe_deg_list)[i])
  plt2 = plt2 + scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =exp(-seq(-log(min(plt2$data$fdr)), -log(max(plt2$data$fdr)), 
            length.out = 6)) %>% signif(digits = 2))
  print(plt2)
  }
  
}
```

