---
title: 'bulk RNA-seq analysis' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
editor_options: 
  chunk_output_type: inline
params:
  cell_line: "HCC"
  data_out_dir: "./temp_data/" 
---

```{r}
source("./pipe.R")
input = pipeline$bulk_mar25_HCC$input
output = pipeline$bulk_mar25_HCC$output
```


```{r}
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(GSEABase))
source_from_github(repositoy = "DEG_functions",version = "0.2.54")
```
#signatures

```{r}
genesets = getGmt(input$genesets) %>% geneIds()
# add senesence signatures to genesets
SASP_signature = c("CCL2", "CCL5", "CCL7", "IL1A", "IL1B", "IL32","SCG2", "INHBA", "INHA", "WNT7A", "CSF2", "TNFRSF11B", "GREM1", "CMTM3")
FRIDMAN_SENESCENCE_UP  = getGmt(input$SENESCENCE) %>% geneIds() %>%  unlist() %>% base::unname()

genesets = c(genesets, list(SASP = SASP_signature,
                        FRIDMAN_SENESCENCE_UP = FRIDMAN_SENESCENCE_UP))

hif_targets =  scan(input$hif_targets, character(), quote = "")
genesets[["HIF_targets"]] = hif_targets

```

# Create data
```{r}
bulk_Mar25_raw = read.table(
  file = input$rna_counts,
  sep = "\t",
  header = TRUE
) %>% as.data.frame() 

bulk_Mar25_TPM = bulk_Mar25_raw %>%   dplyr::select(!c("Geneid","Chr", "Start", "End", "Strand","Length"))
rownames(bulk_Mar25_TPM) = make.unique(bulk_Mar25_TPM[,"gene_name",drop=T])
bulk_Mar25_TPM  = bulk_Mar25_TPM %>% dplyr::select(!c("gene_name"))
colnames(bulk_Mar25_TPM) = gsub(pattern = ".bam",replacement = "",x = colnames(bulk_Mar25_TPM))


```

```{r}
#adjust sample names
#read xlsx file
library(readxl)
sample_description = readxl::read_xlsx(input$sample_description, sheet = 1) %>% 
  as.data.frame() 

sample_description = sample_description %>%  mutate(new_name = paste(sample_description$`Group Name\r\n(Required)`,c(1:3),sep = "_")) 


bulk_Mar25_TPM = bulk_Mar25_TPM[,sample_description$`Sample Name`]
colnames(bulk_Mar25_TPM) = sample_description$new_name
colnames(bulk_Mar25_TPM)  = colnames(bulk_Mar25_TPM) %>%  
  gsub(pattern = "_Osi_",replacement = "_osi_short_") %>% 
  gsub(pattern = "_OsiRox_",replacement = "_osi_short_roxa_") %>% 
  gsub(pattern = "_Per_",replacement = "_osi_persistor_") %>% 
  gsub(pattern = "_PerRox_",replacement = "_osi_persist_roxa_") 


```


```{r}
# get cell line
cell_line_bulk = bulk_Mar25_TPM[,startsWith(colnames(bulk_Mar25_TPM),params$cell_line)]
```



```{r}
# create metadata
cell.labels = names(cell_line_bulk)
condition = str_extract(cell.labels, "Veh|osi_short_[1-9]|Rox|osi_short_roxa|osi_persistor|osi_persist_roxa") %>% gsub(pattern = "_[1-9]",replacement = "")
peristor = str_extract(cell.labels, "short|persist")
metadata = data.frame(condition = condition, row.names = colnames(cell_line_bulk))
```

```{r}
metadata_orig = metadata
metadata <- metadata %>%
  mutate(
    state = case_when(
      grepl("persist", condition) ~ "osi_persistent",
      grepl("short", condition) ~ "osi_short",
      TRUE ~ "Vec"
    ),
    roxa = ifelse(grepl("roxa", condition) | condition == "Rox", "yes", "no")
  )


#filter out osi short
keep <- metadata$condition %in% c("Veh", "Rox", "osi_persistor", "osi_persist_roxa")
cell_line_bulk_orig = cell_line_bulk
cell_line_bulk   <- cell_line_bulk[, keep]
metadata     <- metadata[keep, , drop=FALSE]



metadata$state = factor(metadata$state, levels = c("Vec","osi_persistent"))
metadata$roxa = factor(metadata$roxa, levels = c("no", "yes"))

metadata
```


```{r}
dds <- DESeqDataSetFromMatrix(countData = round(cell_line_bulk),
                              colData = metadata,
                              design = ~ state + roxa + state:roxa)
```
```{r}
dds <- DESeq(dds)  
```

```{r}
resultsNames(dds)
```
```{r}
res_interaction <- results(dds, contrast = list(
  c("stateosi_persistent.roxayes")
))
```

```{r}
res_interaction <- res_interaction[!is.na(res_interaction$padj), ]
res_interaction = res_interaction[order(res_interaction$log2FoldChange,decreasing = T), ] %>% as.data.frame()
```

```{r fig.height=6, fig.width=13, results='asis'}
ranked_vec = res_interaction[,"log2FoldChange"]%>% setNames(rownames(res_interaction)) %>% na.omit() %>%  #order by FC
  sort(decreasing = T) # sort

# create 6 breaks between plot limits in log scale and then exponent, otherwise breaks not good
breaks_fun = function(limits){ 
  breaks = exp(-seq(-log(limits[1]), -log(limits[2]), length.out = 6))
  breaks[1] = breaks[1] * 0.95 #adjust extreme ticks to prevent truncation
  breaks[7] = breaks[7] * 1.05
  return(signif(breaks, digits = 2))
}

hyp_obj <- hypeR_fgsea(ranked_vec, genesets, up_only = F)
plt = hyp_dots(hyp_obj,merge = F)
plt1 = plt$up+ aes(size=nes)+ggtitle("higher FC when rox in combo than veh")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
plt2 = plt$dn+ aes(size=abs(nes))+ggtitle("higher FC when rox in veh than combo")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
plt1+plt2
```
```{r}
res_df = res_interaction[order(res_interaction$log2FoldChange,decreasing = T), ] %>% as.data.frame()
driving_genes = res_df[genesets$HIF_targets,] %>% filter(log2FoldChange>0.3) %>% rownames() 
```

## per gene
```{r}
hif_scores = cell_line_bulk[driving_genes,] %>% t() %>% as.data.frame()
hif_scores= merge(x = hif_scores,y = metadata_orig,by = 0) %>% column_to_rownames("Row.names")
```

```{r}
hif_scores = cell_line_bulk[driving_genes,] %>% t() %>% as.data.frame()
colnames(hif_scores) = paste0("Gene_",colnames(hif_scores))
hif_scores = merge(x = hif_scores,y = metadata_orig,by = 0) %>% column_to_rownames("Row.names")
hif_scores$condition = factor(hif_scores$condition,levels = c("Veh","Rox","osi_short","osi_short_roxa","osi_persistor","osi_persist_roxa"))
hif_scores = hif_scores %>% filter(condition %in% c("Veh","Rox","osi_persistor","osi_persist_roxa"))
```

```{r}
# --- 2. Convert from 'Wide' to 'Long' Format (Tidy Data) ---
# This is crucial for ggplot2 when plotting different features (genes) at once
df_long <- hif_scores %>%
  pivot_longer(
    cols = starts_with("Gene"), # Selects all columns starting with "Gene"
    names_to = "Gene",           # Creates a new column named 'Gene' for gene names
    values_to = "Expression"     # Creates a new column named 'Expression' for expression values
  )

print("\nData Frame after converting to Long Format:")
print(df_long)

# --- 3. Calculate Summary Statistics (Mean, Standard Deviation, Confidence Interval) ---
df_summary <- df_long %>%
  group_by(condition, Gene) %>% # Group by both Condition and Gene
  dplyr::summarize(
    Mean_Expression = mean(Expression),
    SD_Expression = sd(Expression),
    N_Replicates = n(), # Number of replicates
    # Calculate Standard Error of the Mean (SEM)
    SEM_Expression = SD_Expression / sqrt(N_Replicates),
    # Calculate 95% Confidence Interval (CI)
    # Using approx. 1.96 * SEM for 95% CI (common practice for error bars)
    CI_Lower = Mean_Expression - 1.96 * SEM_Expression, 
    CI_Upper = Mean_Expression + 1.96 * SEM_Expression,
    .groups = 'drop' # Ungroup the results after summarizing
  )

print("\nData Frame with Summary Statistics:")
print(df_summary)

# --- 4. Create the Plots (one per gene) ---

# Loop through each gene and create a plot
unique_genes <- unique(df_long$Gene)

```

```{r fig.height=15, fig.width=15}
p_all_genes <- ggplot(df_long, aes(x = condition, y = Expression, fill = condition)) +
  # Use stat_summary for bars and error bars to calculate means/CIs directly from df_long
  stat_summary(fun = mean, geom = "bar", position = position_dodge(width = 0.9), color = "black") +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", width = 0.2, 
               position = position_dodge(width = 0.9)) + # Error bars based on normal distribution CI
  geom_point(position = position_jitterdodge(jitter.width = 0.05, dodge.width = 0.9), 
             color = "darkblue", size = 1.5, alpha = 0.7) + # Individual replicate points
  labs(
    title = "Gene Expression Across Conditions",
    x = "Condition",
    y = "Expression Level"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  facet_wrap(~ Gene, scales = "free_y") # Create a separate plot for each gene (facet)

print("\nSingle Plot with Facets for All Genes:")
print(p_all_genes)
```
```{r}
library(DESeq2)
dds <- DESeqDataSetFromMatrix(countData = round(cell_line_bulk_orig),
                              colData = metadata_orig,
                              design = ~condition)
dds <- DESeq(dds)

```

```{r}
cpVSop <- results(dds,contrast = c("condition","osi_persist_roxa","osi_persistor"))  %>% as.data.frame()
# cpVSop$padj = p.adjust(cpVSop$pvalue, method = "fdr")
roxaVSctrl <- results(dds,contrast = c("condition","Rox","Veh"))  %>% as.data.frame()
common_genes = intersect(rownames(res_interaction),rownames(cpVSop))
res_interaction_compare = res_interaction[common_genes,]
cpVSop = cpVSop[common_genes,]
roxaVSctrl = roxaVSctrl[common_genes,]
diff_genes = data.frame(row.names = rownames(cpVSop), 
                        cpVSop_FC = 2^cpVSop$log2FoldChange,
                        roxaVSctrl_FC = 2^roxaVSctrl$log2FoldChange,
                        FC_interaction = 2^res_interaction_compare$log2FoldChange) %>% na.omit()
```

```{r  results='asis'}
only_up_in_combo = diff_genes %>% filter(cpVSop_FC>1 & roxaVSctrl_FC>1)

ranked_vec = only_up_in_combo[,"logFC_interaction"]%>% setNames(rownames(only_up_in_combo)) %>% na.omit() %>%  #order by FC
  sort(decreasing = T) # sort



hyp_obj <- hypeR_fgsea(ranked_vec, genesets, up_only = T)
plt = hyp_dots(hyp_obj,merge = F)
plt = plt+ aes(size=nes)+ggtitle("up in comboPersistor")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)

plt
```

```{r}
only_up_in_combo = diff_genes %>% filter(cpVSop_FC<1 & roxaVSctrl_FC<1)

ranked_vec = only_up_in_combo[,"logFC_interaction"]%>% setNames(rownames(only_up_in_combo)) %>% na.omit() %>%  #order by FC
  sort(decreasing = T) # sort



hyp_obj <- hypeR_fgsea(ranked_vec, genesets, up_only = T)
plt = hyp_dots(hyp_obj,merge = F)
plt = plt+ aes(size=nes)+ggtitle("up in comboPersistor")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)

plt
```

```{r}
only_up_in_combo = diff_genes %>% filter(cpVSop_FC<1 & roxaVSctrl_FC>1)

ranked_vec = only_up_in_combo[,"logFC_interaction"]%>% setNames(rownames(only_up_in_combo)) %>% na.omit() %>%  #order by FC
  sort(decreasing = F) # sort



hyp_obj <- hypeR_fgsea(ranked_vec, genesets, up_only = T)
plt = hyp_dots(hyp_obj,merge = F)
plt = plt+ aes(size=nes)+ggtitle("up in comboPersistor")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)

plt
```

```{r}
only_up_in_combo = diff_genes %>% filter(cpVSop_FC>1 & roxaVSctrl_FC<1)

ranked_vec = only_up_in_combo[,"logFC_interaction"]%>% setNames(rownames(only_up_in_combo)) %>% na.omit() %>%  #order by FC
  sort(decreasing = T) # sort



hyp_obj <- hypeR_fgsea(ranked_vec, genesets, up_only = T)
plt = hyp_dots(hyp_obj,merge = F)
plt = plt+ aes(size=nes)+ggtitle("up in comboPersistor")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)

plt
```