---
title: 'bulk RNA-seq analysis' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
editor_options: 
  chunk_output_type: inline
params:
  cell_line: "HCC"
  data_out_dir: "./temp_data/" 
---

```{r}
source("./pipe.R")
input = pipeline$bulk_mar25_HCC$input
output = pipeline$bulk_mar25_HCC$output
```


```{r}
suppressPackageStartupMessages(library(GSEABase))
source_from_github(repositoy = "DEG_functions",version = "0.2.54")
```
#signatures

```{r}
genesets = getGmt(input$genesets) %>% geneIds()
# add senesence signatures to genesets
SASP_signature = c("CCL2", "CCL5", "CCL7", "IL1A", "IL1B", "IL32","SCG2", "INHBA", "INHA", "WNT7A", "CSF2", "TNFRSF11B", "GREM1", "CMTM3")
FRIDMAN_SENESCENCE_UP  = getGmt(input$SENESCENCE) %>% geneIds() %>%  unlist() %>% base::unname()

genesets = c(genesets, list(SASP = SASP_signature,
                        FRIDMAN_SENESCENCE_UP = FRIDMAN_SENESCENCE_UP))

hif_targets =  scan(input$hif_targets, character(), quote = "")
genesets[["HIF_targets"]] = hif_targets


CORDENONSI_YAP = getGmt("./input_data/pathways_from_papers/CORDENONSI_YAP_CONSERVED_SIGNATURE.gmt") %>%
geneIds() %>% unlist()

go_smad = getGmt("./input_data/pathways_from_papers/GOBP_POSITIVE_REGULATION_OF_SMAD_PROTEIN_SIGNAL_TRANSDUCTION.gmt") %>%
geneIds() %>% unlist()


mek_activation = c("DUSP4",
"ELF1",
"LGALS3",
"ANKRD15",
"TRIB2",
"ETV4",
"ETV5",
"MAP2K3",
"SPRY2",
"LZTS1",
"PROS1",
"ZFP106",
"DUSP6",
"PHLDA1",
"S100A6",
"SERPINB1",
"SLCO4A1",
"FXYD5")

compensatory_resistance = c("CLU",
"BASP1",
"COL12A1",
"CRIM1",
"GPR176",
"STAC",
"FZD2",
"COL5A1",
"LOX",
"SERPINE1",
"CD274",
"G0S2",
"IL6")


```

# Create data
```{r}
bulk_Mar25_raw = read.table(
  file = input$rna_counts,
  sep = "\t",
  header = TRUE
) %>% as.data.frame() 

bulk_Mar25_TPM = bulk_Mar25_raw %>%   dplyr::select(!c("Geneid","Chr", "Start", "End", "Strand","Length"))
rownames(bulk_Mar25_TPM) = make.unique(bulk_Mar25_TPM[,"gene_name",drop=T])
bulk_Mar25_TPM  = bulk_Mar25_TPM %>% dplyr::select(!c("gene_name"))
colnames(bulk_Mar25_TPM) = gsub(pattern = ".bam",replacement = "",x = colnames(bulk_Mar25_TPM))


```

```{r}
#adjust sample names
#read xlsx file
library(readxl)
sample_description = readxl::read_xlsx(input$sample_description, sheet = 1) %>% 
  as.data.frame() 

 sample_description = sample_description %>%  mutate(new_name = paste(sample_description$`Group Name\r\n(Required)`,c(1:3),sep = "_")) 


bulk_Mar25_TPM = bulk_Mar25_TPM[,sample_description$`Sample Name`]
colnames(bulk_Mar25_TPM) = sample_description$new_name
colnames(bulk_Mar25_TPM)  = colnames(bulk_Mar25_TPM) %>%  
  gsub(pattern = "_Osi_",replacement = "_osi_short_") %>% 
  gsub(pattern = "_OsiRox_",replacement = "_osi_short_roxa_") %>% 
  gsub(pattern = "_Per_",replacement = "_osi_persistor_") %>% 
  gsub(pattern = "_PerRox_",replacement = "_osi_persist_roxa_") 


```


```{r}
# get cell line
cell_line_bulk = bulk_Mar25_TPM[,startsWith(colnames(bulk_Mar25_TPM),params$cell_line)]
```

```{r}
# create metadata
cell.labels = names(cell_line_bulk)
condition = str_extract(cell.labels, "Veh|osi_short_[1-9]|Rox|osi_short_roxa|osi_persistor|osi_persist_roxa") %>% gsub(pattern = "_[1-9]",replacement = "")
peristor = str_extract(cell.labels, "short|persist")
metadata = data.frame(condition = condition, row.names = colnames(cell_line_bulk))
```

```{r}
library(DESeq2)
dds <- DESeqDataSetFromMatrix(countData = round(cell_line_bulk),
                              colData = metadata,
                              design = ~condition)
```
## PCA
```{r}
nrow(dds)
dds1 <- dds[ rowSums(counts(dds)) >= 3, ] # filter low count genes
nrow(dds1)
```

```{r}
vst = vst(dds1, blind=FALSE)
```
```{r}
library("ggfortify")
PCAdata <- prcomp(t(assay(vst)))
autoplot(PCAdata, data = metadata,colour = "condition",label = FALSE, main=paste(params$cell_line,"PCA")) + 
  scale_color_manual(values = rainbow(6)) 


```
# signatures barplots
```{r}
library(ggpubr)
library(rstatix)

barplot_for_conditions <- function(data, signature, name) {
  scores_df = data[signature,] %>% colMeans() %>% data.frame(row.names = names(.), score =.)
  scores_df = merge(x = scores_df,y = metadata,by = 0) %>% column_to_rownames("Row.names")
  scores_df
  scores_df$condition = factor(scores_df$condition,levels = 
                                 c("Veh","Rox","osi_short","osi_short_roxa","osi_persistor","osi_persist_roxa"))
  summary_df <- scores_df %>%
    group_by(condition) %>%
    dplyr::summarise(
      Mean_Score = mean(score),
      SD_Score = sd(score),
      N = n(),
      SE_Score = SD_Score / sqrt(N)
    )
  
  stat.test <- scores_df %>%
    t_test(score ~ condition) %>%
    add_significance()
  
  my_comparisons <- list( c("Veh", "Rox"), c("Rox","osi_short"), c("osi_short","osi_short_roxa"), c("osi_short_roxa","osi_persistor"), c("osi_persistor","osi_persist_roxa"))
  
  comparisons_df <- do.call(rbind, my_comparisons) %>%
  as.data.frame() %>%
  setNames(c("group1", "group2"))
  
  stat.test <- stat.test %>%
  semi_join(comparisons_df, by = c("group1", "group2")) %>% 
    add_xy_position(step.increase = 0)
  
  p =  ggplot(scores_df, aes(x = condition, y = score)) +
  # Add bars for the means
  geom_bar(data = summary_df, aes(y = Mean_Score), stat = "identity", fill = "skyblue", color = "black", alpha = 0.7) +
  # Add individual data points (jittered to prevent overlap)
  geom_jitter(width = 0.2, height = 0, color = "darkblue", size = 2, alpha = 0.6) +
  # Optional: Add error bars (Standard Error of the Mean)
  geom_errorbar(data = summary_df, aes(y = Mean_Score, ymin = Mean_Score - SE_Score, ymax = Mean_Score + SE_Score),
  width = 0.1, color = "black") +
  # Add titles and customize appearance
  labs(
  title = paste0(params$cell_line,"- Comparison of Mean ",name," Scores"),
  x = "Condition",
  y = name
  ) +
  theme_minimal() + # Minimalist theme
  theme(plot.title = element_text(hjust = 0.5))+  # Center the title
  stat_pvalue_manual(stat.test, label = "p.adj",bracket.shorten = 0.1)
  return(p)
}

```


```{r}
#HIF

barplot_for_conditions(bulk_Mar25_TPM,signature = genesets$HIF_targets,name = "hif_targets")

#senesence
barplot_for_conditions(bulk_Mar25_TPM,signature = SASP_signature,name = "SASP_signature")
barplot_for_conditions(bulk_Mar25_TPM,signature = FRIDMAN_SENESCENCE_UP,name = "FRIDMAN_SENESCENCE_UP")


barplot_for_conditions(bulk_Mar25_TPM,signature = CORDENONSI_YAP,name = "CORDENONSI_YAP")
barplot_for_conditions(bulk_Mar25_TPM,signature =go_smad,name = "go_SMAD_PROTEIN_SIGNAL")
barplot_for_conditions(bulk_Mar25_TPM,signature =genesets$HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION,name = "EMT")


mek_activation = mek_activation[mek_activation %in% rownames(bulk_Mar25_TPM)]
barplot_for_conditions(bulk_Mar25_TPM,signature =mek_activation,name = "mek_activation")
barplot_for_conditions(bulk_Mar25_TPM,signature =compensatory_resistance,name = "compensatory_resistance")
barplot_for_conditions(bulk_Mar25_TPM,signature =c("NDRG1"),name = "EMT")


```
# Heatmap

```{r}

all_genesets_tpm = list()

for (pathway in names(genesets)) {
  pathway_genes = genesets[[pathway]]
  pathway_genes = pathway_genes[pathway_genes %in% rownames(bulk_Mar25_TPM)]
  scores_df = bulk_Mar25_TPM[pathway_genes,] %>% colMeans() %>% data.frame(row.names = names(.), score =.)
  scores_df = merge(x = scores_df,y = metadata,by = 0) %>% column_to_rownames("Row.names")
  scores_df$condition = factor(scores_df$condition,levels = 
                                 c("Veh","Rox","osi_short","osi_short_roxa","osi_persistor","osi_persist_roxa"))
  summary_df <- scores_df %>%
  group_by(condition) %>%
  dplyr::summarise(
    Mean_Score = mean(score),
    SD_Score = sd(score),
    N = n(),
    SE_Score = SD_Score / sqrt(N)
  )
  means = summary_df$Mean_Score  %>% scale() %>% as.vector() %>% setNames(summary_df$condition)
  all_genesets_tpm[[pathway]] = means
}

all_genesets_tpm_df = all_genesets_tpm %>% as.data.frame() %>% t()
```

```{r fig.height=11, fig.width=10}


ht <- Heatmap(all_genesets_tpm_df, show_heatmap_legend = FALSE, column_title= params$cell_line,
              column_order  = colnames(all_genesets_tpm_df))
col_fun = colorRamp2(c(min(all_genesets_tpm_df), max(all_genesets_tpm_df)), c("blue", "red"))

lgd <- Legend(
  title = "TPM mean \nZ score",col_fun = col_fun)

draw(ht, padding = unit(c(2, 2, 2, 75), "mm"))
pushViewport(viewport(x=0.8, y=0.7, width=unit(4, "cm"), height=unit(6, "cm"), just=c("left","center")))
draw(lgd,x = unit(4, "cm"), y = unit(3, "cm"))
popViewport()

```


## HIF per gene
```{r}
hif_scores = cell_line_bulk[genesets$HIF_targets,] %>% t() %>% as.data.frame()
hif_scores= merge(x = hif_scores,y = metadata,by = 0) %>% column_to_rownames("Row.names")
```

```{r}
hif_scores = cell_line_bulk[hif_targets,] %>% t() %>% as.data.frame()
colnames(hif_scores) = paste0("Gene_",colnames(hif_scores))
hif_scores = merge(x = hif_scores,y = metadata,by = 0) %>% column_to_rownames("Row.names")
hif_scores$condition = factor(hif_scores$condition,levels = c("Veh","Rox","osi_short","osi_short_roxa","osi_persistor","osi_persist_roxa"))
hif_scores = hif_scores %>% filter(condition %in% c("Veh","Rox","osi_persistor","osi_persist_roxa"))
```

```{r}
# --- 2. Convert from 'Wide' to 'Long' Format (Tidy Data) ---
# This is crucial for ggplot2 when plotting different features (genes) at once
df_long <- hif_scores %>%
  pivot_longer(
    cols = starts_with("Gene"), # Selects all columns starting with "Gene"
    names_to = "Gene",           # Creates a new column named 'Gene' for gene names
    values_to = "Expression"     # Creates a new column named 'Expression' for expression values
  )

print("\nData Frame after converting to Long Format:")
print(df_long)

# --- 3. Calculate Summary Statistics (Mean, Standard Deviation, Confidence Interval) ---
df_summary <- df_long %>%
  group_by(condition, Gene) %>% # Group by both Condition and Gene
  dplyr::summarize(
    Mean_Expression = mean(Expression),
    SD_Expression = sd(Expression),
    N_Replicates = n(), # Number of replicates
    # Calculate Standard Error of the Mean (SEM)
    SEM_Expression = SD_Expression / sqrt(N_Replicates),
    # Calculate 95% Confidence Interval (CI)
    # Using approx. 1.96 * SEM for 95% CI (common practice for error bars)
    CI_Lower = Mean_Expression - 1.96 * SEM_Expression, 
    CI_Upper = Mean_Expression + 1.96 * SEM_Expression,
    .groups = 'drop' # Ungroup the results after summarizing
  )

print("\nData Frame with Summary Statistics:")
print(df_summary)

# --- 4. Create the Plots (one per gene) ---

# Loop through each gene and create a plot
unique_genes <- unique(df_long$Gene)

```

```{r fig.height=15, fig.width=15}
p_all_genes <- ggplot(df_long, aes(x = condition, y = Expression, fill = condition)) +
  # Use stat_summary for bars and error bars to calculate means/CIs directly from df_long
  stat_summary(fun = mean, geom = "bar", position = position_dodge(width = 0.9), color = "black") +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", width = 0.2, 
               position = position_dodge(width = 0.9)) + # Error bars based on normal distribution CI
  geom_point(position = position_jitterdodge(jitter.width = 0.05, dodge.width = 0.9), 
             color = "darkblue", size = 1.5, alpha = 0.7) + # Individual replicate points
  labs(
    title = "Gene Expression Across Conditions",
    x = "Condition",
    y = "Expression Level"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  facet_wrap(~ Gene, scales = "free_y") # Create a separate plot for each gene (facet)

print("\nSingle Plot with Facets for All Genes:")
print(p_all_genes)
```




## DEG FC {.tabset}
```{r}


dds <- DESeq(dds)
cpVSop <- results(dds,contrast = c("condition","osi_persist_roxa","osi_persistor"))  %>% as.data.frame()
roxaVSctrl <- results(dds,contrast = c("condition","Rox","Veh"))  %>% as.data.frame()
diff_genes = data.frame(row.names = rownames(cpVSop), 
                        cpVSop_FC = cpVSop$log2FoldChange,
                        roxaVSctrl_FC = roxaVSctrl$log2FoldChange, 
                        cpVSop_padj = cpVSop$padj)
```

```{r}
# create 6 breaks between plot limits in log scale and then exponent, otherwise breaks not good
breaks_fun = function(limits){ 
  breaks = exp(-seq(-log(limits[1]), -log(limits[2]), length.out = 6))
  breaks[1] = breaks[1] * 0.95 #adjust extreme ticks to prevent truncation
  breaks[7] = breaks[7] * 1.05
  return(signif(breaks, digits = 2))
}

```



```{r fig.height=6, fig.width=13, results='asis'}
suppressPackageStartupMessages(library(GSEABase))
ranked_vec = cpVSop[,"log2FoldChange"]%>% setNames(rownames(cpVSop)) %>% na.omit() %>%  #order by FC
  sort(decreasing = T) # sort



hyp_obj_combo <- hypeR_fgsea(ranked_vec, genesets, up_only = F)
plt = hyp_dots(hyp_obj_combo,merge = F)
plt1 = plt$up+ aes(size=nes)+ggtitle("up in comboPersistor")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
plt2 = plt$dn+ aes(size=abs(nes))+ggtitle("up in osiPersistors")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
print_tab(plt1+plt2,title = paste(params$cell_line,"cpVSop"))


ranked_vec = roxaVSctrl[,"log2FoldChange"]%>% setNames(rownames(roxaVSctrl)) %>% na.omit() %>% # make named vector
  sort(decreasing = T) # sort 

hyp_obj_rox <- hypeR_fgsea(ranked_vec, genesets, up_only = F)
plt = hyp_dots(hyp_obj_rox,merge = F)
plt1 = plt$up+ aes(size=nes)+ggtitle("up in roxa")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
plt2 = plt$dn+ aes(size=abs(nes))+ggtitle("up in ctrl")+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
print_tab(plt1+plt2,title = paste(params$cell_line,"roxaVSctrl"))
```

# DEG in comboVSosi but not in roxaVSctrl - only up threshold

```{r}
diff_genes = data.frame(row.names = rownames(cpVSop), 
                        cpVSop_FC = 2**cpVSop$log2FoldChange,
                        roxaVSctrl_FC = 2**roxaVSctrl$log2FoldChange,
                        cpVSop_padj = cpVSop$padj,
                        roxaVSctrl_padj = roxaVSctrl$padj)
```

```{r}
library(org.Hs.eg.db)
# significant FC and pval in one but bot significant in other
up_genes_df =  diff_genes %>% filter((cpVSop_FC > 1.3  | cpVSop_FC < 1/1.3) & cpVSop_padj<0.05 & roxaVSctrl_padj >0.05) 
down_genes_df = diff_genes %>% filter((roxaVSctrl_FC > 1.3  | roxaVSctrl_FC < 1/1.3) & roxaVSctrl_padj<0.05 & cpVSop_padj>0.05)
up_genes = up_genes_df %>% rownames()
down_genes = down_genes_df %>% rownames()

gene_descriptions <- AnnotationDbi::select(org.Hs.eg.db, keys = up_genes, columns = "GENENAME", keytype = "SYMBOL")

print_tab(cbind(up_genes_df,gene_description = gene_descriptions$GENENAME),
          title = "up")

gene_descriptions <- AnnotationDbi::select(org.Hs.eg.db, keys = down_genes, columns = "GENENAME", keytype = "SYMBOL")

print_tab(cbind(down_genes_df,gene_description = gene_descriptions$GENENAME),
          title = "down")

```


```{r}
# write a data frame from the list of up and down genes
lst = list(up_genes = up_genes, down_genes = down_genes)
df_from_list <- bind_rows(lapply(lst, function(x) as.data.frame(t(x)))) %>% set_rownames(names(lst)) %>% t()

write.table(df_from_list,
            file = paste0(params$data_out_dir, paste0(basename(output$up_in_persistors))),
            sep = "\t", row.names = FALSE, quote = FALSE)
```

## exclusively up or down GSEA
```{r}
if(length(up_genes)>=3){
  hyp_obj <- hypeR(up_genes, genesets, test = "hypergeometric", fdr=1, plotting=F,
                 background = rownames(bulk_Mar25_TPM))
  plt1 = hyp_dots(hyp_obj,title = paste("up in comboVSosi but not in roxaVSctrl -",params$cell_line))
  print(plt1)
}

if(length(down_genes)>=3){
  hyp_obj <- hypeR(down_genes, genesets, test = "hypergeometric", fdr=1, plotting=F,
                   background = rownames(bulk_Mar25_TPM))
  plt2 = hyp_dots(hyp_obj,title = paste("down in comboVSosi but not in roxaVSctrl - ",params$cell_line))
  print(plt2)
}

```




# scatter plot 
looking for genes in the sides 

```{r}
library(ggrepel)
up_genes_df =  diff_genes %>% filter(cpVSop_FC > 1.2 & roxaVSctrl_FC<1.2 & cpVSop_padj<0.05) 
down_genes_df = diff_genes %>% filter(cpVSop_FC < 0.8 & roxaVSctrl_FC>0.8 & cpVSop_padj<0.05)
diff_genes_signif = rbind(up_genes_df,down_genes_df)

ggplot(diff_genes_signif, aes(x=cpVSop_FC, y=roxaVSctrl_FC)) +
  geom_point() + 
  geom_text_repel(label=rownames(diff_genes_signif))

```


# set up and down thresholds




```{r fig.width=15}
library(org.Hs.eg.db)
fc_threshold =1.2

up_in_combo = diff_genes %>% filter(cpVSop_FC > fc_threshold & cpVSop_padj<0.05) %>% rownames()
down_in_combo = diff_genes %>% filter(cpVSop_FC < 1/fc_threshold & cpVSop_padj<0.05) %>% rownames()
up_in_roxa =  diff_genes %>% filter(roxaVSctrl_FC > fc_threshold & roxaVSctrl_padj<0.05) %>% rownames()
down_in_roxa = diff_genes %>% filter(roxaVSctrl_FC < 1/fc_threshold & roxaVSctrl_padj<0.05) %>% rownames()
all_list = list(up_in_combo = up_in_combo,down_in_combo= down_in_combo, up_in_roxa =up_in_roxa, down_in_roxa =down_in_roxa)
ggvenn::ggvenn(data = all_list)
```


```{r}
greater_than = 1.5
up_only_in_combo = up_in_combo[!up_in_combo %in% c(up_in_roxa)]
up_only_in_combo = up_only_in_combo[diff_genes[up_only_in_combo,"cpVSop_FC"] /
                                      diff_genes[up_only_in_combo,"roxaVSctrl_FC"] > greater_than] #need to be X times FC

only_down_in_combo = down_in_combo[!down_in_combo %in% c(down_in_roxa)]
only_down_in_combo = only_down_in_combo[diff_genes[only_down_in_combo,"cpVSop_FC"] /
                                      diff_genes[only_down_in_combo,"roxaVSctrl_FC"] < 1/greater_than] #need to be X times FC

only_up_in_roxa = up_in_roxa[!up_in_roxa %in% c(up_in_combo)]
only_up_in_roxa = only_up_in_roxa[diff_genes[only_up_in_roxa,"roxaVSctrl_FC"] /
                                      diff_genes[only_up_in_roxa,"cpVSop_FC"] > greater_than] #need to be X times FC

only_down_in_roxa = down_in_roxa[!down_in_roxa %in%  c(down_in_combo)]
only_down_in_roxa = only_down_in_roxa[diff_genes[only_down_in_roxa,"roxaVSctrl_FC"] /
                                      diff_genes[only_down_in_roxa,"cpVSop_FC "] < 1/greater_than] #need to be X times FC

HCC_uniqe_deg_list = list(up_only_in_combo,only_down_in_combo,only_up_in_roxa,only_down_in_roxa)
names(HCC_uniqe_deg_list) = c("up_only_in_combo","only_down_in_combo","only_up_in_roxa","only_down_in_roxa")
```

```{r}
cat("HCC827 exclusive DEG\n\n")
HCC_uniqe_deg_list
```

```{r}
all_fdr_df = data.frame(row.names = names(genesets))
for (i in 1:length(HCC_uniqe_deg_list)) {
  geneset = HCC_uniqe_deg_list[[i]]
  if (length(geneset)>=3) {
    hyp_obj <- hypeR(geneset, genesets, test = "hypergeometric", fdr=1, plotting=F,
               background = rownames(bulk_Mar25_TPM))
    
    all_fdr_df[[names(HCC_uniqe_deg_list)[i]]] = -log10(hyp_obj$data[names(genesets),"fdr"])
    plt = hyp_dots(hyp_obj,title = paste(names(HCC_uniqe_deg_list)[i] ," - ",params$cell_line))
    plt = plt+
      scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =exp(-seq(-log(min(plt$data$fdr)), -log(max(plt$data$fdr)), 
            length.out = 6)) %>% signif(digits = 2))
    print(plt)
  }
}


```

```{r fig.width=9}
all_list = list(up_only_in_combo = up_only_in_combo, only_up_in_roxa =only_up_in_roxa, hif_targets =hif_targets)
ggvenn::ggvenn(data = all_list)+ggtitle(params$cell_line)
```

```{r}
# write
df_from_list <- bind_rows(lapply(HCC_uniqe_deg_list, function(x) as.data.frame(t(x)))) %>% set_rownames(names(HCC_uniqe_deg_list)) %>% t()

write.table(df_from_list,
            file = paste0(params$data_out_dir, "one_threshold_exclusive_DEG_HCC.tsv"),
            sep = "\t", row.names = FALSE, quote = FALSE)
```

# FDR heatmap

```{r fig.height=10, fig.width=8}
library(circlize)
library(grid)
library(ComplexHeatmap)
all_fdr_df =all_fdr_df[,c("up_only_in_combo")]


threshold <- -log10(0.05)  

col_fun <- colorRamp2(
  c(0, threshold - 0.01, threshold, max(all_fdr_df, na.rm=TRUE)),
  c("grey80", "grey80", "white", "red")
)

lgd <- Legend(
  title = "-log10(FDR)",
  col_fun = col_fun,
  direction = "vertical",
  labels = c("0","-log10(0.05)",seq(from = threshold, to = max(all_fdr_df), by = 1)),
  at =c(-2,threshold,seq(from = threshold, to = max(all_fdr_df), by = 1))
)

ht <- Heatmap(all_fdr_df,col = col_fun, row_names_gp = gpar(fontsize = 9),cluster_columns = F, show_heatmap_legend = FALSE, column_title= params$cell_line)

draw(ht, padding = unit(c(2, 2, 2, 50), "mm"))
pushViewport(viewport(x=0.8, y=0.7, width=unit(4, "cm"), height=unit(6, "cm"), just=c("left","center")))
draw(lgd)
popViewport()


```

# FC heatmaps

```{r fig.height=6, fig.width=9}
library(scales)
library(ggdendro)
library(patchwork)


df = diff_genes[hif_targets,] %>% rownames_to_column("gene") %>% na.omit()

df_long <- df %>%
  pivot_longer(
    cols = -gene,
    names_to = c("condition", ".value"),
    names_pattern = "(.+)_(FC|padj)"
  )
df_long = df_long %>% mutate(group = case_when(
  gene %in% HCC_uniqe_deg_list$up_only_in_combo ~ "up_only_in_combo",
  gene %in% HCC_uniqe_deg_list$only_down_in_combo ~ "only_down_in_combo",
  gene %in% HCC_uniqe_deg_list$only_up_in_roxa ~ "only_up_in_roxa",
  gene %in% HCC_uniqe_deg_list$only_down_in_roxa ~ "only_down_in_roxa",
  .default = "non-unique"
)) %>%
  mutate(sig_label = case_when(
    padj < 0.001 ~ "***",
    padj < 0.01  ~ "**",
    padj < 0.05  ~ "*",
    TRUE         ~ "ns"
  ))

fc_mat <- df[, c("cpVSop_FC", "roxaVSctrl_FC")]
rownames(fc_mat) <- df$gene
d <- dist(fc_mat)
hc <- hclust(d)
dend_data <- ggdendro::dendro_data(hc)

gene_order <- rownames(fc_mat)[hc$order]
df_long$gene <- factor(df_long$gene, levels = gene_order)

dend_plot <- ggplot(ggdendro::segment(dend_data)) +
  geom_segment(aes(x = y, xend = yend, y = x, yend = xend)) +  # change axis
  scale_y_continuous(breaks = seq_along(gene_order), labels = gene_order, expand = c(0.01, 0.01)) +
  scale_x_reverse() +  
  theme_void() +
  theme(plot.margin = margin(t = 10, r = 0, b = 10, l = 10))

dot_plot = ggplot(df_long, aes(x = condition, y = gene)) +
  geom_point(aes(size = -log10(padj), color = FC)) +
  scale_color_gradient2(
    low = "blue", mid = "white", high = "red", midpoint = 0, limits = c(-max(df_long$FC), max(df_long$FC))
  ) +
  scale_size(range = c(2, 6)) +
  theme_minimal() +
  labs(
    title = "Dotplot: FC by Color, Significance by Size",
    x = "Condition",
    y = "Gene",
    color = "FC",
    size = "-log10(FDR)"
  ) +
  theme(axis.text.y = element_text(size = 6))+
    geom_tile(data = distinct(df_long[, c("gene", "group")]),
            aes(x = "group", fill = group),
            width = 0.1, height = 0.8) +
  scale_x_discrete(limits = c("group", unique(df_long$condition)))

final_plot <- dend_plot + dot_plot + plot_layout(ncol = 2, widths = c(1, 4))
final_plot
library(ggtext)
group_colors <- c(
  "up_only_in_combo" = "lightgreen",
  "only_down_in_combo" = "steelblue",
  "only_up_in_roxa" = "darkgreen",
  "only_down_in_roxa" = "darkblue",
  "non-unique" = "black"

)

gene_colors <- df_long %>%
  select(gene, group) %>%
  distinct() %>%
  mutate(col = group_colors[group]) %>%
  { setNames(.$col, .$gene) }

label_html <- function(x) {
  sprintf(
    "<span style='color:%s'>%s</span>",
    gene_colors[x],  # לוקח את הצבע המתאים
    x                # ושם הגן עצמו
  )
}

colors = df_long$gene %>% unique()
ggplot(df_long, aes(x = gene, y = FC, fill = condition)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(x = "Gene", y = "Fold Change", title = "Fold Change per Gene") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
   geom_hline(yintercept = fc_threshold, linetype = "dashed", color = "black")+
  scale_x_discrete(
    labels = label_html
  ) +
  theme(
    axis.text.x = element_markdown(angle = 45, hjust = 1),  # מאפשר HTML/CSS בתוויות
    legend.position = "bottom"
  )+
   geom_text(aes(label = sig_label),
            position = position_dodge(width = 0.9),
            vjust = -0.5, size = 4)

```











