---
title: "R Notebook"
author: "Avishai Wizel"
date: '`r Sys.time()`'

output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---

```{r}
# Get input and output
source("./pipe.R")
input = pipeline$xeno_clustering$input
output = pipeline$xeno_clustering$output
```

```{r}
library(Seurat)
library(qs2)
library(ggplot2)
library(dplyr)
```

```{r}
xeno <- qs_read(input$xeno)

```

```{r}
p <- DimPlot(object = xeno, reduction = "umap", pt.size = 0.1, label = F)
p
```
```{r}
svg(filename = params$data_out_dir %s+% "xeno_clusters.svg")
p
dev.off()

```

```{r}
p <- DimPlot(object = xeno, reduction = "umap", pt.size = 0.1, label = F,group.by = "treatment")
p
```
```{r}
svg(filename = params$data_out_dir %s+% "xeno_treatment_UMAP.svg")
p
dev.off()

```

```{r}
p <- DimPlot(object = xeno, reduction = "umap", pt.size = 0.1, label = F,group.by = "orig.ident")+ggtitle("")
p
```

#KRT 5- KRT17+
```{r}

data = xeno %>% FetchData(vars = c("KRT5","KRT17"))  %>% mutate(KRT5_state = ifelse(KRT5>1,"high","low"),
                                                KRT17_state = ifelse(KRT17>1,"high","low")) 

xeno = AddMetaData(object = xeno,metadata = data[,c("KRT5_state","KRT17_state"),drop=F])
xeno$KRT_quadrant <- paste0("KRT5_", xeno$KRT5_state, "/KRT17_", xeno$KRT17_state)
table(xeno$KRT_quadrant)
DimPlot(xeno, group.by = "KRT_quadrant", cols = c(
  "KRT5_low/KRT17_low"   = "lightgrey", 
  "KRT5_high/KRT17_low"  = "#ff0000", # אדום
  "KRT5_low/KRT17_high"  = "#00ff00", # ירוק (מה שחיפשת)
  "KRT5_high/KRT17_high" = "#ffcc00"  # צהוב/כתום
)) + ggtitle("KRT5/KRT17 Co-expression States")
```
```{r}
plot_data <- xeno@meta.data %>%
  group_by(treatment, KRT_quadrant) %>% 
  summarise(count = n()) %>%
  mutate(percentage = count / sum(count) * 100)


ggplot(plot_data, aes(x = treatment, y = percentage, fill = KRT_quadrant)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = c(
    "KRT5_low/KRT17_low"   = "lightgrey", 
    "KRT5_high/KRT17_low"  = "#ff0000", # אדום
    "KRT5_low/KRT17_high"  = "#00ff00", # ירוק
    "KRT5_high/KRT17_high" = "#ffcc00"  # צהוב
  )) +
  theme_minimal() +
  labs(y = "Percentage of Cells (%)", x = "Time Point", fill = "KRT Status") +
  ggtitle("Distribution of KRT5/KRT17 Subsets over Time")
```
```{r fig.height=8, fig.width=6}
#per model
plot_data <- xeno@meta.data %>%
  group_by(treatment, orig.ident, KRT_quadrant) %>% 
  summarise(count = n()) %>%
  mutate(percentage = count / sum(count) * 100)


ggplot(plot_data, aes(x = treatment, y = percentage, fill = KRT_quadrant)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = c(
    "KRT5_low/KRT17_low"   = "lightgrey", 
    "KRT5_high/KRT17_low"  = "#ff0000", # אדום
    "KRT5_low/KRT17_high"  = "#00ff00", # ירוק
    "KRT5_high/KRT17_high" = "#ffcc00"  # צהוב
  )) +
  facet_grid(orig.ident ~ .) +
  theme_minimal() +
  labs(y = "Percentage of Cells (%)", x = "Time Point", fill = "KRT Status") +
  ggtitle("Distribution of KRT5/KRT17 Subsets over Time")
```

