---
title: 'Xeno Run SiPSiC' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  # html_notebook: 
  #   code_folding: hide
  #   toc: true
  #   toc_collapse: true
  #   toc_float:
  #     collapsed: false
  #   number_sections: true
  #   toc_depth: 1
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 

editor_options: 
  chunk_output_type: inline
---



```{r}
if (interactive()) {
  source("./pipe.R")
  input = get_input(get_current_path())
  output = get_output(get_current_path())
}
```

# Functions

```{r}
library(stringi)
library(reticulate)
library(ggplotify)
suppressPackageStartupMessages(library(GSEABase))
library(SiPSiC)
source_from_github(repositoy = "DEG_functions",version = "0.2.47")
source_from_github(repositoy = "sc_general_functions",version = "0.1.34",script_name = "functions.R")


```

# Data


```{r}
xeno <- qs::qread(input$xeno)
hallmark_genesets = getGmt(paste0(input$genesets))
hif_targets = scan(input$hif_targets, character(), quote = "")
# add hif targets to genesets
hif_targets <- list(hif_targets = GeneSet(geneIds = hif_targets, setName = "hif_targets"))
genesets <- c(hallmark_genesets, hif_targets)
names(genesets) = c(names(hallmark_genesets), names(hif_targets))
```


# DE pathways

```{r}
calculatePathwayScores <- function(pathwayToScore, countsMatrix) {
  pathwayName <- pathwayToScore@setName
  message(pathwayName)
  pathwayGenes <- pathwayToScore@geneIds
  pathwayScoresObject <- getPathwayScores(countsMatrix, pathwayGenes)
  suppressWarnings(
    if (is.null(pathwayScoresObject)) {
      return(NA)
    }
  )
  return(pathwayScoresObject$pathwayScores)
}
```



```{r}
pathwayScoreLists <- lapply(X = genesets@.Data, calculatePathwayScores, xeno@assays$RNA@data %>% expm1())
names(pathwayScoreLists) = names(genesets)
pathwayScoreLists <- pathwayScoreLists[!is.na(pathwayScoreLists)] #remove NA pathways
pathwayScoresMatrix <- as.data.frame(do.call("rbind", pathwayScoreLists))
```

```{r}
# save
saveRDS(object = pathwayScoresMatrix,file = paste0(params$data_out_dir,basename(output$sipsic_matrix)))
```


# session info
<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName"> Show/Hide </button>  
<div id="BlockName" class="collapse">  
```{r}
devtools::session_info()
```

</div>