---
title: 'SiPSiC'
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 

editor_options: 
  chunk_output_type: inline
---

```{r}
# Get input and output
source("./pipe.R")
input = pipeline$xeno_sipsic_analysis$input
output = pipeline$xeno_sipsic_analysis$output
```

# Functions

```{r}
library(qs2)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringi)
library(reticulate)
library(ggplotify)
library(grid)
library(ComplexHeatmap)
library(ggpubr)
library(SourceFromGithub)
library(data.table)
library(tibble)
source_from_github(repositoy = "DEG_functions",version = "0.2.47")
source_from_github(repositoy = "sc_general_functions",version = "0.1.35",script_name = "functions.R")

```

# Data


```{r}
xeno <- qs_read(input$xeno)
```


# DE pathways


```{r}
pathwayScoresMatrix = readRDS(file = input$sipsic_matrix)
xeno[["sipsic"]] = CreateAssayObject(counts = pathwayScoresMatrix)

```



```{r}
xeno = SetIdent(xeno, value = "treatment")
pathways_names = gsub(rownames(pathwayScoresMatrix), pattern = "_", replacement = "-")


logFC_df = data.frame(row.names = pathways_names)
fdr_df = data.frame(row.names = pathways_names)

for (model in unique(xeno$orig.ident)) {
  model_data = subset(xeno, subset = orig.ident == model)
  pathway_markers = FindMarkers(
    object = model_data,
    ident.1 = "OSI",
    ident.2 = "NT",
    assay = "sipsic",
    slot = "counts",
    logfc.threshold = 0,
    densify = T,
    pseudocount.use = 0.001,
    features = pathways_names
  )
  
  avg_log2FC = pathway_markers[pathways_names, "avg_log2FC", drop = F]
  colnames(avg_log2FC) = model
  pathway_markers$fdr = p.adjust(pathway_markers$p_val,method = "fdr",n = length(rownames(model_data@assays$sipsic)))
  fdr = pathway_markers[pathways_names, "fdr", drop = F]
  colnames(fdr) = model
  
  logFC_df = cbind(logFC_df, avg_log2FC)
  fdr_df = cbind(fdr_df, fdr)
}
fdr_df_raw = fdr_df
fdr_df[fdr_df > 0.05]  = 1 #remove non significant values

fdr_df = apply(fdr_df, 1:2, \(x) format(x, digits=1)) %>% as.data.frame() #round p values 
fdr_df[fdr_df == "1"] = ""

fdr_df[fdr_df == "0"] = paste0("<",format(.Machine$double.xmin,digits = 1))
# replace p=0 with p<min float

```


```{r}
fwrite(logFC_df,file = params$data_out_dir %s+% "xeno_sipsic_hallmarks_logFC.tsv",sep = "\t",row.names = T)
fwrite(fdr_df,file = params$data_out_dir %s+% "xeno_sipsic_hallmarks_fdr_df.tsv",sep = "\t",row.names = T)
```



```{r}
# color row name if consistent across patients/models
colors= c()
for (row_num in 1:nrow(logFC_df)) {
  row = logFC_df[row_num,]
  if (sum(row > 0.15)  >= 4) { # if at least x values are more than 0.1 log2FC
    colors <- c(colors, "red")
  }
  else if (sum(row < -0.15)  >= 4) {
    colors <- c(colors, "blue")
  }
  else{colors <- c(colors, "black")}
}

```

```{r fig.height=8, fig.width=8}
col_fun = circlize::colorRamp2(c(-1.5, 0, 1.5), c("royalblue4", "white", "red"))
p = ComplexHeatmap::Heatmap(logFC_df,  row_names_gp = gpar(fontsize = 8,col =colors), clustering_method_rows = "average",show_heatmap_legend = F,col = col_fun, clustering_distance_rows = "euclidean", cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(fdr_df[i, j], x, y, gp = gpar(fontsize = 8))
}
)

lgd = Legend(title = "log2 Fold change", at = c(-1.5, 0, 1.5),
 col_fun = col_fun)


```

```{r fig.height=8, fig.width=10}
# draw(p %v% known_p, padding = unit(c(2, 2, 2, 50), "mm"))
draw(p, padding = unit(c(2, 2, 2, 50), "mm"))
draw(lgd,x = unit(0.85, "npc"), y = unit(0.78, "npc"))
```

```{r fig.height=7, fig.width=8}

svg( paste0(params$data_out_dir, "xeno_sipsic_heatmap.svg"), width = 8, height = 7)
draw(p, padding = unit(c(2, 2, 2, 50), "mm"))
draw(lgd,x = unit(0.85, "npc"), y = unit(0.78, "npc"))
dev.off()


```

```{r}
#show only consistant
logFC_df_consistant = logFC_df[colors =="blue" | colors == "red",]
fdr_df_consistant = fdr_df[colors =="blue" | colors == "red",]
colors_consistant = colors[colors =="blue" | colors == "red"]
p = ComplexHeatmap::Heatmap(
  logFC_df_consistant,
  name = "log2FC on/pre",
  row_names_gp = gpar(fontsize = 8, col = colors_consistant),
  clustering_method_rows = "average",
  show_heatmap_legend = T,
  col = col_fun,
  clustering_distance_rows = "euclidean",
  cell_fun = function(j, i, x, y, width, height, fill) {
    grid.text(fdr_df_consistant[i, j], x, y, gp = gpar(fontsize = 8))
  })
# p %v% known_p
p
```



# Heatmap with asterisks



```{r}
# Description
fdr_df_sig = fdr_df_raw
fdr_df_sig[] <- lapply(fdr_df_sig, as.numeric)

convert <- function(vec) {
  symnum(vec, corr = FALSE, na = FALSE, cutpoints = c(0, 
    0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")) %>% as.character()
} 

fdr_df_sig[] = apply(fdr_df_sig, MARGIN = 1, FUN = convert)
```


```{r fig.height=7, fig.width=8}
col_fun = circlize::colorRamp2(c(-1, 0, 1), c("blue", "white", "red"))
p = ComplexHeatmap::Heatmap(logFC_df, name = "log2FC on/pre", col = col_fun,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(fdr_df_sig[i, j], x, y, gp = gpar(fontsize = 8))
}, row_names_gp = gpar(fontsize = 8,col =colors), clustering_method_rows = "average", clustering_distance_rows = "euclidean")
p
```

# Heatmap
```{r fig.height=15}
DefaultAssay(xeno) = "sipsic"
data = FetchData(object = xeno, vars = c(pathways_names,"orig.ident"))
data[] <- data %>%  group_by(orig.ident) %>% mutate(across(is.numeric, ~ as.numeric(scale(.)))) %>% ungroup() 
data = data %>% select(-orig.ident) 
data = data %>% t() %>% as.data.frame()

annotation_data = FetchData(object = xeno, vars = c("orig.ident","treatment")) %>% dplyr::arrange(orig.ident,treatment)
column_ha = HeatmapAnnotation(df = annotation_data[,2])
data = data[,rownames(annotation_data)] #order data like annotation
data = na.omit(data)
p = ComplexHeatmap::Heatmap(
  data,
  show_column_names = F,
  row_names_gp = grid::gpar(fontsize = 7),
  cluster_rows = T,
  top_annotation = column_ha,
  name = "Z-score expression",use_raster = F,cluster_columns = F,column_split   = annotation_data$orig.ident,
  column_gap = unit(2, "mm"), border = TRUE,show_parent_dend_line = FALSE, show_column_dend = FALSE,cluster_column_slices = F
)
  
p
```

```{r fig.height=15}
# heatmap with clutering per model and time point
DefaultAssay(xeno) = "sipsic"
data = FetchData(object = xeno, vars = c(pathways_names,"orig.ident"))
data[] <- data %>%  group_by(orig.ident) %>%
  mutate(across(is.numeric, ~ as.numeric(scale(.)))) %>% ungroup() # scale per model
data = data %>% select(-orig.ident) # remove ident var
data = data %>% t() %>% as.data.frame()

annotation_data = FetchData(object = xeno, vars = c("orig.ident","treatment")) %>% dplyr::arrange(orig.ident,treatment)
column_ha = HeatmapAnnotation(Treatment = annotation_data[,2], #set annotation
                              col = list(Treatment = c("NT" = "red", "OSI" = "green", "res" = "blue"))) 
data = data[,rownames(annotation_data)] #order data like annotation
data = na.omit(data)
column_split = paste(annotation_data$orig.ident,annotation_data$treatment,sep = "\n") #split by ident+tp
column_names = unique(column_split) %>% gsub(pattern = "119\nOSI",replacement = "      119\n      OSI") #adujst location to avoid overlap
DefaultAssay(xeno) = "RNA" #make RNA default again

p = ComplexHeatmap::Heatmap(
  data,
  show_column_names = F,
  row_names_gp = grid::gpar(fontsize = 10),
  cluster_rows = T,
  top_annotation = column_ha,
  name = "Z-score expression",use_raster = F,cluster_columns = T,column_split = column_split,
  column_title = column_names,
  column_gap = unit(2, "mm"), border = TRUE,show_parent_dend_line = FALSE, show_column_dend = F,cluster_column_slices = F)

  
p
```

```{r fig.width=10}
# only nmf programs
for (patient_name in unique(xeno$orig.ident)) {
  
  patient_data = subset(xeno,subset = orig.ident == patient_name)
  pathways_names = c("HALLMARK-INTERFERON-ALPHA-RESPONSE","HALLMARK-TNFA-SIGNALING-VIA-NFKB", "HALLMARK-HYPOXIA","HALLMARK-E2F-TARGETS" )
  
  DefaultAssay(patient_data) = "sipsic"
  data = FetchData(object = patient_data, vars = c(pathways_names))
  data[] <- data %>% 
    mutate(across(everything(), ~ as.numeric(scale(.))))  # scale per pathway
  data = data %>% t() %>% as.data.frame()
  
  annotation_data = FetchData(object = patient_data, vars = c("treatment")) %>% dplyr::arrange(treatment)
  column_ha = HeatmapAnnotation(Treatment = annotation_data[,1], #set annotation
                                col = list(Treatment = c("NT" = "red", "OSI" = "green", "res" = "blue"))) 
  data = data[,rownames(annotation_data)] #order data like annotation
  data = na.omit(data)
  DefaultAssay(xeno) = "RNA" #make RNA default again
  
  p = ComplexHeatmap::Heatmap(
    data,
    show_column_names = F,
    row_names_gp = grid::gpar(fontsize = 10),
    cluster_rows = T,
    top_annotation = column_ha,
    name = "Z-score expression",use_raster = F,cluster_columns = T,column_split = annotation_data$treatment,
    column_gap = unit(2, "mm"), border = TRUE,show_parent_dend_line = FALSE, show_column_dend = T,cluster_column_slices = F,column_title = patient_name)
  
    
  print(p)
}
```


# Correlation

```{r}
# Description
names = c("H_INFa", "H_TNFa_NFKb", "H_HYPOXIA", "H_E2F")
combinations <- combn(names, 2, FUN = function(x) paste(x, collapse = " ~ ")) #create every combination
all_patients_data = data.frame(pathways = combinations)

for (patient_name in unique(xeno$orig.ident)) {
  
  patient_data = subset(xeno, subset = orig.ident == patient_name)
  pathways_names = c(
    "HALLMARK-INTERFERON-ALPHA-RESPONSE",
    "HALLMARK-TNFA-SIGNALING-VIA-NFKB",
    "HALLMARK-HYPOXIA",
    "HALLMARK-E2F-TARGETS"
  )
  
  DefaultAssay(patient_data) = "sipsic"
  data = FetchData(object = patient_data, vars = c(pathways_names))
  
  data = na.omit(data)
  DefaultAssay(xeno) = "RNA" #make RNA default again
  colnames(data) = c("H_INFa", "H_TNFa_NFKb", "H_HYPOXIA", "H_E2F")
  data = cor(data)
  library("reshape2")
  data = reshape2::melt(as.matrix(data),varnames = c("pathway_1","pathway_2"),value.name = "correlation") %>% #to long format
    filter(!pathway_1 == pathway_2) %>%  # remove self correlation
    mutate(pathways = paste0(pathway_1," ~ ",pathway_2)) %>%  
    select(pathways,correlation) 
  colnames(data)[2] = patient_name
    
  all_patients_data = left_join(x = all_patients_data,y = data,by = c("pathways" = "pathways")) # add patient data to all_patients_data
  

}

all_patients_data = all_patients_data %>% column_to_rownames("pathways")

#plot:
col_fun = circlize::colorRamp2(c(-1, 0, 1), c("blue", "white", "red"))
p = ComplexHeatmap::Heatmap(all_patients_data, name = "Pearson", col = col_fun,
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(round(all_patients_data[i, j],3), x, y, gp = gpar(fontsize = 8))
}, row_names_gp = gpar(fontsize = 8), clustering_method_rows = "average", clustering_distance_rows = "euclidean")
p
```

```{r}

for (patient_name in c("1109","1071")) {
  patient_data = subset(xeno, subset = orig.ident == patient_name)
  pathways_names = c(
    "HALLMARK-INTERFERON-ALPHA-RESPONSE",
    "HALLMARK-TNFA-SIGNALING-VIA-NFKB",
    "HALLMARK-HYPOXIA",
    "HALLMARK-E2F-TARGETS"
  )
  
  DefaultAssay(patient_data) = "sipsic"
  data = FetchData(object = patient_data, vars = c(pathways_names,"treatment"))
  colnames(data) = gsub(colnames(data), pattern = "-", replacement = "_") # replace - with _
  p = ggscatter(data, x = "HALLMARK_TNFA_SIGNALING_VIA_NFKB", y = "HALLMARK_HYPOXIA",
                add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method = "pearson",
                main = c(patient_name,"orrelation"))
  print(p)


  p1 = 
   ggplot(data, aes(x = treatment, y = HALLMARK_HYPOXIA)) +
    stat_summary(fun = mean)+
    geom_jitter() +
    geom_text(stat = "summary", aes(label = round(..y.., 2)),nudge_y = 0.2) +
    theme_minimal() +
    labs(title =paste(patient_name, "HALLMARK_HYPOXIA in each treatment"), x = "Treatment", y = "HALLMARK_HYPOXIA")+ 
    geom_boxplot(aes(group = treatment), fill = "white", width = 0.2, outlier.shape = NA)  
  print(p1)
  

  p2 = 
  ggplot(data, aes(x = treatment, y = HALLMARK_TNFA_SIGNALING_VIA_NFKB)) +
    stat_summary(fun = mean)+
    geom_jitter() +
    geom_text(stat = "summary", aes(label = round(..y.., 2)),nudge_y = 0.2) +
    theme_minimal() +
    labs(title = paste(patient_name,"HALLMARK_TNFA_SIGNALING_VIA_NFKB in each treatment"), x = "Treatment", y = "HALLMARK_TNFA_SIGNALING_VIA_NFKB")+ 
    geom_boxplot(aes(group = treatment), fill = "white", width = 0.2, outlier.shape = NA)
  
  print(p2)
}

```




