---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.Date()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
---

## Parameters

```{r warning=FALSE}
suffix = ""
data_to_read = ""
```


## functions

```{r warning=FALSE}
library(stringi)
library(ggplotify)
source_from_github(repositoy = "DEG_functions",version = "0.2.54")
```

## Data

```{r}
xeno = readRDS("./Data/10x_xeno_1000.Rds")
lung = readRDS("./Data/lung_cancercells_withTP_onlyPatients.rds")
lung_patients = lung$patient.ident %>% unique() %>% as.character()
lung_patients_filtered = lung_patients[!(lung_patients %in% c("X1055new","X1099"))] #remove patients with less then 100 cells
lung = subset(x = lung,subset = patient.ident %in% lung_patients_filtered)
```



## Xeno DEG

```{r}
xeno = SetIdent(object = xeno,value = "treatment")
xeno = FindVariableFeatures(object = xeno,nfeatures = 5000)
deg_df = FindMarkers(object = xeno,ident.1 = "NT",ident.2 = "OSI",densify = T,mean.fxn = function(x) {
  return(log(x = rowMeans(x = x) + 1, base = 2))
},features = VariableFeatures(xeno), logfc.threshold=0, min.pct=0)

p = volcano_plot(deg_df,top_genes_text = 5,ident1 = "NT",ident2 = "OSI",fc_cutoff = 1.5)+coord_cartesian(clip = "off")
p
```
```{r}
saveRDS(object = as.grob(p),file = "./Figures/xeno_DEG.rds")
```

## Xeno DEG regress patients

```{r}
xeno = SetIdent(object = xeno,value = "treatment")
xeno = FindVariableFeatures(object = xeno,nfeatures = 5000)
deg_df = FindMarkers(object = xeno,ident.1 = "NT",ident.2 = "OSI",densify = T,mean.fxn = function(x) {
  return(log(x = rowMeans(x = x) + 1, base = 2))
},features = VariableFeatures(xeno), logfc.threshold=0, min.pct=0,test.use = "LR",latent.vars = "orig.ident")

p = volcano_plot(deg_df,top_genes_text = 5,ident1 = "NT",ident2 = "OSI",fc_cutoff = 1.5)+coord_cartesian(clip = "off")
p
```


## Xeno DEG per patient

```{r fig.height=8, fig.width=14}
patients_list = xeno$orig.ident %>% unique()
xeno = SetIdent(object = xeno,value = "treatment")
p_list = list()
for (patient in patients_list) {
  patient_data = subset(x = xeno,subset = orig.ident == patient)
  patient_data = FindVariableFeatures(object = patient_data,nfeatures = 5000)
  deg_df = FindMarkers(object = patient_data,ident.1 = "NT",ident.2 = "OSI",densify = T,mean.fxn = function(x) {
    return(log(x = rowMeans(x = x) + 1, base = 2))
  },features = VariableFeatures(patient_data), logfc.threshold=0, min.pct=0)
  
  p = volcano_plot(deg_df,top_genes_text = 5,ident1 = "NT",ident2 = "OSI",fc_cutoff = 1.5,title = paste("Model",patient))
  p_list[[patient]] = p
}

p_list = lapply(p_list,FUN = function(x) { #fix cropped edges
  x = x+ 
   coord_cartesian(clip = "off")
})


p = ggarrange(plotlist = p_list,common.legend = T,legend = "right")
p
```


```{r}
saveRDS(object = as.grob(p),file = "./Figures/xeno_DEG_per_patient.rds")
```







