---
title: 'Create data for CNMF' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 

editor_options: 
  chunk_output_type: inline
---

```{r}
source("./pipe.R")
input = pipeline$xeno_cnmf_preprocess$input
output = pipeline$xeno_cnmf_preprocess$output
```



```{r}
reticulate::use_condaenv(pipeline$xeno_cnmf_preprocess$params$cnmf_env,required = T)
reticulate::py_config() # if you see that r-cnmf_dev has not been loaded, restart/terminate r and try again, DO NOT load reticulate before.
```

# Functions

```{r warning=FALSE}
library(qs2)
library(reticulate)
library(Seurat)
```

# Data
```{r}
xeno <- qs_read(input$xeno)
xeno = DietSeurat(xeno)
```



## Convert seurat to scanpy
```{r}
sc <- import('scanpy', convert = FALSE)
gene_expression = t(as.matrix(GetAssayData(xeno,slot='counts'))) 
gene_expression = gene_expression[,colSums(gene_expression) != 0] #remove genes with 0 expression in all cells


xeno_filtered  = xeno[colnames(gene_expression),]
adata <- sc$AnnData(
  X   = gene_expression,
  obs = xeno_filtered@meta.data,
  var = GetAssay(xeno_filtered)@meta.features
)
rm(gene_expression)
rm(gene_expression)

gc()
```




```{python}
import os
import scanpy as sc
adata = r.adata
adata.var['highly_variable'] = adata.var['vst.variable'] # rename seurat var genes to scanpy var genes
adata.write_h5ad(r.params['data_out_dir'] + os.path.basename((r.output['xeno_counts_filtered'])))
```



# session info
<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName"> Show/Hide </button>  
<div id="BlockName" class="collapse">  
```{r}
devtools::session_info()
```

</div>