---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 

editor_options: 
  chunk_output_type: inline
---

```{r}
if (interactive()) {
  source("./pipe.R")
  input = get_input(get_current_path())
  output = get_output(get_current_path())
}
```



```{r}
reticulate::use_condaenv("C:/Users/avishaiw.EKMD/AppData/Local/r-miniconda/envs/cnmf",required = T)
reticulate::py_config() # if you see that r-cnmf_dev has not been loaded, restart/terminate r and try again, DO NOT load reticulate before.
```

# Functions

```{r warning=FALSE}
```

# Data

```{r}
xeno <- qs::qread(input$xeno)
xeno = DietSeurat(object = xeno)
gc()
```


## Convert seurat to scanpy
```{r}
library(reticulate)
sc <- import('scanpy', convert = FALSE)
gene_expression = t(as.matrix(GetAssayData(xeno,slot='counts'))) 
gene_expression = gene_expression[,colSums(gene_expression) != 0] #remove genes with 0 expression in all cells

xeno_filtered  = xeno[colnames(gene_expression),]
adata <- sc$AnnData(
  X   = gene_expression,
  obs = xeno_filtered[[]],
  var = GetAssay(xeno_filtered)[[]]
)
rm(gene_expression)
gc()
```

```{python}
import scanpy as sc
import os
adata = r.adata
adata.var['highly_variable'] = adata.var['vst.variable'] # rename seurat var genes to scanpy var genes
adata.write_h5ad(r.params['data_out_dir'] + os.path.basename((r.output['xeno_counts_filtered'])))
```



# session info
<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName"> Show/Hide </button>  
<div id="BlockName" class="collapse">  
```{r}
devtools::session_info()
```

</div>