---
title: '05_models_cnmf_analysis_k5' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 

editor_options: 
  chunk_output_type: inline
---


```{r}
#Get input and output
source("./pipe.R")
input = pipeline$models_programs_analysis$input
output = pipeline$models_programs_analysis$output
input_params = pipeline$models_programs_analysis$params
```


# Functions
```{r}
name <- function(variables) {
  
}
```




```{r warning=FALSE}
library(ggplotify)
library(stringi)
library(reticulate)
suppressPackageStartupMessages(library(GSEABase))
source_from_github(repositoy = "DEG_functions",version = "0.2.53")
source_from_github(repositoy = "cNMF_functions",version = "0.4.25",script_name = "cnmf_functions_V3.R")
source_from_github(repositoy = "sc_general_functions",version = "0.1.34",script_name = "functions.R")

```


# Data

```{r}
xeno <- qs::qread(input$xeno)
genesets = getGmt(input$genesets)  %>% geneIds()
hif_targets =  scan(input$hif_targets, character(), quote = "")
genesets[["HIF_targets"]] = hif_targets
xeno_cell_usage = readRDS(input$xeno_cell_usage)
gep_scores = readRDS(input$gep_scores)
```



```{r fig.height=6, fig.width=14}

df = FetchData(xeno,vars = c("treatment","orig.ident"))

p = ggplot(df, aes(x = orig.ident, fill = treatment)) +
  geom_bar(position = "stack") +
  labs(title = "Models data",
       x = "Model ID",
       y = "Count",
       fill = "Treatment") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1,size = 20),axis.title = element_text(size = 20),
        axis.text.y = element_text(size = 15),legend.text = element_text(size = 20),legend.title = element_text(size = 20),plot.title = element_text(size = 25))
p
```




# programs expression
```{r fig.height=7, fig.width=12, results='asis'}

#add each metagene to metadata
for (i  in 1:ncol(xeno_cell_usage)) {
  metagene_metadata = xeno_cell_usage[,i,drop=F]
  xeno = AddMetaData(object = xeno,metadata = metagene_metadata,col.name = names(xeno_cell_usage)[i])
}

p = FeaturePlot(object = xeno,features = colnames(xeno_cell_usage),ncol = 3)

p
```

```{r}
svg(params$data_out_dir %s+% "xeno_programs_usage_UMAP.svg",height = 7,width = 12)
p
dev.off()
```

# Heatmap
```{r fig.height=10}
# all_programs_top_genes = data.frame()
# for (i in 1:(ncol(gep_scores)-1)) {
#   top_genes = gep_scores  %>%  arrange(desc(gep_scores[i])) #sort by score a
#   top = head(rownames(top_genes), 20) #take top top_genes_num
#   all_programs_top_genes = rbind(all_programs_top_genes, data.frame(row.names = top, 
#                                                                     top = top, program = paste("program",i)))
# }
# 
# data = FetchData(object = xeno, vars = all_programs_top_genes$top)
# data_row_means = data %>% colMeans()
# data = data[,!data_row_means<0.05] # remove genes with expression less than 0.05
# all_programs_top_genes = all_programs_top_genes[!data_row_means<0.05,] %>% select(!top)
# data = data %>% scale() %>% t()
# 
# annotation_data = FetchData(object = xeno, vars = c(names(xeno_cell_usage)[1:4],"treatment","orig.ident"))
# # annotation_data = FetchData(object = xeno, vars =names(xeno_cell_usage)[1:4])
# 
# data = data[,1:1000] # take small data for debug
# annotation_data = annotation_data [1:1000,] #debug
# annotation_data = annotation_data %>% dplyr::rename( model = orig.ident)
# col_dend = as.dendrogram(hclust(dist(annotation_data[,1:4]),method = "complete")) # cluster based on 4 programs
# 
# col_fun = circlize::colorRamp2(c(0, 1), c("white", "red"))
# models_colors = rainbow(6,alpha = 1) %>% purrr::set_names(unique(xeno$orig.ident))
# column_ha = HeatmapAnnotation(df = annotation_data, col = list(Program.1 = col_fun,Program.2 = col_fun,Program.3 = col_fun,Program.4 = col_fun,unknown = col_fun, treatment  = c(NT = "red",OSI = "green",res = "blue"),model = models_colors))
# colors_list = my_list <- list(program = setNames(c("blue", "green", "red","orange"), unique(all_programs_top_genes$program)))
# 
# row_ha = rowAnnotation(df = all_programs_top_genes,
#                        col =  colors_list)
# 
# p = ComplexHeatmap::Heatmap(
#   data,
#   show_column_names = F,
#   row_names_gp = grid::gpar(fontsize = 7),
#   cluster_rows = F,
#   top_annotation =
#     column_ha,
#   name = "Z-score expression",use_raster = F,cluster_columns = col_dend,right_annotation = row_ha
# )
#   

```

```{r fig.height=7, fig.width=4}
# p = ComplexHeatmap::Heatmap(
#   gep_scores,
#   cluster_columns = F,
#   show_column_names = T,
#   show_row_names = F,
#   cluster_rows = T,
#   name = "score",use_raster = F
# )
# p
```



```{r warning=FALSE}
# modify dotplot to be without exponent of the expression
newDef <- deparse(DotPlot)
newDef[57] =  "            return(mean(x =  x))"
newDef[136] =  "            yes = \"Identity\", no = \"Split Identity\")) + cowplot::theme_cowplot()" #add package name
newDef[95] = "                data.use <- data.use" # remove log
newDef[146] = "        plot <- plot + scale_color_distiller(palette = cols,  direction = 1)"
DotPlot.2 <- eval(parse(text=newDef))
```

# Programs dotplot

```{r}
# scale metagene and add to metadata
for (i  in 1:ncol(xeno_cell_usage)) {
  metagene_metadata = xeno_cell_usage[,i,drop=F] %>% scale()
  xeno = AddMetaData(object = xeno,metadata = metagene_metadata,col.name = paste0(names(xeno_cell_usage)[i],"_scaled"))
}
```

```{r}
xeno = program_assignment(dataset = xeno,program_names = names(xeno_cell_usage),larger_by = 2)


data = FetchData(object = xeno,vars = c(paste0(names(xeno_cell_usage),"_scaled"),"treatment","program.assignment"))%>%
  group_by(treatment) %>% 
  summarize(
    across(c(-program.assignment), mean), # 
    program.1  = sum(program.assignment == "Program.1"),
    program.2  = sum(program.assignment == "Program.2"),
    program.3  = sum(program.assignment == "Program.3"),
    program.4  = sum(program.assignment == "Program.4"),
    program.5  = sum(program.assignment == "Program.5"),
    n = n()
  ) %>% ungroup() %>% 
  t() %>% as.data.frame() %>% janitor::row_to_names(1) %>% rownames_to_column("program") %>% 
  pivot_longer(!program, names_to = "treatment", values_to = "value")
data2 = cbind(data[1:15,],data[16:30,])
cell_count_df = data[31:33,] %>% select(treatment,value) %>% dplyr::rename(cell_count = value) 
data2 = data2[,-c(1,2)] %>% dplyr::rename(assigned_cells = value.1,z_score_level = value)
data2 = left_join(data2, cell_count_df, by = "treatment")%>%
  mutate(
    z_score_level = as.numeric(z_score_level),
    assigned_cells = as.numeric(assigned_cells),
    cell_count = as.numeric(cell_count)
  )
data2 = data2  %>% mutate(precntg = assigned_cells/cell_count)

p = ggplot(data = data2, mapping = aes_string(x = "program", 
    y = "treatment")) + geom_point(mapping = aes_string(size = "precntg", 
    color = 'z_score_level')) + scale_size(range = c(1, 8)) + theme(axis.title.x = element_blank(), 
    axis.title.y = element_blank()) + guides(size = guide_legend(title = "assigned/all_cells")) + 
    labs(x = "Features", y = "Treatment") + cowplot::theme_cowplot()+
  scale_color_gradient(low = "lightblue", high = "darkblue")
# change x axis names to program names
 p+scale_x_discrete(labels= paste0(names(xeno_cell_usage),"\n(",c("IFNa","TNFa-NFKb","HIF","Cell_Cycle"),")"))
p
```





```{r}
saveRDS(object = as.grob(p),file = "./Figures/xeno_NMF_programs_dotplot.rds")
```





# NMF programs regulation  {.tabset}

```{r echo=TRUE, fig.height=4, fig.width=7, results='asis'}
p = metagenes_violin_compare(dataset = xeno,prefix = "model",pre_on = c("NT","OSI"),test = "wilcox.test",programs = colnames(xeno_cell_usage)[3], return_list = T)
p = p[[1]]+xlab("Model")+ylab(paste( "Program 3 (HIF)\n Z-score"))

p
```

```{r}
saveRDS(object = as.grob(p),file = "./Figures/xeno_NMF_hypoxia_split_violin.rds")
```

```{r}
program_names =  c("IFNa","TNFa", "cell cycle","EMT")
```

```{r fig.height=5, fig.width=11}
# for sup:
plt_list = metagenes_violin_compare(dataset = xeno,prefix = "model",pre_on = c("NT","OSI"),test = "wilcox.test",programs = colnames(xeno_cell_usage)[-c(3)],return_list =  T)

for (i in 1:length(plt_list)) {
  plt_list[[i]] = plt_list[[i]]+xlab("Model")+ylab(paste0( "Program ",i," (",program_names[i],")\n Z-score"))
}

p = ggarrange(plotlist = plt_list,common.legend = T)
p
```

```{r}
saveRDS(object = as.grob(p),file = "./Figures/xeno_NMF_NOhypoxia_split_violin.rds")
```



```{r}
saveRDS(object = as.grob(p),file = "./Figures/xeno_patient_hifTargets_split_violin.rds")
```



```{r fig.height=15}
# heatmap with clutering per model and time point
data = FetchData(object = xeno, vars = c(hif_targets,"orig.ident"))
data[] <- data %>%  group_by(orig.ident) %>%
  mutate(across(is.numeric, ~ as.numeric(scale(.)))) %>% ungroup() # scale per model
data = data %>% select(-orig.ident) # remove ident var
data = data %>% t() %>% as.data.frame()

annotation_data = FetchData(object = xeno, vars = c("orig.ident","treatment")) %>% dplyr::arrange(orig.ident,treatment)
column_ha = HeatmapAnnotation(Treatment = annotation_data[,2], #set annotation
                              col = list(Treatment = c("NT" = "red", "OSI" = "green", "res" = "blue"))) 
data = data[,rownames(annotation_data)] #order data like annotation
data = na.omit(data)
column_split = paste(annotation_data$orig.ident,annotation_data$treatment,sep = "\n") #split by ident+tp
column_names = unique(column_split) %>% gsub(pattern = "119\nOSI",replacement = "      119\n      OSI") #adujst location to avoid overlap

p = ComplexHeatmap::Heatmap(
  data,
  show_column_names = F,
  row_names_gp = grid::gpar(fontsize = 10),
  cluster_rows = T,
  top_annotation = column_ha,
  name = "Z-score expression",use_raster = F,cluster_columns = T,column_split = column_split,
  column_title = column_names,
  column_gap = unit(2, "mm"), border = TRUE,show_parent_dend_line = FALSE, show_column_dend = F,cluster_column_slices = F)

  
p
```


```{r fig.height=15}

data = FetchData(object = xeno, vars = c(hif_targets,"orig.ident"))
data[] <- data %>%  group_by(orig.ident) %>% mutate(across(is.numeric, ~ as.numeric(scale(.)))) %>% ungroup() %>% select(-orig.ident) 
data = data %>% t() %>% as.data.frame()

annotation_data = FetchData(object = xeno, vars = c("orig.ident","treatment")) %>% dplyr::arrange(orig.ident,treatment)
column_ha = HeatmapAnnotation(df = annotation_data[,2])
data = data[,rownames(annotation_data)] #order data like annotation
data = na.omit(data)
p = ComplexHeatmap::Heatmap(
  data,
  show_column_names = F,
  row_names_gp = grid::gpar(fontsize = 7),
  cluster_rows = T,
  top_annotation = column_ha,
  name = "Z-score expression",use_raster = F,cluster_columns = F,column_split   = annotation_data$orig.ident,
  column_gap = unit(2, "mm"), border = TRUE,show_parent_dend_line = FALSE, show_column_dend = FALSE,cluster_column_slices = F
)
  
p
```

```{r fig.height=7, fig.width=10}
p = DoHeatmap(object = xeno,features = hif_targets,group.by = "treatment")
p

```

# known genes score
```{r}

ranked_vec = gep_scores[,1] %>% setNames(rownames(gep_scores)) %>% sort(decreasing = TRUE) 
hyp_obj <- hypeR_fgsea(ranked_vec, genesets)
le_genes_ifna =  hyp_obj$data %>% filter(label == "HALLMARK_INTERFERON_ALPHA_RESPONSE") %>% pull("le") %>% strsplit(",") %>% unlist()

ranked_vec = gep_scores[,2] %>% setNames(rownames(gep_scores)) %>% sort(decreasing = TRUE) 
hyp_obj <- hypeR_fgsea(ranked_vec, genesets)
le_genes_tnfa =  hyp_obj$data %>% filter(label == "HALLMARK_TNFA_SIGNALING_VIA_NFKB") %>% pull("le") %>% strsplit(",") %>% unlist()

ranked_vec = gep_scores[,3] %>% setNames(rownames(gep_scores)) %>% sort(decreasing = TRUE) 
hyp_obj <- hypeR_fgsea(ranked_vec, genesets)
le_genes_hif =  hyp_obj$data %>% filter(label == "HIF_targets") %>% pull("le") %>% strsplit(",") %>% unlist()


gene_list = list(IFNa_genes = genesets$HALLMARK_INTERFERON_ALPHA_RESPONSE, TNFa_genes = genesets$HALLMARK_TNFA_SIGNALING_VIA_NFKB, hif_targets = hif_targets,E2F_genes = genesets$HALLMARK_E2F_TARGETS,gep2_top = gep_scores  %>%  arrange(desc(gep_scores[2])) %>% rownames() %>% head(200),TNFa_le = le_genes_tnfa,hif_le = le_genes_hif,IFNa_le  = le_genes_ifna)
# xeno = ScaleData(object = xeno,features = unlist(gene_list))
for (i in seq_along(gene_list)) {
  genes = gene_list[[i]]
  name = names(gene_list)[i]
  scores = FetchData(object = xeno,vars = genes,slot = "data")  %>%  expm1()  %>%  rowMeans() #use  TPM
    # scores = FetchData(object = xeno,vars = genes,slot = "data")  %>%  rowMeans() #use  TPM

  xeno %<>% AddMetaData(metadata = scores,col.name = name)

}



```



# known genes score
```{r}

gene_list = list(IFNa_genes = genesets$HALLMARK_INTERFERON_ALPHA_RESPONSE, TNFa_genes = genesets$HALLMARK_TNFA_SIGNALING_VIA_NFKB, hif_targets = hif_targets,E2F_genes = genesets$HALLMARK_E2F_TARGETS)
patient_var = "orig.ident"
# xeno = ScaleData(object = xeno,features = unlist(gene_list))
for (i in seq_along(gene_list)) {
  genes = gene_list[[i]]
  name = names(gene_list)[i]
  genes = genes[genes %in% rownames(xeno)]
  scores = FetchData(object = xeno,vars = c(genes,patient_var))
  scores = scores %>% mutate(r = rowMeans(dplyr::select_at(scores,vars(-contains(patient_var))))) %>% # z score every patient separately 
    group_by_at(patient_var) %>% summarise(r = scale(r)) %>% pull(r) %>% as.data.frame() 
  print(name)
  xeno %<>% AddMetaData(metadata = scores,col.name = name)
}





```



```{r}

p1 = metagenes_violin_compare(dataset = xeno,prefix = "Model",pre_on = c("NT","OSI"),test = "wilcox.test",programs = "hif_targets", return_list = T)[[1]]
p1
```

```{r}
saveRDS(object = as.grob(p1),file = "./Figures/xeno_hif_targets_violin.rds")
```


```{r fig.height=4, fig.width=11}

p = DotPlot.2(object = xeno, features =   names(gene_list),group.by  = 'treatment',scale = F)+
  guides(size = guide_legend(title = "Cells above average (%)"),color = guide_colorbar(title = "Average Score"))
p
```
```{r}
saveRDS(object = as.grob(p),file = "./Figures/xeno_signtures_dotplot.rds")
```


# new


# known genes signatures log TPM
```{r}

gene_list = list(IFNa_genes = genesets$HALLMARK_INTERFERON_ALPHA_RESPONSE, TNFa_genes = genesets$HALLMARK_TNFA_SIGNALING_VIA_NFKB, hif_targets = hif_targets,E2F_genes = genesets$HALLMARK_E2F_TARGETS)
patient_var = "orig.ident"
for (i in seq_along(gene_list)) {
  genes = gene_list[[i]]
  name = names(gene_list)[i]
  genes = genes[genes %in% rownames(xeno)]
  scores = FetchData(object = xeno,vars = c(genes,patient_var))
  scores = scores %>% mutate(r = rowMeans(dplyr::select_at(scores,vars(-contains(patient_var))))) %>% # z score every patient separately 
    group_by_at(patient_var) %>% summarise(r = scale(r)) %>% pull(r) %>% as.data.frame() 
  print(name)
  xeno %<>% AddMetaData(metadata = scores,col.name = name)
}

```


## violin
```{r}
p2 = metagenes_violin_compare(dataset = xeno,prefix = "Modek",pre_on = c("NT","OSI"),test = "wilcox.test",programs = "hif_targets", return_list = T)[[1]] + xlab("Model")+
  ylab("HIF targets mean score")
p2
```

```{r}
saveRDS(object = as.grob(p2),file = "./Figures/xeno_hif_targets_violin.rds")
```

## Dotplot

```{r}
# scale for all cells
for (i in seq_along(gene_list)) {
  genes = gene_list[[i]]
  name = paste0(names(gene_list)[i],"_scaled")
  genes = genes[genes %in% rownames(xeno)]
  scores = FetchData(object = xeno,vars = c(genes)) %>% rowMeans() %>% scale()
  xeno %<>% AddMetaData(metadata = scores,col.name = name)
}
```

```{r warning=FALSE}
# modify dotplot to be without exponent of the expression
newDef <- deparse(DotPlot)
newDef[57] =  "            return(mean(x =  x))" # remove exponent
newDef[136] =  "            yes = \"Identity\", no = \"Split Identity\")) + cowplot::theme_cowplot()" #add package name
newDef[95] = "                data.use <- data.use" # remove log
newDef[146] = "        plot <- plot + scale_color_distiller(palette = cols,  direction = 1)"
DotPlot.2 <- eval(parse(text=newDef))
```


```{r fig.height=4, fig.width=11}

p = DotPlot.2(object = xeno, features =  paste0(names(gene_list),"_scaled"),group.by  = 'treatment',scale = F)+
  guides(size = guide_legend(title = "Cells above average (%)"),
         color = guide_colorbar(title = "Average Score"))+ 
  scale_y_discrete(limits = c("NT","OSI"))+
  scale_x_discrete(labels= names(gene_list))
p
```

```{r}
saveRDS(object = as.grob(p),file = "./Figures/xeno_signtures_dotplot.rds")
```


# known genes signatures TPM
```{r}
patient_var = "orig.ident"
for (i in seq_along(gene_list)) {
  genes = gene_list[[i]]
  name = names(gene_list)[i]
  genes = genes[genes %in% rownames(xeno)]
  scores = FetchData(object = xeno,vars = c(genes,patient_var))
  scores[,1:(ncol(scores)-1)] = (2^scores[,1:(ncol(scores)-1)])-1 # log(tpm+1)to tpm without last col (patients idents)
  scores = scores %>% mutate(r = rowMeans(dplyr::select_at(scores,vars(-contains(patient_var))))) %>% # z score every patient separately 
    group_by_at(patient_var) %>% summarise(r = scale(r)) %>% pull(r) %>% as.data.frame() 
  print(name)
  xeno %<>% AddMetaData(metadata = scores,col.name = name)
}

```


## violin
```{r}
p2 = metagenes_violin_compare(dataset = xeno,prefix = "Model",pre_on = c("NT","OSI"),test = "wilcox.test",programs = "hif_targets", return_list = T)[[1]] + xlab("Model")+
  ylab("HIF targets Z-score")
p2
```

```{r}
saveRDS(object = as.grob(p2),file = "./Figures/xeno_hif_targets_TPM_violin.rds")
```

## Dotplot

```{r}
# scale for all cells
for (i in seq_along(gene_list)) {
  genes = gene_list[[i]]
  name = paste0(names(gene_list)[i],"_scaled")
  genes = genes[genes %in% rownames(xeno)]
  scores = FetchData(object = xeno,vars = c(genes))
  scores = (2^scores)-1 
  scores = scores %>%  rowMeans() %>% scale() #log(tpm+1)to tpm
  xeno %<>% AddMetaData(metadata = scores,col.name = name)
}
```


```{r fig.height=4, fig.width=11}

p = DotPlot.2(object = xeno, features =  paste0(names(gene_list),"_scaled"),group.by  = 'treatment',scale = F)+
  guides(size = guide_legend(title = "Cells above average (%)"),
         color = guide_colorbar(title = "Average Score"))+ 
  scale_y_discrete(limits = c("NT","OSI"))+
  scale_x_discrete(labels= names(gene_list))
p
```


```{r}
saveRDS(object = as.grob(p),file = "./Figures/xeno'_signtures_TPM_dotplot.rds")
```


