---
title: "01_preprocess"
output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---

```{r}
# Get input and output
source("./pipe.R")
input = pipeline$patients_preprocess$input
output = pipeline$patients_preprocess$output
```

```{r}
library(Seurat)
library("dplyr")
library("ggplot2")
library(qs2)
```


```{r}

tpm <- function(counts, lengths) {
  
  rpk <- counts / lengths
  coef <- sum(rpk) / 1e6
  rpk/coef
}
```

```{r}
lung.data <- read.delim(input$count_matrix,skip=0,header=T,sep="\t",stringsAsFactors=F)
rownames(lung.data)<- make.unique(lung.data$gene_name)
lengths <- lung.data[,6] 
omitgenes <- startsWith(rownames(lung.data),"MT-")|startsWith(rownames(lung.data),"ERCC-")
lung.data <- lung.data[,8:ncol(lung.data)]
```

```{r}
# remove PDX
lung.data = lung.data %>% select(-contains("PC9")) %>% select(-contains("X1068"))%>% select(-contains("MGH1068")) 
```



```{r}
# changing the cell labels
cell.labels <- gsub(".gene_counts.tsv","",colnames(lung.data))
cell.labels <- gsub(".sort.bam","",cell.labels)
cell.labels <- gsub("_",".",cell.labels)
cell.labels <- gsub(".S[0-9]*","",cell.labels)
t <- regexpr("[A-H][0-9]+$", cell.labels)
cell.labels[t<0] <- paste0(regmatches(cell.labels[t<0], regexpr("[^ACGT]*", cell.labels[t<0])),regmatches(colnames(lung.data)[t<0], regexpr("_S[0-9]+", colnames(lung.data)[t<0])))
well <- regmatches(cell.labels, regexpr("[A-H,S][0-9]+$", cell.labels))
plate <- substr(cell.labels,1,nchar(cell.labels)-nchar(well)-1)

colnames(lung.data) <- paste(plate,well,sep="_")

```


```{r}
#remove certain plates
to_remove = c("X1071.10." ,"X1071.3.P3", "X1071.4.P3",   "X1071.8.P2",   "MGH1071.3.P1", "MGH1071.4",    "MGH1071.8.P1", "MGH1066.2.p2", "MGH1066.2.p3"  ,"MGH1066.P1",    "MGH1066.P2")
lung.data = lung.data[,!plate %in% to_remove]
well = well [!plate %in% to_remove]
plate = plate[!plate %in% to_remove]
```


```{r}
dim(lung.data)
```

# QC
```{r}
lung <- CreateSeuratObject(counts = lung.data, project = "lung", min.cells = 3, min.features = 200)
prefix="all"

dim(lung)

id <- FetchData(lung, "orig.ident") # gives the name of the sample for each cell 
cell_number <- as.data.frame(table(id)) # creates df of number of cells sequenced for each sample

percent.mt <- PercentageFeatureSet(lung, pattern = "^MT-")
lung[["percent.mt"]] <- percent.mt

nFeature_RNA_plot <- VlnPlot(lung , features = "nFeature_RNA") + theme(legend.position="none", axis.text.x = element_text(size=8))
nCount_RNA_plot <- VlnPlot(lung , features = "nCount_RNA") + theme(legend.position="none", axis.text.x = element_text(size=8))
percent.mt_plot <- VlnPlot(lung , features = "percent.mt") + theme(legend.position="none", axis.text.x = element_text(size=8))


FeatureScatter(lung, feature1 = "nCount_RNA", feature2 = "percent.mt") + 
  theme(legend.position="none", axis.text.x = element_text(size=8)) + 
  geom_point(color='darkblue')

FeatureScatter(lung, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") + 
  theme(legend.position="none", axis.text.x = element_text(size=8)) + 
  geom_point(color='darkblue')

FeatureScatter(lung, feature1 = "nFeature_RNA", feature2 = "percent.mt") + 
  theme(legend.position="none", axis.text.x = element_text(size=8)) + 
  geom_point(color='darkblue')



```
# metadata and clustering, UMAP

```{r}
lung.tpm <- apply(lung.data[!omitgenes,1:dim(lung.data)[2]], 2, function(x) tpm(x, lengths[!omitgenes]) )
colnames(lung.tpm) <- paste(plate,well,sep="_")
```

```{r}
lung <- CreateSeuratObject(counts = log2(lung.tpm+1), project = "lung", min.cells = 3, min.features = 200)
lung[["percent.mt"]] <- percent.mt

# subseting the data according to the QC
lung <- subset(lung, subset = nFeature_RNA > 2000 & percent.mt < 35)
dim(lung)

# calculate how many cells in each sample after the QC
idQC <- FetchData(lung, "orig.ident")
cell_numberQC <- as.data.frame(table(idQC))
cell_number[["PassedQC"]] <- cell_numberQC$Freq
cell_number[["percentagePQC"]] <- cell_number$PassedQC / cell_number$Freq

# Identification of highly variable features
lung <- FindVariableFeatures(lung, selection.method = "vst", nfeatures = 2000)

# Scaling the data
all.genes <- rownames(lung)
lung <- ScaleData(lung, features = all.genes)


# adding patient symbol to the seurat meta.data
unique(x = lung@meta.data$orig.ident)
patient.ident <- gsub("[[:punct:]]\\w*$","", lung@meta.data$orig.ident)
patient.ident <- gsub("[[:punct:]]\\w*$","", patient.ident)
patient.ident <- gsub("[[:punct:]]\\w*$","", patient.ident)
patient.ident <- gsub("X1068","MGH1068", patient.ident)
patient.ident <- gsub("X1144","MGH1144", patient.ident)
patient.ident <- gsub("X1155","MGH1155", patient.ident)
patient.ident <- gsub("X1071","MGH1071", patient.ident)
patient.ident <- gsub("X1055new","MGH1055", patient.ident)
patient.ident <- gsub("X1099","MGH1099", patient.ident)
patient.ident <- gsub("X1167","MGH1167", patient.ident)



levels(as.factor(patient.ident))
lung <- AddMetaData(object = lung, metadata = as.factor(patient.ident), col.name = "patient.ident")


# Perform linear dimensional reduction (PCA)

lung <- RunPCA(lung, features = VariableFeatures(object = lung))

pcaplot <- PCAPlot(lung, label = FALSE)

elbowplot <- ElbowPlot(lung, ndims = 50) # checking the dimensionality 

# cluster the cells
lung <- FindNeighbors(lung, dims = 1:25)
lung <- FindClusters(lung, resolution = .5)

# Run non-linear dimensional reduction (UMAP)
lung <- RunUMAP(lung, dims = 1:25)

lung_umap1 <- DimPlot(object = lung, reduction = "umap", pt.size = 0.1, label = TRUE)

lung_umap4 <- DimPlot(object = lung, reduction = "umap", pt.size = 0.1, label = F, group.by="patient.ident")

lung_umap1
lung_umap4

svg(params$data_out_dir %s+% "patietns_UMAP_all_cells_clustering.svg")
lung_umap1
dev.off()


```



```{r fig.height=5, fig.width=10}
wbc_markers = c("CD68", "PTPRC", "CD163", "CD14", "CD53", "CD52", "C3AR1", "LAPTM5", "IGSF6",  "SRGN" )
wbc_dotplot = DotPlot(object = lung,features = wbc_markers,cluster.idents = F,scale = F) +ggtitle("WBC markers")
endo_markers= c("VWF", "ERG", "PTPRB",  "TIE1" )
endo_dotplot = DotPlot(object = lung,features = endo_markers,cluster.idents = F,scale = F) + ggtitle("Endothelial markers") 
meso_markers = c("CALB2", "UPK3B", "UPK1B", "HAS1", "WT1", "SAA2",  "SAA1")
meso_dotplot = DotPlot(object = lung,features = meso_markers,cluster.idents = F,scale = F)+ ggtitle("Mesothelial markers") 
cancer_markers = c("EGFR", "MET", "EPCAM", "NKX2-1", "NAPSA")
cancer_dotplot = DotPlot(object = lung,features = cancer_markers,cluster.idents = F,scale = F)+ ggtitle("Cancer markers") 
wbc_dotplot
endo_dotplot
meso_dotplot
cancer_dotplot
```

```{r fig.height=9, fig.width=12}
p = ggpubr::ggarrange(wbc_dotplot,endo_dotplot,meso_dotplot,cancer_dotplot, common.legend = T,ncol = 2,nrow = 2,widths = c(1.5,1))
p

svg(filename = params$data_out_dir %s+% "clusters_cell_types.svg",height = 9,width = 12)
p
dev.off()
```

# identify cell types
```{r}

# assigning the type of the cell of the clusters
new.cluster.ids <- c(" 0- cancer",
                     " 1- cancer",
                     " 2- WBC",
                     " 3- cancer",
                     " 4- cancer",
                     " 5- cancer",
                     " 6- cancer",
                     " 7- Mesothelial/Endothelial",
                     " 8- cancer",
                     " 9- WBC",
                     "10- cancer",
                     "11- cancer",
                     "12- cancer",
                     "13- cancer")                
names(new.cluster.ids) <- levels(lung)
lung <- RenameIdents(lung, new.cluster.ids)
umap_labled <- DimPlot(lung, reduction = "umap", label = TRUE, pt.size = 0.1) + NoLegend()
umap_labled2 <- DimPlot(lung, reduction = "umap", label = F, pt.size = 0.1) 


new.cluster.ids2 <- c("cancer",
                      "cancer",
                      "WBC",
                      "cancer",
                      "cancer",
                      "cancer",
                      "cancer",
                      "Mesothelial/Endothelial",
                      "cancer",
                      "WBC",
                      "cancer",
                      "cancer",
                      "cancer",
                      "cancer")              
names(new.cluster.ids2) <- levels(lung)
lung <- RenameIdents(lung, new.cluster.ids2)


umap_labled1 <- DimPlot(lung, reduction = "umap", label = F, pt.size = 0.1) 
umap_labled3 <- DimPlot(lung, reduction = "umap", label = F, pt.size = 0.1, group.by="patient.ident") + ggtitle(NULL)

umap_labled1
umap_labled3
```

```{r}
svg(filename = params$data_out_dir %s+% "UMAP_cell_types.svg")
umap_labled1
dev.off()

svg(filename = params$data_out_dir %s+% "UMAP_patient_idents.svg")
umap_labled3
dev.off()
```

```{r}
cluster_types <- substring(new.cluster.ids,5)
cell.type <- lung@meta.data$seurat_clusters
levels(cell.type) <- cluster_types
lung <- AddMetaData(object = lung, metadata = as.factor(cell.type), col.name = "cell.type")
```

# cluster/UMAP cancer cells 
```{r}
CancerOnlyTPM <- subset(lung, subset = cell.type == "cancer")
dim(CancerOnlyTPM)

```



# set tp metadata
```{r}

patients <- unique(CancerOnlyTPM$patient.ident)


#### cancer cel from cancer cells file
for (patient in patients){
  CancerOnlyTPM_patient <- subset(CancerOnlyTPM, subset = patient.ident == patient)
  CancerOnlyTPM <- subset(CancerOnlyTPM, subset = patient.ident != patient)
  pre_treatment = switch(
    as.character(patient),
    "MGH1066" = "MGH1066.1.p5|MGH1066.1.P4|MGH1066.1.P6",
    "MGH1055" = "X1055new.1.p1|X1055new.1.p2",
    "MGH1068" = "X1068.2PDXP2M2.Control.P1|X1068.2PDXP2M2.Control.P2|X1068.2PDXP2M2.Control.P3|X1068.2PDXP2M2.Control.P4",
    "MGH1071" = "X1071.2.P3|X1071.2.P5|MGH1071.2|MGH1071.2.P2",
    "MGH1099" = "X1099.1.p3|X1099.1.p8",
    "MGH1144" = "MGH1144.merged1|MGH1144.merged2.p1|MGH1144.2.p1",
    "MGH1167" = "MGH1167.1.p1|X1167.1.p2",
    "MGH088" = "MGH088.2.p1",
    "MGH1155" = "MGH1155.1",
    "PC9" = "PC9.6R.GEF.MOE|PC9.GEF.M6R.P1|PC9.MOE.6R.P2|PC9.MOE.6R.P4"
  )
  on_treatment = switch(
    as.character(patient),
    "MGH1066" = "MGH1066.3.p4|MGH1066.3.P5|MGH1066.3.P6|MGH1066.d12erb",
    "MGH1055" = "X1055new.2.p1|X1055new.2.p2",
    "MGH1068" = "X1068.2PDXP2M2.Gefitinib8Weeks.P1|X1068.2PDXP2M2.Gefitinib8Weeks.P2",
    "MGH1071" = "X1071.5.P3|MGH1071.5|MGH1071.5.P2",
    "MGH1099" = "X1099.2.p1|X1099.3.p2",
    "MGH1144" = "X1144.3.p3|MGH1144.3",
    "MGH1167" = "MGH1167.2.p1",
    "MGH088" = "MGH088.3R.p1|MGH088.4.p1",
    "MGH1155" = "MGH1155.4|MGH1155.5.p2|MGH1155.6.p3|MGH1155.7",
    "PC9" = "PC9.GEF.M3L.P3|PC9.MOE.3L.GEF"
  )
  resistant = switch(
    as.character(patient),
    "MGH1071" = "X1071.10.P1|X1071.10.P4|MGH1071.10.P|X1071.10.P|MGH1071.10.P1|MGH1071.10.P4|X1071.10.p1|X1071.10.p4|MGH1071.10.p|X1071.10.p|MGH1071.10.p1|MGH1071.10.p4",
    "MGH1144" = "X1144.5.p1|X1144.5.p2|MGH1144.5.p1|MGH1144.5.p2|MGH1144.5",
    "MGH088" = "MGH088.5.p1"
  )
  time.point <- gsub(pre_treatment,
                     "pre-treatment",
                     CancerOnlyTPM_patient@meta.data$orig.ident)       
  time.point <- gsub(on_treatment, "on-treatment", time.point)
  if (patient %in% c('MGH1144', "MGH088", 'MGH1071')) {
    time.point <- gsub(resistant, "resistant", time.point)
  }
  print(unique(time.point)[!unique(time.point) %in% c("pre-treatment", "on-treatment", "resistant")])
  
  time.point[!(time.point %in% c("pre-treatment", "on-treatment", "resistant"))] <- "NA"
  CancerOnlyTPM_patient <- AddMetaData(
    object = CancerOnlyTPM_patient,
    metadata = as.factor(time.point),
    col.name = "time.point"
  )
  Idents(CancerOnlyTPM_patient) <- "time.point"
  CancerOnlyTPM_patient <- subset(CancerOnlyTPM_patient,
                                  subset = time.point %in% c("pre-treatment", "on-treatment", "resistant"))
  CancerOnlyTPM <- merge(CancerOnlyTPM, CancerOnlyTPM_patient)
}

```
# remove patients with less 100 cells
```{r}
CancerOnlyTPM$patient.ident %>% table()
CancerOnlyTPM <- CancerOnlyTPM[,!CancerOnlyTPM@meta.data$patient.ident %in% c("MGH1055","MGH1099")] # remove patients with less than 100 malignant cells


```

```{r}
CancerOnlyTPM <- FindVariableFeatures(CancerOnlyTPM)
CancerOnlyTPM <- ScaleData(CancerOnlyTPM)
CancerOnlyTPM <- RunPCA(CancerOnlyTPM, dims=1:10)
CancerOnlyTPM <- RunUMAP(CancerOnlyTPM, dims = 1:10)
CancerOnlyTPM <- FindNeighbors(CancerOnlyTPM, reduction = "pca", dims = 1:10)
CancerOnlyTPM <- FindClusters(CancerOnlyTPM, resolution = .5)
```

```{r}
print(DimPlot(CancerOnlyTPM, reduction = "umap", pt.size = 0.1))
print(DimPlot(CancerOnlyTPM, reduction = "umap", group.by="patient.ident", pt.size = 0.1))
print(DimPlot(CancerOnlyTPM, reduction = "umap", group.by="time.point", pt.size = 0.1))
```

```{r}
qs_save(CancerOnlyTPM,params$data_out_dir %s+% basename(output$patients))
```

