---
title: 'patients_cnmf_analysis_k5_from_xeno' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 

editor_options: 
  chunk_output_type: inline
---


```{r}
#Get input and output
source("./pipe.R")
input = pipeline$patients_programs_analysis$input
output = pipeline$patients_programs_analysis$output
```


# Functions

```{r warning=FALSE}
library(stringi)
library(reticulate)
library(ggpubr)
suppressPackageStartupMessages(library(GSEABase))
source_from_github(repositoy = "DEG_functions",version = "0.2.53")
source_from_github(repositoy = "cNMF_functions",version = "0.4.33",script_name = "cnmf_functions_V3.R")
source_from_github(repositoy = "sc_general_functions",version = "0.1.34",script_name = "functions.R")

```

# Data

```{r}
lung = qs::qread(input$lung)
patients_cell_usage = readRDS(input$patients_cell_usage)
genesets = getGmt(input$genesets)  %>% geneIds()
hif_targets =  scan(input$hif_targets, character(), quote = "")
genesets[["HIF_targets"]] = hif_targets
lung$time.point = lung$time.point %>% factor(levels = c("pre-treatment","on-treatment", "resistant")) 
lung$treatment = lung$time.point
```


```{r fig.height=6, fig.width=14}
p1  = DimPlot(lung,group.by = "patient.ident")+ggtitle("")+ guides(color=guide_legend(title="Patient",override.aes = list(size=3)))
p2  =  DimPlot(lung,group.by = "time.point",shuffle = T)+ggtitle("")+ guides(color=guide_legend(title="Time.point",override.aes = list(size=3)))
p1+p2

df = FetchData(lung,vars = c("time.point","patient.ident"))

p = ggplot(df, aes(x = patient.ident, fill = time.point)) +
  geom_bar(position = "stack") +
  labs(title = "Patients data",
       x = "Patient ID",
       y = "Count",
       fill = "Time Point") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1,size = 20),axis.title = element_text(size = 20),
        axis.text.y = element_text(size = 15),legend.text = element_text(size = 20),legend.title = element_text(size = 20),plot.title = element_text(size = 25))
p
```




# programs expression

```{r echo=TRUE, fig.height=7, fig.width=12, results='asis'}

#add each metagene to metadata
for (i  in 1:ncol(patients_cell_usage)) {
  metagene_metadata = patients_cell_usage[,i,drop=F]
  lung = AddMetaData(object = lung,metadata = metagene_metadata,col.name = names(patients_cell_usage)[i])
}

p  = FeaturePlot(object = lung,features = colnames(patients_cell_usage),ncol = 3)+DimPlot(object = lung,group.by = "time.point",shuffle = T)

p
```


```{r}
svg(params$data_out_dir %s+% "patients_programs_usage_UMAP.svg",height = 7,width = 12)
p
dev.off()
```





# NMF programs dotplot



```{r}
# scale metagene and add to metadata
for (i  in 1:ncol(patients_cell_usage)) {
  metagene_metadata = patients_cell_usage[,i,drop=F] %>% scale()
  lung = AddMetaData(object = lung,metadata = metagene_metadata,col.name = paste0(names(patients_cell_usage)[i],"_scaled"))
}
```



```{r fig.height=4, fig.width=11}
lung = program_assignment(dataset = lung,program_names = names(patients_cell_usage),larger_by = 2)

p = programs_dotplot(seurat_obj = lung,treatment_var = "time.point",program_names = paste0(names(patients_cell_usage),"_scaled"))+scale_y_discrete(limits  = c("pre-treatment","on-treatment","resistant"))
p
```

```{r}
svg(params$data_out_dir %s+% "patients_programs_dotplot.svg",height = 4,width = 8)
p
dev.off()
```


# NMF programs violin combine patients
```{r}
p = metagenes_violin_combine_patients(dataset = lung,prefix = "patient",pre_on = c("pre-treatment","on-treatment"),test = "wilcox.test",programs = colnames(patients_cell_usage), return_list = F)

p
```

# NMF programs per patient

```{r fig.height=5, fig.width=11}
plt_list = metagenes_violin_compare(dataset = lung,prefix = "patient",pre_on = c("pre-treatment","on-treatment"),test = "wilcox.test",programs = colnames(patients_cell_usage)[c(1,2,3,4)], return_list = T,patient.ident_var = "patient.ident")
p = ggarrange(plotlist = plt_list,common.legend = T)
p
```
```{r}
svg(params$data_out_dir %s+% "patients_programs_violin.svg",height = 5,width = 11)
p
dev.off()
```


# NMF HIF per patient
```{r echo=TRUE, fig.height=4, fig.width=7, results='asis'}
p = metagenes_violin_compare(dataset = lung,prefix = "patient",pre_on = c("pre-treatment","on-treatment"),test = "wilcox.test",programs = colnames(patients_cell_usage)[3], return_list = T,patient.ident_var = "patient.ident")
p = p[[1]]+xlab("Patient")+ylab(paste( "Program 3 (HIF)\n"))

p
```

```{r}
svg(params$data_out_dir %s+% "HIF_program_violin_patients.svg",height = 4,width = 7)
p
dev.off()
```





# known genes signatures log TPM
```{r}

gene_list = list(IFNa_genes = genesets$HALLMARK_INTERFERON_ALPHA_RESPONSE, TNFa_genes = genesets$HALLMARK_TNFA_SIGNALING_VIA_NFKB, hif_targets = hif_targets,E2F_genes = genesets$HALLMARK_E2F_TARGETS)
patient_var = "patient.ident"
# xeno = ScaleData(object = xeno,features = unlist(gene_list))
for (i in seq_along(gene_list)) {
  genes = gene_list[[i]]
  name = names(gene_list)[i]
  genes = genes[genes %in% rownames(lung)]
  scores = FetchData(object = lung,vars = c(genes,patient_var))
  scores = scores %>% mutate(r = rowMeans(dplyr::select_at(scores,vars(-contains(patient_var))))) %>% # z score every patient separately 
    group_by_at(patient_var) %>% plyr::summarise(r = scale(r)) %>% pull(r) %>% as.data.frame() 
  print(name)
  lung %<>% AddMetaData(metadata = scores,col.name = name)
}

```


## violin
```{r}
p2 = metagenes_violin_compare(dataset = lung,prefix = "Patient",pre_on = c("pre-treatment","on-treatment"),test = "wilcox.test",programs = "hif_targets", return_list = T,patient.ident_var = "patient.ident")[[1]] + xlab("Patient")
p2
```

```{r}
svg(params$data_out_dir %s+% "HIF_genes_violin_patients.svg")
p
dev.off()
```


