---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  # html_notebook: 
  #   code_folding: hide
  #   toc: yes
  #   toc_collapse: yes
  #   toc_float: 
  #     collapsed: FALSE
  #   number_sections: true
  #   toc_depth: 1
    
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df-print: paged
    
params:
  data_out_dir: NULL
  figs_out_dir: NULL
---






# Functions

```{r}
library(stringi)
library(reticulate)
library(ggplotify)

source_from_github(repositoy = "DEG_functions",version = "0.2.47")
source_from_github(repositoy = "cNMF_functions",version = "0.4.04",script_name = "cnmf_functions_V3.R")
source_from_github(repositoy = "sc_general_functions",version = "0.1.34",script_name = "functions.R")


```

# Data


```{r}
lung = readRDS("./raw_data/lung_cancercells_withTP_onlyPatients.rds")
lung_patients = lung$patient.ident %>% unique() %>% as.character()
lung_patients_filtered = lung_patients[!(lung_patients %in% c("X1055new","X1099"))] # remove patients with less than 100 malignant cells
lung = subset(x = lung,subset = patient.ident %in% lung_patients_filtered)
genesets = getGmt("./raw_data/h.all.v2023.2.Hs.symbols.gmt")
```


# DE pathways

```{r}
calculatePathwayScores <- function(pathwayToScore, countsMatrix) {
  pathwayName <- pathwayToScore@setName
  print(pathwayName)
  pathwayGenes <- pathwayToScore@geneIds
  pathwayScoresObject <- getPathwayScores(countsMatrix, pathwayGenes)
  suppressWarnings(
    if (is.null(pathwayScoresObject)) {
      return(NA)
    }
  )
  return(pathwayScoresObject$pathwayScores)
}
```



```{r}
# debugonce(calculatePathwayScores)
pathwayScoreLists <- lapply(X = genesets@.Data, calculatePathwayScores, lung@assays$RNA@data %>% expm1())
names(pathwayScoreLists) = names(genesets)
pathwayScoreLists <- pathwayScoreLists[!is.na(pathwayScoreLists)] #remove NA pathways
pathwayScoresMatrix <- as.data.frame(do.call("rbind", pathwayScoreLists))
```

```{r}
# save
saveRDS(object = pathwayScoresMatrix,file = "./output_data/run_SiPSiC/patients_pathwayScoresMatrix.RDS")
```


