---
title: "R Notebook"
output: html_notebook
---


```{r}
#define parametes
nfeatures = 2000 #default: 2000
n_iter = 10 #default: 10
densify = T #default: T
tpm = T #default: T
rpk = T #default: F
provideTPM = F  #default: T
suffix ="2Kvargenes_rpk_nullTPM"
```

```{python}
#import parameters to python
nfeatures = r.nfeatures
n_iter = int(r.n_iter)
densify = r.densify
suffix = r.suffix
provideTPM = r.provideTPM
rpk = r.rpk
```

```{r}
lung = readRDS("./Data/lung_cancercells_withTP_onlyPatients.rds")
```

```{r}
lung = FindVariableFeatures(object = lung,nfeatures = nfeatures)
var_features = VariableFeatures(lung) %>% as.character()
```



```{r}
#convert seurat to scanpy AnnData
library(reticulate)
sc <- import('scanpy', convert = FALSE)
gene_expression = t(as.matrix(GetAssayData(lung,slot='data'))) #in smart seq data, TPM is needed both in count_fn and tpm_fn

if(tpm == T){
gene_expression = 2**gene_expression #convert log2(TPM+1) to TPM+1
gene_expression = gene_expression-1 #convert TPM+1 to TPM
}

adata <- sc$AnnData(
  X   = gene_expression, 
  obs = lung[[]],
  var = GetAssay(lung)[[]]
)
rm(gene_expression)
```

```{python}
adata = r.adata
```

```{python}
# %matplotlib inline
# %load_ext autoreload
# %autoreload 2
import scipy
import scanpy as sc
import matplotlib.pyplot as plt
import harmonypy
from harmonypy import run_harmony
import sys
from cnmf import cNMF

import numpy as np
import pandas as pd
from sklearn.decomposition import NMF
import seaborn as sns
import yaml
## copied from harmonypy.py
def moe_correct_ridge(Z_orig, Z_cos, Z_corr, R, W, K, Phi_Rk, Phi_moe, lamb):
    Z_corr = Z_orig.copy()
    for i in range(K):
        Phi_Rk = np.multiply(Phi_moe, R[i,:])
        x = np.dot(Phi_Rk, Phi_moe.T) + lamb
        W = np.dot(np.dot(np.linalg.inv(x), Phi_Rk), Z_orig.T)
        W[0,:] = 0 # do not remove the intercept
        Z_corr -= np.dot(W.T, Phi_Rk)
    Z_cos = Z_corr / np.linalg.norm(Z_corr, ord=2, axis=0)
    return Z_cos, Z_corr, W, Phi_Rk

```

```{python}
var_features = r.var_features #import var features from seurat
var_features_df = pd.Series(data=np.full(len(adata.var_names), False), index = adata.var_names) #create df of all genes, initialized with "False"

#if gene in var_features, set to "True"
for i,gene_name in enumerate(var_features_df.index):
  if gene_name in var_features:
    var_features_df[i] = True
  else:
    var_features_df[i] = False

#take only var features
adata.var['highly_variable'] = var_features_df
```

```{python}

if(rpk == False):
  sc.pp.normalize_per_cell(adata) #don't normalize because it can be already normalized

adata = adata[:,adata.var['highly_variable']].copy()
sc.pp.scale(adata, zero_center=False, max_value=50)
sc.tl.pca(adata, use_highly_variable=False)
```

```{python}
sc.pl.pca_variance_ratio(adata, log=True)
plt.savefig("./Data/cnmf/PCA_patients_"+suffix)
```

```{python}
harmony_res = run_harmony(adata.obsm['X_pca'], adata.obs, 'patient.ident')
```

```{python}
X = np.array(adata[:,adata.var['highly_variable']].X)
_, X_corr, _, _ = moe_correct_ridge(X.T, None, None, harmony_res.R, None, harmony_res.K, None, harmony_res.Phi_moe, harmony_res.lamb)
X_corr = X_corr.T
adata.obsm['X_pca_harmony'] = harmony_res.Z_corr.T
```

```{python}
sc.pl.umap(adata, color=['orig.ident'])
plt.savefig('./Data/orig_umap' + suffix, dpi=199)
```

```{python}
sc.pp.neighbors(adata, n_pcs=25, use_rep='X_pca_harmony')
sc.tl.umap(adata) #error when running on server
plt.savefig('./Data/corrected_umap.png')

```


```{python}
adata_corr = adata[:,adata.var['highly_variable']].copy()
adata_corr.X = X_corr
X_corr_nonneg = X_corr.copy()
X_corr_nonneg[X_corr_nonneg<0]= 0
adata_corr_nonneg = adata_corr.copy()
adata_corr_nonneg.X = X_corr_nonneg
sc.write('./Data/cnmf/lung_Harmony_NoNeg_' + suffix +'.h5ad', adata_corr_nonneg)
```


cNMF:

```{python}
name = 'cNMF_patients_Varnorm_Harmony_' + suffix
outdir = './Data/cnmf'
K_range = np.arange(3,10)
cnmf_obj = cNMF(output_dir=outdir, name=name)
counts_fn='./Data/cnmf/lung_Harmony_NoNeg_' + suffix +'.h5ad'
if (provideTPM == True):
  tpm_fn = counts_fn
else:
  tpm_fn = None

cnmf_obj.prepare(counts_fn=counts_fn, components=K_range, n_iter=n_iter, seed=14,tpm_fn=tpm_fn,densify=densify)
```

```{python}
cnmf_obj.factorize(worker_i=0, total_workers=1)
```

```{python}
cnmf_obj.combine()
cnmf_obj.k_selection_plot()
```

```{python}
import pickle
f = open('./Data/cnmf/cnmf_objects/patients_' + suffix +'_cnmf_obj.pckl', 'wb')
pickle.dump(cnmf_obj, f)
f.close()
```


